### ISSUE TITLE
ubutu server 16.04 glpi-ocsinventoryng-1.2.1.tar for php7.0 problem

### ISSUE THREAD

**Issue by tingcom3** [pluginsGLPI/ocsinventoryng#10]
Dear friends Hello, my English is not good, if not explain, please forgive me.
This is the problem. I use server Ubuntu 16.04 to install glpi 0.93 (referred to as glpi), the plug-in using the glpi-ocsinventoryng-1.2.1.tar version, in the glpi page to add a computer to import, click on nothing. View the Apache log prompt as follows:
PHP Fatal error: Uncaught Error: Call to a member function fetch_assoc (on) Boolean in /usr/share/glpi09/inc/dbmysql.class.php:280\nStack trace:\n#0 /usr/share/glpi09/plugins/ocsinventoryng/inc/ocsdbclient.class.php (437): DBmysql->fetch_assoc (false) \n#1 /usr/share/glpi09/plugins/ocsinventoryng/inc/ocsserver.class.php (3209): PluginOcsinventoryngOcsDbClient->getComputers (Array) \n#2 /usr/share/glpi09/plugins/ocsinventoryng/front/ocsng.import.php (111): PluginOcsinventoryngOcsServer:: showComputersToAdd ('1', false,'all', 0, Array) \n#3 {main}\n thrown in /usr/share/glpi09/inc/dbmysql.class.php on line 280, referer: http://192.168.2.11/glpi/plugins/ocsinventoryng/front/ocsng.php

Excuse me, glpi-ocsinventoryng-1.2.1 on the PHP7.0, whether there is a problem.

**Comment by tsmr** [comment]
Do you have setup a OCS Server into the plugin ?

**Comment by tingcom3** [comment]
Sorry, there are a few days a little thing, no time to see the forum and email. Many thanks for your reply. Yes, is GLPI under the plug-in glpi-ocsinventoryng-1.2.1. According to the log prompt, it seems that glpi-ocsinventoryng-1.2.1 is php7.0 to produce compatible problems. Does this have a way to solve it.

**Comment by tsmr** [comment]
I have the same version (PHP 7 & plugin version)  and i have no problem with it.

Have you logs into /glpi/files/_log/

**Comment by tingcom3** [comment]
Has been installed for many times, and ultimately failed. In addition, this problem does not appear on the old system. What do you use the Linux version of the release, I was using the server Ubuntu 16.04 version of the.

**Comment by tsmr** [comment]
What is you mysql version ?

**Comment by tingcom3** [comment]
Is mysql5.7

**Comment by tsmr** [comment]
Due to that, i think.

Downgrade to 5.5 do the job

**Comment by tsmr** [comment]
I think is linked to that : https://github.com/glpi-project/glpi/issues/627

Can you test to drop strict mode ?

**Comment by tingcom3** [comment]
Problems may be here. Because the old version of the system using mysql5.6, the use of the new system 5.7. Thank you very much for this friend, I test it.

**Comment by tingcom3** [comment]
Just looked at the mysql, it couldn't handle. It requires new plug-in to solve this. Thanks for the help from tsmr.English is not good, please forgive me
