### ISSUE TITLE
import error : Table 'ocsweb.securitycenter' doesn't exist

### ISSUE THREAD

**Issue by fgent** [pluginsGLPI/ocsinventoryng#102]
OCS Inventory NG is configured to run automatic import, it works but only the computer name, serial, OS and OS serial are imported from OCS. In sql-errors.log we get an error :
 *** MySQL query error:
  SQL: SELECT `securitycenter`.`SCV` AS scv,
                          `securitycenter`.`CATEGORY` AS category,
                          `securitycenter`.`HARDWARE_ID` AS HARDWARE_ID,
                          `securitycenter`.`COMPANY` AS company,
                          `securitycenter`.`PRODUCT` AS product,
                          `securitycenter`.`VERSION` AS version,
                          `securitycenter`.`ENABLED` AS enabled,
                          `securitycenter`.`UPTODATE` AS uptodate
                   FROM `securitycenter`
                   WHERE `HARDWARE_ID` IN (95)
  Error: Table 'ocsweb.securitycenter' doesn't exist

Plugin ocsinventoryng 1.3
GLPI 9.1
OCS 2.2.1

Any idea ?

**Comment by tsmr** [comment]
Hello.

Can you try the 1.3.3 version of the plugin at first approch ?

**Comment by fgent** [comment]
Indeed, it works like a charm after upgrades to GLPI 9.1.6 and Plugin ocsinventoryng 1.3.3
