### ISSUE TITLE
GLPI from OCS assettag

### ISSUE THREAD

**Issue by fartigue** [pluginsGLPI/ocsinventoryng#11]
Hello,

It would be great to get Assettag from BIOS information of GLPI.
So we could set the assettag directly on the computer.

Is it possible ?

**Comment by tsmr** [comment]
This value exists into OCS database ?

**Comment by fartigue** [comment]
Hi Xavier,

Can we speak french ?

La valeur existe, c’est le champ ASSETTAG de type varchar(255) dans la table bios

De : Xavier CAILLAUD [mailto:notifications@github.com]
Envoyé : mercredi 20 juillet 2016 09:21
À : pluginsGLPI/ocsinventoryng
Cc : Florent ARTIGUE; Author
Objet : Re: [pluginsGLPI/ocsinventoryng] GLPI from OCS assettag (#11)


This value exists into OCS database ?

**Comment by tsmr** [comment]
En fait je le fait déjà en dernière version du plugin.

Par contre il faut que la donnée soit présente dans la table bios d'OCS et avoir activer l'option dans "Informations générales"

**Comment by fartigue** [comment]
Merci pour votre réponse rapide.

Dans l’onglet information générale, pour le numéro d’inventaire, je ne peux sélectionner que HARDWARE_ID ou TAG. Je ne peux pas sélectionner ASSETTAG.
Y-aurait-t-il une ruse ?

**Comment by tsmr** [comment]
![image](https://cloud.githubusercontent.com/assets/13178158/16987809/64c9a6f2-4e8e-11e6-8b52-d072af5abc5e.png)

**Comment by fartigue** [comment]
Cette option est bien activée mais les informations liées à ASSETTAG, ne remontent pas, ni dans le champ « Numéro d’inventaire » ni nulle part ailleurs.

Je ne comprends pas…

De : Xavier CAILLAUD [mailto:notifications@github.com]
Envoyé : mercredi 20 juillet 2016 15:27
À : pluginsGLPI/ocsinventoryng
Cc : Florent ARTIGUE; Author
Objet : *** BULK *** Re: [pluginsGLPI/ocsinventoryng] GLPI from OCS assettag (#11)


[image]<https://cloud.githubusercontent.com/assets/13178158/16987809/64c9a6f2-4e8e-11e6-8b52-d072af5abc5e.png>

**Comment by tsmr** [comment]
1. Verifier si le champ assettag dans ocsweb.bios contient une valeur
2. Activer l'option bios dans le plugin
3. Forcer la synchronisation du PC
4. Onglet composants - aller dans la partie Bios et cliquer sur le Nom du Bios
5. Le champ Asset Tag : 
![image](https://cloud.githubusercontent.com/assets/13178158/16988961/84fb9e68-4e92-11e6-82e9-832f06644884.png)

**Comment by fartigue** [comment]
Parfait merci en effet le numéro d’asset remonte.

Mais ne serait-il pas possible, par exemple dans une prochaine version, de pouvoir utiliser ce numéro directement dans l’élément Ordinateur, champ numéro d’inventaire ? cela faciliterait les recherches et l’affichage

Dans tous les cas, merci pour votre aide.

Bonne journée,

Florent ARTIGUE

De : Xavier CAILLAUD [mailto:notifications@github.com]
Envoyé : mercredi 20 juillet 2016 15:57
À : pluginsGLPI/ocsinventoryng
Cc : Florent ARTIGUE; Author
Objet : Re: [pluginsGLPI/ocsinventoryng] GLPI from OCS assettag (#11)


  1.  Verifier si le champ assettag dans ocsweb.bios contient une valeur
  2.  Activer l'option bios dans le plugin
  3.  Forcer la synchronisation du PC
  4.  Onglet composants - aller dans la partie Bios et cliquer sur le Nom du Bios
  5.  Le champ Asset Tag : [image] <https://cloud.githubusercontent.com/assets/13178158/16988961/84fb9e68-4e92-11e6-82e9-832f06644884.png>

**Comment by tsmr** [comment]
Je pense qu'on pourrait l'afficher dans le bloc lié à la liaison OCS Inventory NG en plus du Bios.

**Comment by SylvieCozic** [comment]
Bonjour,

C'est également une information dont j'ai besoin de manière plus centrale que dans le détail du bios

De mon côté, j'ai modifié la classe ocsserver.class.php pour remonter cette info dans le champ "otherserial" (affiché en français en tant que "Numéro d'inventaire").

Modification de la fonction getOcsFieldsMatching :

```
   /**
    * Return field matching between OCS and GLPI
    *
    * @return array of glpifield => ocsfield
    **/
   static function getOcsFieldsMatching() {

      // Manufacturer and Model both as text (for rules) and as id (for import)
      return array('manufacturer'                     => array('BIOS', 'SMANUFACTURER'),
                     'manufacturers_id'                 => array('BIOS', 'SMANUFACTURER'),
                     'os_license_number'                => array('HARDWARE', 'WINPRODKEY'),
                     'os_licenseid'                     => array('HARDWARE', 'WINPRODID'),
                     'operatingsystems_id'              => array('HARDWARE', 'OSNAME'),
                     'operatingsystemversions_id'       => array('HARDWARE', 'OSVERSION'),
                     'operatingsystemservicepacks_id'   => array('HARDWARE', 'OSCOMMENTS'),
                     'domains_id'                       => array('HARDWARE', 'WORKGROUP'),
                     'contact'                          => array('HARDWARE', 'USERID'),
                     'name'                             => array('META', 'NAME'),
                     'comment'                          => array('HARDWARE', 'DESCRIPTION'),
                     'serial'                           => array('BIOS', 'SSN'),
++                     'otherserial'                      => array('BIOS', 'ASSETTAG'),
                     'model'                            => array('BIOS', 'SMODEL'),
                     'computermodels_id'                => array('BIOS', 'SMODEL'),
                     'TAG'                              => array('ACCOUNTINFO', 'TAG')
      );
   }
```

Modification de la fonction updateBios :

```
   /**
    * Update the computer bios configuration
    *
    *
    * @param $computers_id integer : ocs computer id.
    * @param $ocsid integer : glpi computer id
    * @param $plugin_ocsinventoryng_ocsservers_id integer : ocs server id
    * @param $cfg_ocs array : ocs config
    * @param $computer_updates array : already updated fields of the computer
    * @param $dohistory boolean : log changes?
    * @param entities_id the entity in which the computer is imported
    *
    * @return nothing.
    **/
   static function updateBios($computers_id, $ocsComputer, $plugin_ocsinventoryng_ocsservers_id, $cfg_ocs,
   $computer_updates, $dohistory=2, $entities_id=0){

      $compupdate = array();
      $computer = $ocsComputer;
      if (!is_null($computer)) {
         $compudate  = array();
         $bios = $computer['BIOS'];

         if ($cfg_ocs["import_general_serial"]
               && $cfg_ocs["import_general_serial"] > 0
                  && intval($cfg_ocs["import_device_bios"]) > 0
                     && !in_array("serial", $computer_updates)){
            $compupdate["serial"] = self::encodeOcsDataInUtf8($cfg_ocs['ocs_db_utf8'],
            $bios["SSN"]);
         }

++         if ($cfg_ocs["import_general_serial"]
++               && $cfg_ocs["import_general_serial"] > 0
++                  && intval($cfg_ocs["import_device_bios"]) > 0
++                     && !in_array("otherserial", $computer_updates)){
++            $compupdate["otherserial"] = self::encodeOcsDataInUtf8($cfg_ocs['ocs_db_utf8'],
++            $bios["ASSETTAG"]);
++         }
++
         if (intval($cfg_ocs["import_general_model"]) > 0
               && intval($cfg_ocs["import_device_bios"]) > 0
                  && !in_array("computermodels_id", $computer_updates)) {

```

Modification de la fonction showComputersToAdd :

```
               if (isset($data['BIOS']) && count($data['BIOS'])) {
                  $hardware[$id]["serial"]       = $data['BIOS']["SSN"];
                  $hardware[$id]["model"]        = $data['BIOS']["SMODEL"];
                  $hardware[$id]["manufacturer"] = $data['BIOS']["SMANUFACTURER"];
++                  $hardware[$id]["otherserial"]  = $data['BIOS']["ASSETTAG"];
               } else {
                  $hardware[$id]["serial"]       = '';
                  $hardware[$id]["model"]        = '';
                  $hardware[$id]["manufacturer"] = '';
++                  $hardware[$id]["otherserial"]  = '';
               }
            }
```

PI, c'est une rustine et pour une "vraie" mise en prod, il faudrait que ce soit une option d'import à choisir, qu'on vérifie si la valeur a été modifiée, ...

Donc c'est juste pour dépanner fartigue ou tout autre personne qui acceptera le caractère "rustine" de cette modif :)

Cdt,

_Sylvie_

**Comment by fartigue** [comment]
Merci Sylvie, la modification marche parfaitement, même si ca reste une rustine ça répond à mon besoin.

**Comment by SylvieCozic** [comment]
De rien Florent.

Je laisse l'équipe du plugin OCS décider du sort de cette demande :wink: 

Cdt,

_Sylvie_

**Comment by tsmr** [comment]
Le mieux est de l'ajouter ici : 

![image](https://cloud.githubusercontent.com/assets/13178158/17517914/e09cf2f4-5e45-11e6-961d-85694adf4c5f.png)
