### ISSUE TITLE
[GLPI 9.2 - OCSInventoryNG 1.4] script not working

### ISSUE THREAD

**Issue by chauchse** [pluginsGLPI/ocsinventoryng#115]
Dears,

When i launch php script for synchronise GLPI and OCSInventory, i have some errors 👍 
`root@XXXXXX:/var/www/glpi# php5.6 plugins/ocsinventoryng/scripts/ocsng_fullsync.php
PHP Warning:  include(../../../inc/includes.php): failed to open stream: No such file or directory in /var/www/glpi/plugins/ocsinventoryng/scripts/ocsng_fullsync.php on line 50
PHP Warning:  include(): Failed opening '../../../inc/includes.php' for inclusion (include_path='.:/usr/share/php') in /var/www/glpi/plugins/ocsinventoryng/scripts/ocsng_fullsync.php on line 50
PHP Fatal error:  Class 'Toolbox' not found in /var/www/glpi/plugins/ocsinventoryng/scripts/ocsng_fullsync.php on line 58
`
NB : Simple sync from GLPI GUI is working

Thank you for helping.

**Comment by tsmr** [comment]
try this : 
chmod +x /var/www/glpi/plugins/ocsinventoryng/scripts/ocsng_fullsync.sh

and launch
/var/www/glpi/plugins/ocsinventoryng/scripts/ocsng_fullsync.sh --server_id=1

**Comment by chauchse** [comment]
Hi,

Thank you for replying.

But that is not a right problem.

www-data is the owner and i can execute the script.

`You have new mail in /var/mail/root
root@XXXXX:/var/www/glpi# tail files/_log/ocsng_fullsync.log                                                      #0 /var/www/glpi/inc/dbmysql.class.php(79): DBmysql->connect(NULL)
#1 /var/www/glpi/inc/dbconnection.class.php(196): DBmysql->__construct()
#2 /var/www/glpi/inc/dbconnection.class.php(276): DBConnection::switchToMaster()
#3 /var/www/glpi/inc/config.php(78): DBConnection::establishDBConnection(0, 1)
#4 /var/www/glpi/inc/includes.php(57): include_once('/var/www/glpi/i...')
#5 /var/www/glpi/plugins/ocsinventoryng/scripts/ocsng_fullsync.php(50): include('/var/www/glpi/i...')
#6 {main}
  thrown in /var/www/glpi/inc/dbmysql.class.php on line 105
cleaning up.
jeudi 19 octobre 2017, 16:47:32 (UTC+0200) ended
`

**Comment by tsmr** [comment]
you cannot use like that

cd plugins/ocsinventoryng/scripts/
php5.6 ocsng_fullsync.php

**Comment by chauchse** [comment]
That was the result of my first post 👍 
`root@XXXXX:/var/www/glpi# php5.6 plugins/ocsinventoryng/scripts/ocsng_fullsync.php                                PHP Warning:  include(../../../inc/includes.php): failed to open stream: No such file or directory in /var/www/glpi/plugins/ocsinventoryng/scripts/ocsng_fullsync.php on line 50
PHP Warning:  include(): Failed opening '../../../inc/includes.php' for inclusion (include_path='.:/usr/share/php') in /var/www/glpi/plugins/ocsinventoryng/scripts/ocsng_fullsync.php on line 50
PHP Fatal error:  Class 'Toolbox' not found in /var/www/glpi/plugins/ocsinventoryng/scripts/ocsng_fullsync.php on line 58
You have new mail in /var/mail/root
`

**Comment by tsmr** [comment]
No.
You must go on the scripts folder before launch php file

**Comment by chauchse** [comment]
Ha ok.
Sorry.

Script is working.
So there is a version of PHP to precise in my crontab.

Thanks a lot
