### ISSUE TITLE
Debian9 php7 -  problem with ocsng_fullsync.sh

### ISSUE THREAD

**Issue by o71** [pluginsGLPI/ocsinventoryng#116]
Hello

- The version of the plugin : 1.4.2 
- The version of your GLPI : 9.2

To make the script work properly I had to:
- Add the file /glpi/config/based_config.php. It does not exist in the new version of glpi (9.2), I had to copy the file of my old version of glpi (9.1.6). Is it a bug or an error on my part?
- I replaced the php command by php5 in the ocsng_fullsync.sh script. Is the plugin compatible with php7?

Thank you.

**Comment by o71** [comment]
For the based_config.php file I think it's a GLPI bug : https://github.com/glpi-project/glpi/pull/2862

**Comment by tsmr** [comment]
Is the plugin compatible with php7?

Yes it is

**Comment by o71** [comment]
Thank you. It's my fault. I forgot to install php-mysqli for php7.
Now it works.

The problem remains with the /glpi/config/based_config.php file. I hope Glpi version 9.2.1 will solve it automatically.

Thanks

**Comment by o71** [comment]
I think, the based_config.php file have change of directory.
You should modify the file glpienv.php 


`define("GLPI_ROOT", "../../..");`
`//include GLPI_ROOT . "/config/based_config.php";`
`include GLPI_ROOT . "/inc/based_config.php";`
`echo "GLPI_LOG_DIR=" . GLPI_LOG_DIR . "\n";`
`echo "GLPI_LOCK_DIR=" . GLPI_LOCK_DIR . "\n";`

Is it the solution ?

**Comment by o71** [comment]
Hello @tsmr 

What do you think about my last comment ?

Thanks

**Comment by tsmr** [comment]
Yes it's the solution. I commit a fix.
