### ISSUE TITLE
CPU do not import

### ISSUE THREAD

**Issue by CIVODUL4** [pluginsGLPI/ocsinventoryng#118]
Hi,

I just setup two servers to replace my old glpi / ocs infrastructure.

The OCS server is 2.3.1.
The GLPI is 9.1.6.
The plugin is 1.3.4 ( trie1d 1.3.2 and 1.3.3 with no more success ).

When I import computers, the cpu information is lost.

Database version is 7011 ( 7006 min ) and the option to import cpu is ticked. No error in Glpi log ....I don't know where to search.

Thank your for your help.

**Comment by tsmr** [comment]
And yours agents ? which version ?

**Comment by CIVODUL4** [comment]
2.0.5

**Comment by tsmr** [comment]
Try update it to 2.3.1 version please

**Comment by amma35** [comment]
I'm closing for now without answer, feel free to reopen if issue persists.

**Comment by CIVODUL4** [comment]
Sorry for the late reply, upgrading agents did the trick !

Thank you for your support.
