### ISSUE TITLE
Import SNMP data from OCS

### ISSUE THREAD

**Issue by tsmr** [pluginsGLPI/ocsinventoryng#12]
From FactorX - Gille Dubois Thanks to him

# Import SNMP from OCS

Ticket : https://forge.glpi-project.org/issues/5491

Manquant coté GLPI : 

* TODO : Autre Composant (DevicePci) pour Ventilateur - Matériel réseau - Soumettre PR
* Champ Uptime (Objets de l'inventaire) [OK - Tsmr - Traité autrement]

Manquant dans le plugin :

* Import
  * Choix du type d'objet a créer [OK - Tsmr]
  * Liaison avec objets existants [OK - Tsmr]
  * Choix des données à importer / écraser [OK - Tsmr]

* Synchronisation
  * Choix des données à importer / écraser [OK - Tsmr]

* Process
  * Si objet supprimé de l'inventaire GLPI - Vider la table glpi_plugin_ocsinventoryng_snmpocslinks [OK - Tsmr]
  * Listing des liens pour suppression si besoin [OK - Tsmr]
  * Ajout d'un tableau depuis les objets pour voir les informations (comme d'uptime & forcer la synchronisation) [OK - Tsmr]
  * TODO : Vérifier les objets à gérer : 'Computer', 'NetworkEquipment', 'Peripheral', 'Phone', 'Printer' ?
  * TODO : More import : to inventory snmp_cards, snmp_memories, snmp_trays etc
  * Ajout en mode debug du contenu du tableau SNMP [OK - Tsmr]
  * TODO : Stocker les données des cartouches et bacs des imprimantes / cartes pour switchs
  * Ajout d'un moteur de recherche pour l'import / lien [OK - Tsmr]

**Comment by dwtz** [comment]
Do i need a new rule for snmp import? I can browse all snmp devices but could not import it.
Message: SNMP objects not imported. Inventory and ipdiscover import is working fine.

**Comment by tsmr** [comment]
Can new open a new thread please ? This thread is here to finalize the feature.
