### ISSUE TITLE
Bug in right for computer to link/import

### ISSUE THREAD

**Issue by yllen** [pluginsGLPI/ocsinventoryng#122]
showComputersToAdd is call to import or to link computer.
So link for check all must be display if you have one of these rights

**Comment by yllen** [comment]
PR: https://github.com/pluginsGLPI/ocsinventoryng/pull/121/commits/d0356a43740dfb107cfe95852244d5c56d168656

**Comment by amma35** [comment]
Fix in https://github.com/pluginsGLPI/ocsinventoryng/commit/f4df8bc3fa22981a4706e34ac3c730fc9ab1d5be
