### ISSUE TITLE
the selected service is not active. 

### ISSUE THREAD

**Issue by jasongerhardt1903** [pluginsGLPI/ocsinventoryng#125]
Dear team,

i crash into this issue when i implement ocs-glpi on a redhat 7.4 server.

- The version of the plugin. 1.2.2
- The version of your GLPI. 0.9.0
- The steps to reproduce your issue.
yum install ocsinventory 2.1.2
yum install glpi
then install and enable plugin ocsinventoryng 
in tool-->ocsinventoryng i see this error.

Thank you for your help ahead.

Best Reagrds,
Jason Gerhardt

**Comment by amma35** [comment]
Can you give screenshots of your error?

**Comment by amma35** [comment]
I'm closing for now without answer, feel free to reopen if issue persists.
