### ISSUE TITLE
Adding options for importing data with the user

### ISSUE THREAD

**Issue by amma35** [pluginsGLPI/ocsinventoryng#127]
Added options for data import:
User informations
- Affect user location by default
- Affect user from contact
- Affect first group of user by default

![setup](https://user-images.githubusercontent.com/15138371/34214850-f2be9d2a-e5a3-11e7-9b32-181504c06139.png)

**Comment by wawax** [comment]
Hi @amma35 I suggest that you check the new business rules for asset that I'm introducing here : https://github.com/glpi-project/glpi/pull/3330 :)
