### ISSUE TITLE
could not synch computer with 1.2.2

### ISSUE THREAD

**Issue by hbbk** [pluginsGLPI/ocsinventoryng#130]
hi when trying to sync computers after update I got the following error with glpi 0.90.5 
any ideas please ?

[/var/log/apache2/php_errors.log] [15-Jan-2018 10:41:06 Europe/Berlin] PHP Fatal error:  Uncaught Error: Call to a member function add() on boolean in /www/sites/glpi-0.90.5/plugins/ocsinventoryng/inc/networkport.class.php:110
[/var/log/apache2/php_errors.log] Stack trace:
[/var/log/apache2/php_errors.log] #0 /www/sites/glpi-0.90.5/plugins/ocsinventoryng/inc/networkport.class.php(309): PluginOcsinventoryngNetworkPort::updateNetworkPort('00:19:99:c1:e7:...', 'eth0', '2444', 'NetworkPortEthe...', Array, Array, false, 2, Array)
[/var/log/apache2/php_errors.log] #1 /www/sites/glpi-0.90.5/plugins/ocsinventoryng/inc/ocsserver.class.php(3974): PluginOcsinventoryngNetworkPort::importNetwork('1', Array, Array, '2444', 2, '0')
[/var/log/apache2/php_errors.log] #2 /www/sites/glpi-0.90.5/plugins/ocsinventoryng/inc/ocsserver.class.php(2377): PluginOcsinventoryngOcsServer::updateDevices('Item_DeviceNetw...', '2444', Array, '1', Array, Array, Array, 2)
[/var/log/apache2/php_errors.log] #3 /www/sites/glpi-0.90.5/plugins/ocsinventoryng/front/ocsng.sync.php(49): PluginOcsinventoryngOcsServer::updateComputer(3682, '1', 2)
[/var/log/apache2/php_errors.log] #4 {main}
[/var/log/apache2/php_errors.log]   thrown in /www/sites/glpi-0.90.5/plugins/ocsinventoryng/inc/networkport.class.php on line 110

**Comment by amma35** [comment]
plugin version?

**Comment by hbbk** [comment]
1.2.2
but I personally don't need to solve this issue anymore, we switched to a brand new system :)

**Comment by amma35** [comment]
Ok thanks for your return, it was an old version that should have been updated in all cases.
