### ISSUE TITLE
Sync problems

### ISSUE THREAD

**Issue by CarlosGallegoA** [pluginsGLPI/ocsinventoryng#137]
Hello,

I recently install and configure OCSInventory Version 2.4 on a server OracleLinux whit more than 7000 computers inventored, OCS work's fine.

Now install the GLPI 9.2.2 and the  plugin OCSINVENTORYNG 1.4.3

Plugin can import the computers information, but not import software. 

The configuration package has next configuration

Linked objects
Software = Unit Import

The php_errors show this error. 

> 2018-03-09 12:59:59 [6@emt-inventario.epmcc-pob.com]
  *** PHP Notice(8): Undefined variable: groups_id
  Backtrace :
  ...ins/ocsinventoryng/inc/ocsserver.class.php:2793
  plugins/ocsinventoryng/front/ocsng.sync.php:51     PluginOcsinventoryngOcsServer::updateComputer()
2018-03-09 12:59:59 [6@emt-inventario.epmcc-pob.com]
  *** PHP Notice(8): Undefined variable: groups_id
  Backtrace :
  ...ins/ocsinventoryng/inc/ocsserver.class.php:2795
  plugins/ocsinventoryng/front/ocsng.sync.php:51     PluginOcsinventoryngOcsServer::updateComputer()

>

**Comment by CarlosGallegoA** [comment]
Server information 


Operating system

    OS Name :    Linux x86_64
    Version :    4.1.12-94.3.9.el7uek.x86_64
    RAM installed : 9741 MB
    Free RAM : 8511 MB
    CPU :Intel(R) Xeon(R) Gold 5120 CPU @ 2.20GHz
    Distribution :  Oracle Linux Server 7.4
 

Software

    PHP Version :  5.6.32
    Web Server : Apache/2.4.6 () OpenSSL/1.0.2k-fips PHP/5.6.32 mod_perl/2.0.10 Perl/v5.16.3
    Database Server :  MySQL Community Server (GPL) version 5.7.21
    Version OCSReports:    2.4

**Comment by steph78630** [comment]
Hi @CarlosGallegoA 

for info, I use OCS v. **2.4** with GLPI v. **9.2.1** and its plugin v. **1.43** :

The software goes back well in GLPI (but we have a few hundred machines only to process - not 7000)

Regards, Stéphane

**Comment by fgendorf** [comment]
For me, only 3 hundred of machines, with GLPI 9.2.2, OCS 2.4 plugin 1.43,
it works great!

_________________________
Frederico Gendorf

**Comment by drTr0jan** [comment]
I've the problem with 'Undefined variable: groups_id' in the log too.
GLPI 9.2.2, OCS 2.3, plugin 1.4.3

**Comment by CarlosGallegoA** [comment]
Hi, 

Thanks a lot for your help, after applied your fix and update php work's fine. 

Regards.
