### ISSUE TITLE
Duplicate entry in glpi_items_operatingsystems after date fields added

### ISSUE THREAD

**Issue by drTr0jan** [pluginsGLPI/ocsinventoryng#138]
GLPI 9.2.2, Plugin 1.4.3
I've an errors in the SQL log after upgrading to 9.2.2 and 1.4.3, ex:
```
2018-03-19 21:10:20 [@servicedesk-2.domain.lan]
  *** MySQL query error:
  SQL: INSERT
                   INTO `glpi_items_operatingsystems` (`items_id`,`itemtype`,`operatingsystems_id`,`operatingsystemversions_id`,`operatingsystemservicepacks_id`,`operatingsystemarchitectures_id`,`license_number`,`license_id`,`is_dynamic`,`entities_id`,`is_recursive`,`date_creation`,`date_mod`) VALUES ('272','Computer','5','4','5','2','XXXXX-3X4F3-XXXXX-X7PKK-XXXXX','00000-000-1506045-00000','1','0','0','2018-03-19 21:10:00','2018-03-19 21:10:00')
  Error: Duplicate entry '272-Computer-5-2' for key 'unicity'
  Backtrace :
  inc/commondbtm.class.php:504
  inc/commondbtm.class.php:928                       CommonDBTM->addToDB()
  ...ins/ocsinventoryng/inc/ocsserver.class.php:3566 CommonDBTM->add()
  ...ins/ocsinventoryng/inc/ocsserver.class.php:3596 PluginOcsinventoryngOcsServer::setComputerOS()
  ...ins/ocsinventoryng/inc/ocsserver.class.php:3167 PluginOcsinventoryngOcsServer::updateHardware()
  ...ins/ocsinventoryng/inc/ocsserver.class.php:7427 PluginOcsinventoryngOcsServer::updateComputer()
  :                                                  PluginOcsinventoryngOcsServer::cronocsng()
  inc/crontask.class.php:832                         call_user_func()
  front/cron.php:87                                  CronTask::launch()
```
The error is occured on added a data with NOT NULL date_mod and date_creation fields.

**Comment by amma35** [comment]
Hi,
There should be no duplicate at this location as a reset is performed before.
This case is encountered if this OS has been added manually before.

**Comment by bigben386** [comment]
If it is not a plugin problem, then what is the fix? I also have this issue.

**Comment by drTr0jan** [comment]
Nope, I haven't added the OS manually before. OS has been added by OCSInventory plugin (old version) before without date_mod and date_creation fields.

**Comment by amma35** [comment]
The fields date_mod and date_creation have no impact, the important field is is_dynamic.

**Comment by drTr0jan** [comment]
All records in glpi_items_operatingsystems have the 'is_dynamic' field as '0'.

**Comment by amma35** [comment]
This is a GLPI migration concern in 9.2, we lose the information on the "glpi_items_operatingsystems" table of the "is_dynamic" field value.

So you have to change this manually or OCS will not be able to update itself.

**Comment by bigben386** [comment]
So we should set is_dynamic=1 for all entries in the glpi_items_operatingsystems table to fix this sql error?
I also get this php error at the same time I get the sql error

> 2018-04-13 10:45:02 [@ocs-ng]
  *** PHP Notice(8): Undefined variable: groups_id
  Backtrace :
  ...ins/ocsinventoryng/inc/ocsserver.class.php:2793
  ...ins/ocsinventoryng/inc/ocsserver.class.php:2153 PluginOcsinventoryngOcsSer$
  ...s/ocsinventoryng/scripts/ocsng_fullsync.php:410 PluginOcsinventoryngOcsSer$
  ...s/ocsinventoryng/scripts/ocsng_fullsync.php:290 plugin_ocsinventoryng_impo$
  ...s/ocsinventoryng/scripts/ocsng_fullsync.php:160 SecondPass()
2018-04-13 10:45:02 [@ocs-ng]
  *** PHP Notice(8): Undefined variable: groups_id
  Backtrace :
  ...ins/ocsinventoryng/inc/ocsserver.class.php:2795
  ...ins/ocsinventoryng/inc/ocsserver.class.php:2153 PluginOcsinventoryngOcsSer$
  ...s/ocsinventoryng/scripts/ocsng_fullsync.php:410 PluginOcsinventoryngOcsSer$
  ...s/ocsinventoryng/scripts/ocsng_fullsync.php:290 plugin_ocsinventoryng_impo$
  ...s/ocsinventoryng/scripts/ocsng_fullsync.php:160 SecondPass()

**Comment by drTr0jan** [comment]
@amma35, thx, the plugin works correctly after editing the "is_dynamic" field.

@bigben386, #137.

**Comment by sbraz** [comment]
I can confirm that setting `is_dynamic` to `1` for all records fixed the issue:
```
UPDATE glpi_items_operatingsystems SET is_dynamic=1;
```
