### ISSUE TITLE
Enhance Support for Plugin

### ISSUE THREAD

**Issue by Eon9D** [pluginsGLPI/ocsinventoryng#141]
It would be nice if you add the plugins (Microsoft Office licenses,Antivirus,Windows Update State,Windows Users,OS Informations..) to the view + search criteria.

Thanks

**Comment by amma35** [comment]
Windows Update State,Windows Users,OS Informations are already present in version 1.4.3

**Comment by Eon9D** [comment]
How do i seach for "Antivirus is not up to date" ?
How do i search for "Computer has local user X" ?
..

As mentioned I mean -  "the view + search criteria" - not the function.
Otherwise please send me a screenshot. I have Version 1.4.4.

Thanks

**Comment by amma35** [comment]
Version 1.4.4 is a development version not to be used. 

For the evolutions and the addition of new plugins, we realize the developments according to the customers requests.

The antivirus is present in the core of GLPI.

Example : ![ocs](https://user-images.githubusercontent.com/15138371/41338599-f21de546-6ef2-11e8-91df-41d049ef2844.png)
