### ISSUE TITLE
Error seeing the history of a computer with OCS link

### ISSUE THREAD

**Issue by jedumat** [pluginsGLPI/ocsinventoryng#142]
Hi, I use gplpi 9.1.5 with the plugin ocsinventoryng 1.3.3. 
I have updated the glpi from 9.1.5 to 9.2.2 and the plugin ocsinventoryng to 1.4.3 (for glpi 9.2).

When I see the history of a computer with an OCS link, it shows this error:
Fatal error: Class 'PluginOcsinventoryngItem_DeviceBiosdata' not found in /var/www/cmdb/html/inc/log.class.php on line 397

Greetings.

**Comment by jedumat** [comment]
Hello,
I forget to say that I made a clean installation of the ocsinventory plugin, I'm sorry.

If I do the following, the error does not come out:

Copy from the previous version 1.3.5 the files
... / plugins / ocsinventoryng / inc / devicebiosdata.class.php
... / plugins / ocsinventoryng / inc / item_devicebiosdata.class.php

in the directory ... / plugins / ocsinventoryng / inc / of the new version 1.4.3

I think that in version 1.4.3 are missing that files.

Greetings.

**Comment by amma35** [comment]
Hi,
The files are not missing, this has been migrated into the core of GLPI.

The problem is the content in the logs. This will be difficult to correct. 
The temporary solution is to keep the old files.

The problem will disappear if you perform log purges.

**Comment by jedumat** [comment]
Thanks.
