### ISSUE TITLE
100% memory used on ocsng_fullsync.sh

### ISSUE THREAD

**Issue by enrymari** [pluginsGLPI/ocsinventoryng#143]
When crond run the script for syncronize OCSNG data, server hangs.
The script uses 100% memory (4Gb) and gets lots of memory allocation errors.
This problem don't exist if I don't enable winusers plugin data import.

OCS Inventory NG  ver. 1.4.3
GLPI 9.2.2 - FusionInventory 9.2+1.1

**Comment by amma35** [comment]
We should test with the new version, we tried to improve performance.

**Comment by amma35** [comment]
I'm closing for now without answer, feel free to reopen if issue persists.
