### ISSUE TITLE
Undefined variable in updateComputer()

### ISSUE THREAD

**Issue by jedumat** [pluginsGLPI/ocsinventoryng#146]
Hi, I use gplpi 9.1.5 with the plugin ocsinventoryng 1.3.3.
I have updated the glpi from 9.1.5 to 9.2.2 and the plugin ocsinventoryng to 1.4.3 (for glpi 9.2).

When I synchronyze computers, the php-errors.log shows: 
*** PHP Notice(8): Undefined variable: groups_id
  Backtrace :
  ...ins/ocsinventoryng/inc/ocsserver.class.php:2795 
  plugins/ocsinventoryng/front/ocsng.sync.php:51     PluginOcsinventoryngOcsServer::updateComputer()

It is normal?

Thanks.

**Comment by amma35** [comment]
Duplicate  #137

**Comment by jedumat** [comment]
very thanks!
