### ISSUE TITLE
PluginOcsinventoryngDeviceBiosdata class bug

### ISSUE THREAD

**Issue by SylvieCozic** [pluginsGLPI/ocsinventoryng#15]
Hello,

In inc\devicebiosdata.class.php, items class have an undue "_" .
The first device calling this class will crash the mass import.

Row 37, replace:

   static protected $forward_entity_to = array('PluginOcsinventoryng**_**Item_DeviceBiosdata', 'Infocom');

by

   static protected $forward_entity_to = array('PluginOcsinventoryngItem_DeviceBiosdata', 'Infocom');

Regards,

_Sylvie_

**Comment by amma35** [comment]
What version of OCS Inventoryng you use?

**Comment by SylvieCozic** [comment]
Hello amma35,

We currently use OCS Inventory server 2.1.2.

_Sylvie_

**Comment by SylvieCozic** [comment]
Hello,

Forget it !
I just saw that the undue "_" as already been removed in the last devicebiosdata.class.php file on github.
:-1: 

This issue may be closed.

_Sylvie_
