### ISSUE TITLE
OCS synchronization is not working and automatic synchronization does not work

### ISSUE THREAD

**Issue by crgonzalez4** [pluginsGLPI/ocsinventoryng#151]
The plugin shows results of devices to update, but, after pressing the "synchronize" button, it remains stuck showing what appears to be a blank page.

Automatic synchronization is only executed manually.

httpd/error_log:

PHP Fatal error:  Allowed memory size of 2147483648 bytes exhausted
(tried to allocate 20480 bytes) in /var/www/html/glpi/inc/dbmysql.class.php on line 312, referer: http://inventariocorp.uahurtado.cl/plugins/ocsinventoryng/front/ocsng.sync.php

(tried to allocate 20480 bytes) in Unknown on line 0, referer: http://inventariocorp.uahurtado.cl/plugins/ocsinventoryng/front/ocsng.sync.php

Fatal error: Allowed memory size of 3221225472 bytes exhausted (tried to allocate 262144 bytes) in /var/www/html/glpi/inc/dbmysqliterator.class.php on line 211

/_log/php-errors.log:

2018-06-11 13:36:47 [2@S-INVCORP]
  *** PHP Notice(8): Undefined index: SID
  Backtrace :
  ...ins/ocsinventoryng/inc/ocsserver.class.php:6995
  ...ins/ocsinventoryng/inc/ocsserver.class.php:3282 PluginOcsinventoryngOcsServer::updateWinuser()
  ...ins/ocsinventoryng/inc/ocsserver.class.php:7428 PluginOcsinventoryngOcsServer::updateComputer()
  inc/crontask.class.php:832                         PluginOcsinventoryngOcsServer::cronocsng()
  front/crontask.form.php:49                         CronTask::launch()
2018-06-11 13:36:47 [2@S-INVCORP]
  *** PHP Notice(8): Undefined index: TYPE
  Backtrace :
  ...ins/ocsinventoryng/inc/ocsserver.class.php:6992
  ...ins/ocsinventoryng/inc/ocsserver.class.php:3282 PluginOcsinventoryngOcsServer::updateWinuser()
  ...ins/ocsinventoryng/inc/ocsserver.class.php:7428 PluginOcsinventoryngOcsServer::updateComputer()
  inc/crontask.class.php:832                         PluginOcsinventoryngOcsServer::cronocsng()
  front/crontask.form.php:49                         CronTask::launch()
2018-06-11 13:36:47 [2@S-INVCORP]
  *** PHP Notice(8): Undefined index: DESCRIPTION
  Backtrace :
  ...ins/ocsinventoryng/inc/ocsserver.class.php:6993
  ...ins/ocsinventoryng/inc/ocsserver.class.php:3282 PluginOcsinventoryngOcsServer::updateWinuser()
  ...ins/ocsinventoryng/inc/ocsserver.class.php:7428 PluginOcsinventoryngOcsServer::updateComputer()
  inc/crontask.class.php:832                         PluginOcsinventoryngOcsServer::cronocsng()
  front/crontask.form.php:49                         CronTask::launch()
2018-06-11 13:36:47 [2@S-INVCORP]
  *** PHP Notice(8): Undefined index: DISABLED
  Backtrace :
  ...ins/ocsinventoryng/inc/ocsserver.class.php:6994
  ...ins/ocsinventoryng/inc/ocsserver.class.php:3282 PluginOcsinventoryngOcsServer::updateWinuser()
  ...ins/ocsinventoryng/inc/ocsserver.class.php:7428 PluginOcsinventoryngOcsServer::updateComputer()
  inc/crontask.class.php:832                         PluginOcsinventoryngOcsServer::cronocsng()
  front/crontask.form.php:49                         CronTask::launch()

- The version of the plugin:

OCS Inventory NG | 1.4.3

- The version of your GLPI:
GLPI 9.2.3 ( => /var/www/html/glpi)

**Comment by crgonzalez4** [comment]
where and how to apply this?

**Comment by amma35** [comment]
Do you use the winusers option?

**Comment by crgonzalez4** [comment]
Hi, yes, the plugin is activated. Why?

Do you have any information about why the ocsinventory plugin shows results of devices to update, but, after pressing the "synchronize" button, it remains stuck showing what appears to be a blank page. This behavior appears with any of the option of select 5 computers, 10, etc.

**Comment by amma35** [comment]
We have feedback that this plugin is consumer.
We'd have to test without this plugin to see if it came from him.

**Comment by crgonzalez4** [comment]
I just uninstalled it and the behavior is the same :(

**Comment by amma35** [comment]
1 . Okay, this is not the same problem as this "Fatal error: Allowed memory size of 3221225472" error.
Do you still make that mistake?

2 . The blank page you have, it is at the synchronization level of the "Computers updated in OCSNG" page? (url : ocsinventoryng/front/ocsng.sync.php)
Do you have any errors in the log files when you perform this synchro?

**Comment by crgonzalez4** [comment]
1: Now is no error in php or httpd logs.

2. 
a) plugins/ocsinventoryng/front/ocsng.php
b) Synchronize computers already imported  -> at this moment 73 Computers updated in OCSNG
c) click Synchronize 
d) just show principal menu, link plugins/ocsinventoryng/front/ocsng.sync.php with "waiting" message and here stuck in the page with de principal menu and no data.

no http or php errors in logs

:( :(

**Comment by amma35** [comment]
Okay, can you set the debug mode and do these steps again?

**Comment by crgonzalez4** [comment]
in fact I have it in that mode, if you want you could take control of my computer just to see the symptom

**Comment by amma35** [comment]
You have the same behavior with importing new machines?

**Comment by crgonzalez4** [comment]
no mistake when importing new machines.

Just now a message has just been shown in debug mode when you want to synchronize computers.

Fatal error: Allowed memory size of 2147483648 bytes exhausted (tried to allocate 20480 bytes) in /var/www/html/glpi/inc/commondbtm.class.php on line 1422

Fatal error: Allowed memory size of 2147483648 bytes exhausted (tried to allocate 32768 bytes) in Unknown on line 0

**Comment by amma35** [comment]
Okay, so it's the server that doesn't have enough memory to perform these tasks.

**Comment by crgonzalez4** [comment]
I have been constantly increasing the memory and the error is repeated.

**Comment by crgonzalez4** [comment]
uninstalling and installing the plugin again works. It works for a couple of hours and then fails again. Uninstall and reinstall again and it works again. Everything seems to be related to the plugin.
