### ISSUE TITLE
php-errors.log spammed with 'groups_id' error

### ISSUE THREAD

**Issue by hgpit** [pluginsGLPI/ocsinventoryng#153]
GLPI v9.2.3
OCSInventoryNG v1.4.3
PHP 5.6.36
CentOS 6

Here's a sample of our log file '/var/log/glpi/php-errors.log':

2018-06-22 11:40:03 [@svr-h003011.hayley-group.local]
  *** PHP Notice(8): Undefined variable: groups_id
  Backtrace :
  ...ins/ocsinventoryng/inc/ocsserver.class.php:2795
  ...ins/ocsinventoryng/inc/ocsserver.class.php:2153 PluginOcsinventoryngOcsServer::updateComputer()
  ...s/ocsinventoryng/scripts/ocsng_fullsync.php:410 PluginOcsinventoryngOcsServer::processComputer()
  ...s/ocsinventoryng/scripts/ocsng_fullsync.php:290 plugin_ocsinventoryng_importFromOcsServer()
  ...s/ocsinventoryng/scripts/ocsng_fullsync.php:173 SecondPass()
2018-06-22 11:40:03 [@svr-h003011.hayley-group.local]
  *** PHP Notice(8): Undefined variable: groups_id
  Backtrace :
  ...ins/ocsinventoryng/inc/ocsserver.class.php:2793
  ...ins/ocsinventoryng/inc/ocsserver.class.php:2153 PluginOcsinventoryngOcsServer::updateComputer()
  ...s/ocsinventoryng/scripts/ocsng_fullsync.php:410 PluginOcsinventoryngOcsServer::processComputer()
  ...s/ocsinventoryng/scripts/ocsng_fullsync.php:290 plugin_ocsinventoryng_importFromOcsServer()
  ...s/ocsinventoryng/scripts/ocsng_fullsync.php:173 SecondPass()
2018-06-22 11:40:03 [@svr-h003011.hayley-group.local]
  *** PHP Notice(8): Undefined variable: groups_id
  Backtrace :
  ...ins/ocsinventoryng/inc/ocsserver.class.php:2795
  ...ins/ocsinventoryng/inc/ocsserver.class.php:2153 PluginOcsinventoryngOcsServer::updateComputer()
  ...s/ocsinventoryng/scripts/ocsng_fullsync.php:410 PluginOcsinventoryngOcsServer::processComputer()
  ...s/ocsinventoryng/scripts/ocsng_fullsync.php:290 plugin_ocsinventoryng_importFromOcsServer()
  ...s/ocsinventoryng/scripts/ocsng_fullsync.php:173 SecondPass()
...

No idea how important this is, or if it's having an adverse affect on anything. Our OCS functionality *appears* to work okay, despite this error.

Just thought you might want to know :)

**Comment by amma35** [comment]
Duplicate #137
