### ISSUE TITLE
PHP Fatal error:  Class 'ComputerDisk' not found

### ISSUE THREAD

**Issue by daniejstriata** [pluginsGLPI/ocsinventoryng#154]
- The version of the plugin.
 1.4.3
- The version of your GLPI.
9.3Dev
- The steps to reproduce your issue.
Installed plugin as normal and did first import. Devices are only imported one by one. Does not import all selected devices.
The only error I can see is in Apache's error log.

`[Thu Jun 28 08:08:00.266322 2018] [:error] [pid 2670:tid 139882320033536] [client 10.2.37.44:35368] PHP Fatal error:  Class 'ComputerDisk' not found in /var/www/html/glpi/plugins/ocsinventoryng/inc/ocsserver.class.php on line 6329, referer: http://10.2.39.230/glpi/plugins/ocsinventoryng/front/ocsng.import.php
`

**Comment by amma35** [comment]
The plugin isn't compatible for version 9.3
