### ISSUE TITLE
GLPi 9.3 compatibility

### ISSUE THREAD

**Issue by octvcdrc** [pluginsGLPI/ocsinventoryng#155]
Hi,

Right now the plugin seems to work fine with GLPi 9.3 however the "minimum" version needs to be bumped in order to be able to install it.

Also, the db tables needs to be switched from MyISAM to InnoDB since GLPi switched to InnoDB and complains about it after installation.

Thanks
Regards

**Comment by major697** [comment]
I change MyISAM to InnoDB for all tables, and I have still error: 

> This plugin requires GLPI >= 9.2
--




--





This plugin requires GLPI >= 9.2
--




This plugin requires GLPI >= 9.2
--

**Comment by jairosantosjr** [comment]
1 tables not migrated to InnoDB engine.

**Comment by Cristobal5000** [comment]
I have the same problem: "1 tables not migrated to InnoDB engine "
