### ISSUE TITLE
This plugin requires GLPI >= 9.2 (GLPI 9.3 / OCS Plugin 1.4.4)

### ISSUE THREAD

**Issue by crgonzalez4** [pluginsGLPI/ocsinventoryng#157]
- The version of the plugin.  **1.4.4**
- The version of your GLPI.  **9.3.0**
- The steps to reproduce your issue. **Update GLPI to 9.3.0 and try to install OCS Plugin 1.4.4 then "This plugin requires GLPI >= 9.2" error is displayed**

**Comment by KevinStephane** [comment]
Same probleme for me

**Comment by ejaecker** [comment]
Same here.

**Comment by jairosantosjr** [comment]
the same problem with me.
This plugin requires GLPI >= 9.2
My version is GLPI 9.3.0

**Comment by amma35** [comment]
The version is under development.

**Comment by amma35** [comment]
duplicates https://github.com/pluginsGLPI/ocsinventoryng/issues/155
