### ISSUE TITLE
Probléme connexion Moniteur/Ordinateur 

### ISSUE THREAD

**Issue by jlb5980** [pluginsGLPI/ocsinventoryng#158]
Bonjour

Je viens de voir un probléme de mise à jour au niveau de l'onglet connexion d'un ordinateur dans GLPI .

Explication :

Un moniteur branché sur un ordinateur XXX puis débranché et branché sur un autre ordinateur YYY ne remonte pas sur ce dernier!

Mais reste branché sur l'ancien (XXX) .

Au niveau OCS le moniteur apparait bien branché sur YYY ..!

Mais rien ne change après un nouvel  import  automatique OCS/GLPI; le moniteur est toujours affecter dans glpi à XXX

Seul  la synchronisation manuel permets la mise à jour cette connexion.

note : Pas de verrous sur l'ancien ordinateur XXX

Version : OCS : 2.3.1
GLPI : 9.1.7.1
Plugin : OCS Inventory NG version 1.3.5
Plugin utilisé en Mode de synchronisation expert

Cordialement

**Comment by amma35** [comment]
Bonjour,
Le problème n'est pas présent en dernière version du plugin.
Pouvez-vous essayer en dernière version ?

**Comment by jlb5980** [comment]
bonjour
la derniére version fct avec glpi 9.1.7.1 ? 
Merci

**Comment by amma35** [comment]
Non, nous ne faisons plus de corrections pour la version 9.1

**Comment by jlb5980** [comment]
Bonjour
Dommage ! la version n'est pas si ancienne que cela ( juillet 2017)
Cordialement

**Comment by amma35** [comment]
Ce n'est pas un bug connu

**Comment by tsmr** [comment]
https://github.com/pluginsGLPI/ocsinventoryng/commit/fa93834854b2060234384c3123b8fd732901d778
https://github.com/pluginsGLPI/ocsinventoryng/commit/92119899d11263f5d95b6ff15feea595d8717515
