### ISSUE TITLE
IPDiscover percentage done does not reflect actual value.

### ISSUE THREAD

**Issue by dytrip77** [pluginsGLPI/ocsinventoryng#160]
ocsinventoryng version : 1.5.0
GLPI version : 9.30
Steps to reproduce issue : 

1. Go to Ocsinventoryng in Tools
2. Go to IPDiscover import.
3. In Import IPDiscover, choose All Subnets.

![capture](https://user-images.githubusercontent.com/22068278/42867663-d8012c06-8aa2-11e8-84e4-940c6c3f1735.JPG)

**Comment by tsmr** [comment]
And in OCS web Server ? This data is from OCS DB

**Comment by dytrip77** [comment]
OCS has released new version (2.5) which fixed the counter but error still exist in ocsng for glpi.

![ocsipd](https://user-images.githubusercontent.com/22068278/43434430-2a299652-94ae-11e8-9763-941d4d207e5d.JPG)

![ocsng](https://user-images.githubusercontent.com/22068278/43434433-2edbcfe4-94ae-11e8-821f-3e90ee23f208.JPG)

**Comment by dytrip77** [comment]
Thank you for the fixed. Much appreciated.
