### ISSUE TITLE
Plugin in error a few seconds after enabling it

### ISSUE THREAD

**Issue by Blazfhem** [pluginsGLPI/ocsinventoryng#161]
- The version of the plugin :
1.5.0
- The version of your GLPI. :
9.3.0
- The steps to reproduce your issue :
Installing and enabling the plugin and then wait a little bit.
Plugin pannel says OCS plugin is in error and need to be cleaned :
![image](https://user-images.githubusercontent.com/19334022/43246975-9bf21bf0-90b3-11e8-8146-5394e091417c.png)

**Comment by Blazfhem** [comment]
There was no errors. So finally I decided to revert to glpi 9.1.6 and now it's almost working fine except for automatic sync : I receive a mail every days that says "following automatic actions are in error : ocsng"

And when I check computers that need a sync, the list is full... So every day I manually sync it...

**Comment by amma35** [comment]
This is another problem, we need to create a new issue.
