### ISSUE TITLE
GLPI not import software from OCSNG

### ISSUE THREAD

**Issue by Luchobcn2108** [pluginsGLPI/ocsinventoryng#162]
Hi,

The automatic synchronization software is not working, 
I've got the following set up:
- My plugin version is 1.4.3  .
- My GLPI version is GLPI is 9.2.1

Synchronization method: server is not in expert mode
On automatic action "OCSNG - Launch OCSNG synchronization script" is scheduled and its' running fine.

it doesn't show any software imported 

Thanks

**Comment by amma35** [comment]
Hi, 
What do you have Configuration of OCS : 
Import options - Use the OCSNG software dictionary Yes or No ? 
Datas to import - Linked objects - Software Unit import or not import ? 

We have performed the test, if there have been updates for the machine in OCSNG, the update is done well

**Comment by Luchobcn2108** [comment]
Hi,

Thanks for reply 

In the Import options - Use the OCSNG software dictionary I have Yes
IN Datas to import - Linked objects - I have Software Unit import

**Comment by amma35** [comment]
In the Import options - Use the OCSNG software dictionary I have Yes

it is normal that software does not matter, as explained under this parameter : 
 If Use the OCSNG software dictionary parameter is checked, no software will be imported before you setup them into OCS

**Comment by Luchobcn2108** [comment]
Thanks now it's OK.
