### ISSUE TITLE
GLPI does't import Manufacturer and model from Ocsng

### ISSUE THREAD

**Issue by pcrampette** [pluginsGLPI/ocsinventoryng#163]
Hi,

The automatic synchronization software is not working,
I've got the following set up:

    My plugin version is 1.5 .
    My GLPI version is GLPI is 9.3
    My OCSNG sersion is 2.5 (idem en 2.4)

Synchronization method: server is not in expert mode
On automatic action "OCSNG - Launch OCSNG synchronization script" is scheduled and its' running fine.

it doesn't show any Manufacturer and model in computer imported

Thanks

**Comment by grigribou** [comment]
Hi,

Same issue on GLPI fresh install.
Also using sames versions as PCRAMPETTE.

Regards,

**Comment by amma35** [comment]
The automatic synchronization software is not working, : Duplicate https://github.com/pluginsGLPI/ocsinventoryng/issues/162

Does the automatic action not work or is it only the Manufacturer  & model fields that are not filled?

**Comment by grigribou** [comment]
Software is imported for me!
Its not same as #162

Only manufacturer & Model are not imported.

Fresh install of GLPI 9.3 and plugin 1.5

Let me know how to help, I didn’t found any error in all log I analyzed... I don’t know how else checking ...

Regards,

**Comment by tsmr** [comment]
I found a bug into import data from bios. I push a correction asap

**Comment by tsmr** [comment]
Version released :D 

https://github.com/pluginsGLPI/ocsinventoryng/releases/tag/1.5.1
