### ISSUE TITLE
No Display  Import Option on OCS server and no import some information

### ISSUE THREAD

**Issue by rfrancoba** [pluginsGLPI/ocsinventoryng#164]
Hello, on menu of setup OCS server, Import Options does not appear and it does not matter type, model and manufacturer. I add an image.

![ocssetup en glpi](https://user-images.githubusercontent.com/42107278/43683047-c60c5dca-9873-11e8-929b-9e80c5cea442.png)
---
![pcs glpi](https://user-images.githubusercontent.com/42107278/43683178-d31c45fa-9875-11e8-93ca-c89f9cd2888c.png)
- The version of the plugin ocsinventoryng 1.5
- The version of your GLPI   9.3
- The steps to reproduce your issue:  Upon entering the OCS server setup and entering the equipment menu

Thanks

Ramon

**Comment by tsmr** [comment]
For your first problem : test is ok to database connection ? if yes, can you check your rights into profile for plugin ?

For your second problem : 
see https://github.com/pluginsGLPI/ocsinventoryng/issues/163

**Comment by rfrancoba** [comment]
Hi, 
I did the test to the OCS server and there was no ok.  (Invalid OCSNG configuration (TRACE_DELETED must be active))
for this problem I turned it on TRACE_DELETED on OCS Server. With this I could see import options, Data to import and SNMP imports..

Regards.

Ramon

**Comment by rfrancoba** [comment]
Thank you very much,
this solves the problem of importing model, type an manufacturing when importing new computers. 

Only when  synchronize the computers already imported does not update this information, How can this be resolved?

Regards
Ramon

**Comment by tsmr** [comment]
Do a full import

Version released :D 

https://github.com/pluginsGLPI/ocsinventoryng/releases/tag/1.5.1
