### ISSUE TITLE
No processor in GLPI for AIX 7.1

### ISSUE THREAD

**Issue by dytrip77** [pluginsGLPI/ocsinventoryng#165]
- Plugin version = 1.5.
- GLPI version = 9.3.

Go to Asset>Computers>Open any AIX computer.

Table do exist in OCS db (refer screenshot)

![aix proc](https://user-images.githubusercontent.com/22068278/43756967-be35d90a-9a49-11e8-9423-ee6f05335a80.JPG)

**Comment by tsmr** [comment]
Version of OCS Inventory so old ? upprade it

see https://github.com/pluginsGLPI/ocsinventoryng/issues/100

**Comment by dytrip77** [comment]
Hi,

OCS version is latest one (v2.5).

**Comment by amma35** [comment]
Hi,

You should check if you have php and sql error log. (glpi/files/_log/php-errors.log & sql-errors.log)

Then, the processor is not taken from that table. 
You should check in the OCS 'cpus' table if you find something for the field 'HARDWARE_ID' = 24992

**Comment by AlroneRhyn** [comment]
Hi same issue here :

- OCS Server 2.5 (Version : 7015)
- GLPI 9.3
- OCS Inventory NG Plugin : 1.5.2

Some are synced from OCS to GLPI (servers) : there manufacturer, type, serial, core number,... fields are set. But my Apple and Windows devices, which get only the type, speed and number field, are not.

Thanks

**Comment by amma35** [comment]
@AlroneRhyn Can you create a new issue if only some data is not reported in your case so that we can help you.

**Comment by dytrip77** [comment]
Hi,
Hardware ID for AIX processor does not exist in the said table.

**Comment by tsmr** [comment]
Can you try with last OCS agent ? because the informations were imported from cpus table.

**Comment by dytrip77** [comment]
Still the same. Information does not exist in cpus table. I'm getting help from OCS team to fix AIX agent issue.

**Comment by dytrip77** [comment]
Fixed with custom cpu module. Closing issue.
