### ISSUE TITLE
OS change in historical on each synchronize

### ISSUE THREAD

**Issue by grigribou** [pluginsGLPI/ocsinventoryng#166]
Hi,

OCSNG : 2.5
GLPI : 9.3
Pluging : 1.5.0 & 1.5.0

I show in history a PC imported, OS unlin and link again, on each synchronize run.

![image](https://user-images.githubusercontent.com/8124469/43907274-5f0a346e-9bf5-11e8-87fa-b9beaa2ab5f1.png)

Regards,

**Comment by tsmr** [comment]
It will be in the next release (1.5.1)
