### ISSUE TITLE
GLPI not fetching latest software INSTALLDATE

### ISSUE THREAD

**Issue by mzulfahmy** [pluginsGLPI/ocsinventoryng#168]
Plugin version = 1.5.
GLPI version = 9.3.

On OCS tables got 2 row which same software name & version on the same hardware ID. GLPI importing install date from 0000-00-00 instead.

![1](https://user-images.githubusercontent.com/4937448/44128045-2a6ee6d2-a073-11e8-86af-18ded3ebe3f3.PNG)
![2](https://user-images.githubusercontent.com/4937448/44128046-2aedefb8-a073-11e8-9951-baceff78179c.PNG)

I have made some PHP script logic to fix the issues.
https://pastebin.com/ZWWcQFmM

**Comment by amma35** [comment]
Hi,
The only modification we can make for the moment is to sort on the ID that allows to get the last addition in the OCS table that corresponds to the most recent data so it should get the installation date.
