### ISSUE TITLE
PHP Fatal error:  Class 'Self' not found in \plugins\ocsinventoryng\inc\teamviewer.class.php on line 133

### ISSUE THREAD

**Issue by diegopaz90** [pluginsGLPI/ocsinventoryng#171]
Hi, i have installed plugin version 1.3.5 with glpi 9.1.1 and get this error:
This happens when import a machine that has a team viewer installed and OCS Inventory find its id and version. Not hapening with machines with no id and version in OCS

[Tue Aug 21 09:47:30.562813 2018] [:error] [pid 2436:tid 592] [client 192.168.1.99:5319] PHP Fatal error:  Class 'Self' not found in C:\\wamp\\www\\glpi\\plugins\\ocsinventoryng\\inc\\teamviewer.class.php on line 133, referer: http://192.168.1.159/glpi/front/computer.form.php?id=18
[Tue Aug 21 09:47:30.562813 2018] [:error] [pid 2436:tid 592] [client 192.168.1.99:5319] PHP Stack trace:, referer: http://192.168.1.159/glpi/front/computer.form.php?id=18
[Tue Aug 21 09:47:30.562813 2018] [:error] [pid 2436:tid 592] [client 192.168.1.99:5319] PHP   1. {main}() C:\\wamp\\www\\glpi\\ajax\\common.tabs.php:0, referer: http://192.168.1.159/glpi/front/computer.form.php?id=18
[Tue Aug 21 09:47:30.562813 2018] [:error] [pid 2436:tid 592] [client 192.168.1.99:5319] PHP   2. CommonGLPI::displayStandardTab() C:\\wamp\\www\\glpi\\ajax\\common.tabs.php:97, referer: http://192.168.1.159/glpi/front/computer.form.php?id=18
[Tue Aug 21 09:47:30.562813 2018] [:error] [pid 2436:tid 592] [client 192.168.1.99:5319] PHP   3. PluginOcsinventoryngTeamviewer::displayTabContentForItem() C:\\wamp\\www\\glpi\\inc\\commonglpi.class.php:477, referer: http://192.168.1.159/glpi/front/computer.form.php?id=18
[Tue Aug 21 09:47:30.562813 2018] [:error] [pid 2436:tid 592] [client 192.168.1.99:5319] PHP   4. PluginOcsinventoryngTeamviewer::showForComputer() C:\\wamp\\www\\glpi\\plugins\\ocsinventoryng\\inc\\teamviewer.class.php:84, referer: http://192.168.1.159/glpi/front/computer.form.php?id=18

I tried with the file teamviewer.class.php of plugin version 1.2.3, 1.3.2 , 1.3.3, 1.4.2 and 1.4.3 with no luck. 
I appreciate any help. many thanks!

**Comment by amma35** [comment]
Do not replace the file with another version.
Your problem should be solved by reproducing this correction: https://github.com/pluginsGLPI/ocsinventoryng/commit/1feaefbf8bcfd1399147b9d084b0fa947c589f86
