### ISSUE TITLE
Random freezing ocsng task in CLI mode

### ISSUE THREAD

**Issue by drTr0jan** [pluginsGLPI/ocsinventoryng#172]
ocsinventoryng 1.5.2
glpi 9.3

I've an ocsng task with CLI mode in the GLPI. But sometime the task remains in the running state permanently. I need break the task.
I've traced the `PluginOcsinventoryngOcsServer::cronocsng()` function and found out the function freezes on `PluginOcsinventoryngOcsProcess::manageDeleted($plugin_ocsinventoryng_ocsservers_id)` calling. In turn `PluginOcsinventoryngOcsProcess::manageDeleted()` freezes on the statement:
```
         //If cron, no redirect
         if ($redirect) {
            if (isset($_SERVER['QUERY_STRING']) && $_SERVER['QUERY_STRING'] != "") {
               $redirection = $_SERVER['PHP_SELF'] . "?" . $_SERVER['QUERY_STRING'];
            } else {
               $redirection = $_SERVER['PHP_SELF'];
            }
            Html::redirect($redirection);
         }
```
Why the statement is running if I call the function in a task (cron) mode?
I think the issue is similar #24.

**Comment by amma35** [comment]
Hi,
Indeed by passing the second parameter, the problem should be solved. 
I'll make the correction.
Can you give me a feedback if the correction corrects the problem well?
Thank you for your review.

**Comment by drTr0jan** [comment]
One week uptime. Works correctly.

**Comment by amma35** [comment]
Thank you for your comeback.
