### ISSUE TITLE
Automatic Synchronization not working - cannot get server information - APCU

### ISSUE THREAD

**Issue by ncanqn** [pluginsGLPI/ocsinventoryng#175]
Hi All,
I'm using latest OCS 2.5, GLPI 9.3 and latest OCS Inventory NG 1.5.2 on ubuntu 16.04
I am able to manually import/link new computer from OCS to GLPI but automatic sync script does not work.
I tried to run below command to debug
sudo -u www-data /var/www/glpi/plugins/ocsinventoryng/scripts/ocsng_fullsync.sh --thread_nbr=1 --server_id=1 --nolog --debug

And this is output
Tuesday 28 August 15:03:06 AEST 2018 /var/www/glpi/plugins/ocsinventoryng/scripts/ocsng_fullsync.sh started
        Manage delete items in OCS server #1: "OCS"
PHP Notice:  Undefined offset: 1 in /var/www/glpi/plugins/ocsinventoryng/scripts/ocsng_fullsync.php on line 41
Config::getCache() in /var/www/glpi/inc/config.class.php line 2928
Service with name "Zend\Cache\Storage\Adapter\Apcu" could not be created. Reason: ext/apcu is disabled - see 'apc.enabled' and 'apc.enable_cli' 
Config::getCache() in /var/www/glpi/inc/config.class.php line 2928
Service with name "Zend\Cache\Storage\Adapter\Apcu" could not be created. Reason: ext/apcu is disabled - see 'apc.enabled' and 'apc.enable_cli' =====================================================
        Thread #1: starting (1/1)
        Thread #1: cannot get server information

        Thread #1: done!!
=====================================================
cleaning up.

I already have php-apcu installed as below. Where should I check 'apc.enabled' and 'apc.enable_cli' ?
![image](https://user-images.githubusercontent.com/42762025/44702322-3b55c480-aad6-11e8-97fc-0b0497e5d623.png)

Regards,
Thanks.

**Comment by mzulfahmy** [comment]
Hi,

It seems the apcu.cli is installed but not enabled in the PHP.ini settings.

Could please try to add these line to your php.ini?

**Comment by ncanqn** [comment]
Thank you so much for your help mzulfahmy.
I added following line to /etc/php/7.0/apache2/conf.d/20-apcu.ini where apcu extension config is

```
apc.enabled=1
apc.enable_cli=1

```
There is no more error regarding ACPU but still got error as below. Could you please help further?

sudo -u www-data /var/www/glpi/plugins/ocsinventoryng/scripts/ocsng_fullsync.sh --thread_nbr=1 --server_id=1 --nolog --debug
Tuesday 4 September 10:27:00 AEST 2018 /var/www/glpi/plugins/ocsinventoryng/scripts/ocsng_fullsync.sh started
        Manage delete items in OCS server #1: "AGT-OCS"
**PHP Notice:  Undefined offset: 1** in /var/www/glpi/plugins/ocsinventoryng/scripts/ocsng_fullsync.php on line 41
=====================================================
        Thread #1: starting (1/1)
        Thread #1: **cannot get server information**

        Thread #1: done!!
=====================================================
cleaning up.
Tuesday 4 September 10:27:02 AEST 2018 ended

---
Regards,

**Comment by ncanqn** [comment]
Hi tsmr.
I just upgraded to 1.5.3 and debug output is still exactly the same error PHP Notice: Undefined offset: 1 and **cannot get server information**
sudo -u www-data /var/www/glpi/plugins/ocsinventoryng/scripts/ocsng_fullsync.sh --thread_nbr=1 --server_id=1 --nolog --debug
Wednesday 5 September 07:12:53 AEST 2018 /var/www/glpi/plugins/ocsinventoryng/scripts/ocsng_fullsync.sh started
        Manage delete items in OCS server #1: "OCS"
PHP Notice:  Undefined offset: 1 in /var/www/glpi/plugins/ocsinventoryng/scripts/ocsng_fullsync.php on line 41
=====================================================
        Thread #1: starting (1/1)
        Thread #1: cannot get server information

        Thread #1: done!!
=====================================================
cleaning up.
Wednesday 5 September 07:12:54 AEST 2018 ended

**Comment by amma35** [comment]
see correction for  PHP Notice: Undefined offset: 1

For "cannot get server information" 
You should check in the database in table `glpi_plugin_ocsinventoryng_servers`, what you have as value.
Can you tell us what's in the table?

**Comment by ncanqn** [comment]
Hi amma35,
Thanks a lot for showing me how to fix  PHP Notice: Undefined offset: 1.
After applying the fix, the error is more clearer now. It is database issue this time

```
Wednesday 5 September 22:20:49 AEST 2018 /var/www/glpi/plugins/ocsinventoryng/scripts/ocsng_fullsync.sh started
DBmysql::query() in /var/www/glpi/inc/dbmysql.class.php line 180
  *** MySQL query error:
  SQL: SELECT *
                FROM `glpi_plugin_ocsinventoryng_servers`
                WHERE `plugin_ocsinventoryng_ocsservers_id` = 1
  Error: Unknown column 'plugin_ocsinventoryng_ocsservers_id' in 'where clause'
  Backtrace :
  plugins/ocsinventoryng/inc/server.class.php:48
  ...s/ocsinventoryng/scripts/ocsng_fullsync.php:242 PluginOcsinventoryngServer->getFromDBbyOcsServer()
  ...s/ocsinventoryng/scripts/ocsng_fullsync.php:100 FirstPass()
 DBmysql::query() in /var/www/glpi/inc/dbmysql.class.php line 180
  *** MySQL query error:
  SQL: INSERT INTO `glpi_plugin_ocsinventoryng_servers` (`max_ocsid`, `max_glpidate`) VALUES ('268', '2018-09-05 07:53:02')
  Error: Duplicate entry '0' for key 'ocsservers_id'
  Backtrace :
  inc/dbmysql.class.php:917
  inc/commondbtm.class.php:537                       DBmysql->insert()
  inc/commondbtm.class.php:974                       CommonDBTM->addToDB()
  ...s/ocsinventoryng/scripts/ocsng_fullsync.php:246 CommonDBTM->add()
  ...s/ocsinventoryng/scripts/ocsng_fullsync.php:100 FirstPass()

```

Below is my glpi_plugin_ocsinventoryng_servers table

![image](https://user-images.githubusercontent.com/42762025/45093217-1824b800-b15b-11e8-92a9-f5f04dcd103e.png)

There is no column '**plugin_ocsinventoryng_ocsservers_id**' which SQL query is looking for.
How can we fix this?
Thanks.

**Comment by ncanqn** [comment]
Thank you so much amma35.
After fixing column name in table **glpi_plugin_ocsinventoryng_servers**  I got similar error in table **glpi_plugin_ocsinventoryng_notimportedcomputers**. 
I renamed the column and automation script is now working without any error.
I guess I got column name issue due upgrade from old version 1.0.3 to 1.5.2. There was no error during upgrade though. 

I'm not sure if below is a separate issue for me. Manuall sync and automatic sync is now working but I cannot see anything under **Scripts execution of automatic actions**, **Computers imported by automatic actions** , **Computers not imported by automatic actions**
Is that something related to database upgrade issue as well?

![image](https://user-images.githubusercontent.com/42762025/45125948-484c7500-b1b4-11e8-82bd-9a5fc3701314.png)

**Comment by amma35** [comment]
Yes you must have the data that was imported with the sync.

You should check all the SQL tables related to OCS to make sure that everything is fine so that you don't have the problems as they happen and bring me the problems you saw.
We should compare with this file: https://github.com/pluginsGLPI/ocsinventoryng/blob/master/install/mysql/1.5.2-empty.sql

Thank you for your feedback.

**Comment by ncanqn** [comment]
Thanks for your reply Amandine.
I just exported all my current glpi_plugin_ocsinventoryng_* table and found a few differences compared to your reference [https://github.com/pluginsGLPI/ocsinventoryng/blob/master/install/mysql/1.5.2-empty.sql](https://github.com/pluginsGLPI/ocsinventoryng/blob/master/install/mysql/1.5.2-empty.sql) .
For example:
Column name is different
![image](https://user-images.githubusercontent.com/42762025/45394464-01f38c00-b674-11e8-88e7-bf649e8da0aa.png)

Default value are different
![image](https://user-images.githubusercontent.com/42762025/45394518-644c8c80-b674-11e8-8815-56f5295de34e.png)

So I guess I need to rerun your fresh sql query. My question is, if I run above 1.5.2-empty.sql, I will need to reconfigure all value for OCS Inventory Ng Plugin and link all computer again is that correct?
Is there any other damages?
Thanks again for your fantastic helps.

**Comment by amma35** [comment]
The "default value" has no impact. 

If there is just this field that differs, you can change to SQL query.
```
ALTER TABLE `glpi_plugin_ocsinventoryng_details` CHANGE `plugin_massocsimport_threads_id` `plugin_ocsinventoryng_threads_id` INT(11) NOT NULL DEFAULT '0';
```

**Comment by ncanqn** [comment]
Thanks Amandine,
I found I don't even have table **glpi_plugin_ocsinventoryng_threads**. And some extra column on other tables.
It should be safe to run your fresh sql query I guess?
Coud you please advise.
Regards,
Ken

**Comment by amma35** [comment]
I just did the test to update 1.0.3 with the latest version.
The migration went well.

The test should be run again starting from this version 1.0.3.

If this still doesn't work, there are some data that were already not good in this version. 
For version 1.0.3, was it a first installation or an update? 

Otherwise you have to start from a fresh installation but you will lose all OCS links between the computers.

**Comment by amma35** [comment]
Yes, that's right.

However, you will lose the locks you have put in place.
That is, manually modified values will be overwritten by OCS.
