### ISSUE TITLE
Lien erroné OCS NG sur GLPI

### ISSUE THREAD

**Issue by RollandMatiere** [pluginsGLPI/ocsinventoryng#178]
Bonjour, 

Je rencontre un soucis sur glpi. E effet lorsque jue clique sur le bonton interface OCSNG, le lien est incorrect donc j'ai une page Not found. Je ne sais pas dans quel fichier changer ce lien.
Pouvez vous m'aider? 
Je vous remercie
Version GLPI : 9.3.0
Version plugin OCS NG : 1.53

**Comment by amma35** [comment]
In the configuration of your server, you have an "Import options" tab, you must enter the value "Web address of the OCSNG console" : 
![ocs](https://user-images.githubusercontent.com/15138371/45358398-994fd500-b5c9-11e8-964e-432ec36dfa9a.png)

**Comment by amma35** [comment]
Il faut bien au début 'http://' sinon cela ne fonctionnera pas

**Comment by RollandMatiere** [comment]
Merci beaucoup.
