### ISSUE TITLE
Mass import in expert mode : error message "cannot get server information"

### ISSUE THREAD

**Issue by ericferon** [pluginsGLPI/ocsinventoryng#181]
I'm using ocsinventoryng 1.4.3 with GLPI 9.2.1.
This installation has started in version 0.80 and it has been upgraded some months ago.
I was running ocs import in standard mode, till now.
And I changed to "Expert mode" because the import stops regularly when there are a lot of computers to import from OCS (9000+)
When I run the "run.php" script, I get the error message "cannot get server information".
I noticed that this message is the consequence of a bad SQL request in inc/server.class.php, line 48 :
the "where clause" should be "`ocsservers_id` = '$id'" instead of the current one.
More, I had to change manually, in the DB table glpi_plugin_ocsinventoryng_servers, the value of the field "ocsservers_id" from "0" to the id of my ocs server to make the script running.
Best regards,
Eric

**Comment by ericferon** [comment]
I had 2 lines in the table glpi_plugin_ocsinventoryng_servers.
As explained in the last paragraph of my 1st comment, the ocsservers_id was '0'.
I had to change it to the id of my ocsserver (that is 3).
Best regards,

**Comment by amma35** [comment]
What is the name of the columns?

**Comment by ericferon** [comment]
![image](https://user-images.githubusercontent.com/8736398/46067924-3f7a0e00-c178-11e8-813b-024552cfdefc.png)
The ocsserver_id of the last line was 0 ; I had to change it to the value 3.
Best regards

**Comment by amma35** [comment]
Same problem : https://github.com/pluginsGLPI/ocsinventoryng/issues/175#issuecomment-418727840
The update didn't go well, you don't have the right column names.
