### ISSUE TITLE
No thread count in GLPI for computers imported from OCS Inventory

### ISSUE THREAD

**Issue by dytrip77** [pluginsGLPI/ocsinventoryng#186]
- Plugin version =  1.5.4
- GLPI version = 9.3.0
- Step to reproduce - Open processor type in computer. 

![screenshot from 2018-11-02 11-26-15](https://user-images.githubusercontent.com/22068278/47892445-a8992380-de92-11e8-9856-0d34e1d6171b.png)

Hi,
Why is the thread box is empty? May I know from where does it read the data specifically? I checked ocs table and noticed that Logical CPU data is exist.

**Comment by dytrip77** [comment]
Appreciate if someone can clarify where does the thread box read the data from.

**Comment by dytrip77** [comment]
Hi,
I've tried this fix and it doesn't work.

**Comment by amma35** [comment]
Hi,
The processors are not updated, it is necessary to perform the test with the creation of a processor.

**Comment by dytrip77** [comment]
Hi @amma35,

Once new code is deployed in the script, I rerun the again again. Please review the result.

![screenshot from 2018-12-04 15-45-11](https://user-images.githubusercontent.com/22068278/49426553-dcda6980-f7db-11e8-9356-1f3547799662.png)
LOGICAL_CPUS is present in OCS server

![screenshot from 2018-12-04 15-45-38](https://user-images.githubusercontent.com/22068278/49426591-fa0f3800-f7db-11e8-8938-5c1ef562e8c0.png)
Thread not reporting in GLPI

**Comment by amma35** [comment]
Your processor was created on July 20th in GLPI. It is necessary to test the creation of a new processor not present in GLPI.

**Comment by dytrip77** [comment]
Thanks @amma35 

What I did was I deleted computer from glpi and resync using ocsng. This is fine for test server.

Do you have better idea to execute this for real production server with more than 50 thousand devices?
