### ISSUE TITLE
Drop tables safely 

### ISSUE THREAD

**Issue by marciofoz** [pluginsGLPI/ocsinventoryng#189]
Hi!

I have a lot of tables named ocs_glpi_*. 

I believe these tables are from a very old version of the plugin that was installed.  Now I am using GLPI version 0.93 and plugin 1.5.4 and the correct/actual tables are named glpi_plugin_ocsinventory_*

Can I drop these tables safely?

ocs_glpi_rules
ocs_glpi_rulecriterias
ocs_glpi_ruleactions
ocs_glpi_registrykeys
ocs_glpi_profiles
ocs_glpi_ocsservers
ocs_glpi_ocslinks
ocs_glpi_ocsadmininfoslinks
ocs_glpi_displaypreferences
ocs_glpi_crontasks

Thank you.

**Comment by tsmr** [comment]
Yes you can (dixit Mister Obama)
