### ISSUE TITLE
No Inventory Number imported

### ISSUE THREAD

**Issue by general2000vn** [pluginsGLPI/ocsinventoryng#191]
Dear Plugin Team

- The version of the plugin: 1.5.4 -> 1.5.6 (both has this issue)
- The version of your GLPI: 9.3.1
- The version of OCS NG: 2.5

I installed upgrade GLPI from previous version, and I also had to upgrade GLPI - ocsng plugin too.
But since recent version (1.5.4 and 1.5.6), the Computer Inventory Number is not imported, and not updated.

The configuration of GLPI is not changed comparing with previous version.

I set Data to Import:
- OCSNG administrative information : Inventory Number = TAG

This is same as before (works for many years for me), but it does not work now.

Tested Import New Computer, Sync Computer already Imported, launch Synchronization and Force full import.
But all does not take Inventory Number. Even OCS NG TAG has value, but not inserted into Inventory Number.

Not sure If I have to set any other options for that.

Thank you very much for your help
Anh Tran

**Comment by tsmr** [comment]
OK for Last version
