### ISSUE TITLE
Monitors is imported incorrectly

### ISSUE THREAD

**Issue by general2000vn** [pluginsGLPI/ocsinventoryng#192]
Dear developer team.

I am using these combination below:
- The version of the plugin: 1.5.6
- The version of GLPI: 9.3.1
- The version of OCS NG: 2.5

I have fully synchronise all computers, and see that Monitor are imported incorrectly. That means monitor connected to one computer is reported in GLPI as connected to another computer.

I have checked in OCS NG and see that some how synchronisation mess up all monitors, even after deleting all computers and components, monitors in GLPI and re-imported all computers.

Please check and fix this, thank you so much, developer team.

Anh Tran
General2000vn

**Comment by keha35** [comment]
Hi,

I'm closing for now without answer, feel free to reopen if you have more informations.

**Comment by general2000vn** [comment]
sorry i for being silent for a while.

The import option i use is: Unit import on Serial number

**Comment by keha35** [comment]
Hi,

Have you something in your OCS logs or in php-errors.log ?

**Comment by tsmr** [comment]
https://github.com/pluginsGLPI/ocsinventoryng/commit/92119899d11263f5d95b6ff15feea595d8717515
https://github.com/pluginsGLPI/ocsinventoryng/commit/fa93834854b2060234384c3123b8fd732901d778
