### ISSUE TITLE
OS Version not updated with sync only with import

### ISSUE THREAD

**Issue by gitdevmod** [pluginsGLPI/ocsinventoryng#193]
Hi,

- The version of the plugin is 1.5.6
- The version of your GLPI is 9.3.3

- The steps to reproduce your issue.

OS Version Windows 10 10.0.17763 is correctly imported in OCS Inventory but in GLPI it's still 10.0.17134 even with manual synchronisation. It's works with force full import.
OS Version is not locked in GLPI

There is no error in sql-errors.log or php-errors.log

Thanks in advance

**Comment by gitdevmod** [comment]
With debug enabled I've this error when synching

[2019-01-09 16:09:17] glpisqllog.ERROR: DBmysql::query() in /usr/share/glpi/inc/dbmysql.class.php line 177
  *** MySQL query error:
  SQL: INSERT INTO `glpi_items_operatingsystems` (`items_id`, `itemtype`, `operatingsystems_id`, `operatingsystemversions_id`, `operatingsystemservicepacks_id`, `operatingsystemarchitectures_id`, `license_number`, `license_id`, `is_dynamic`, `entities_id`, `is_recursive`, `date_creation`, `date_mod`) VALUES ('806', 'Computer', '3', '2', '3', '1', 'MAK or VLK key unavailable', 'XXXXXX', '1', '0', '0', '2019-01-09 16:09:17', '2019-01-09 16:09:17')
  Error: Duplicate entry '806-Computer-3-1' for key 'unicity'
  Backtrace :
  inc/dbmysql.class.php:921
  inc/commondbtm.class.php:649                       DBmysql->insert()
  inc/commondbtm.class.php:1128                      CommonDBTM->addToDB()
  plugins/ocsinventoryng/inc/os.class.php:269        CommonDBTM->add()
  ...ns/ocsinventoryng/inc/ocsprocess.class.php:1256 PluginOcsinventoryngOS::updateComputerOS()
  plugins/ocsinventoryng/front/ocsng.sync.php:52     PluginOcsinventoryngOcsProcess::synchronizeComputer()

Why it's trying to INSERT instead of UPDATE ?

**Comment by gitdevmod** [comment]
I think it's this request : https://github.com/pluginsGLPI/ocsinventoryng/blob/1c63d7351d47b19c6463ea613b5120bafd86d04a/inc/os.class.php#L227-L231

**Comment by gitdevmod** [comment]
It's a different issue from topic. This error comes from a Windows 7 computer not Windows 10

**Comment by gitdevmod** [comment]
Ok, I think I found issue, $id is true or false not the id of select request. Could you confirm ?

**Comment by gitdevmod** [comment]
With the PR it's works when updating from glpi/plugins/ocsinventoryng/front/ocsng.sync.php page but not with the synchronisation button in computer page.

**Comment by keha35** [comment]
Hi,

And when did the error occured,
Did you update your glpi version recently?

**Comment by gitdevmod** [comment]
hi @keha35,

I do not remember because I did not pay attention until the new Windows 10 1809 version.
I upgraded to glpi 9.3.3 from 9.3.2

**Comment by keha35** [comment]
Can you try to make this update in your DB : 
`UPDATE `glpi_items_operatingsystems` SET `is_dynamic` = '1'; `

**Comment by gitdevmod** [comment]
@keha35 
I retested this morning, it works in both page now ocsng.sync.php and computer.form.php

> 
> 
> Can you try to make this update in your DB :
> `UPDATE `glpi_items_operatingsystems` SET `is_dynamic` = '1'; `

This is for "Error: Duplicate entry '806-Computer-3-1' for key 'unicity" error ?

**Comment by keha35** [comment]
Yes it's for the Duplicate error

**Comment by gitdevmod** [comment]
@keha35 so far no more error

**Comment by keha35** [comment]
Ok, thanks for the reply.

I'm closing the issue, feel free to reopen if the problem occure again.

**Comment by gitdevmod** [comment]
@keha35 do not forgot #196 :-)
