### ISSUE TITLE
plugin connect to remote ocs db when i open any pc in glpi

### ISSUE THREAD

**Issue by vanya2143** [pluginsGLPI/ocsinventoryng#195]
Hi!
In plugin i see some problrem.
After import pc from remote ocs server, glpi continues connect to remote ocs server when I try see this PC

Help me please 

glpi version 9.3.3

**Comment by keha35** [comment]
Hi, 

I don't understand your probleme can you explain what is wrong for you?
If possible can you add some screenshots to describe it.

**Comment by vanya2143** [comment]
Sorry. Not relevant, thanks
