### ISSUE TITLE
Computers are duplicated when changing names

### ISSUE THREAD

**Issue by andreluizpd** [pluginsGLPI/ocsinventoryng#197]
Hello I'm having a problem when importing a computer that it's name was changed.
On OCS the computer is changed with no problems, but on GLPI the computer is duplicated.
I'm running the ocsng_fullsync.sh withing the crontab.

How can the computer name on GLPI change to the new one without creating a new entry ?
 

GLPI 9.3.2
ocsinventoryng plugin - 1.5.4

**Comment by keha35** [comment]
Hi, 

You need to create a "Rules for import and link computers"
Which check if the serial number is already present in GLPI.
![image](https://user-images.githubusercontent.com/39367117/50983852-ad1c3100-1500-11e9-975f-a1f804be2b62.png)
And the action need to create the link with the existing computer in glpi
![image](https://user-images.githubusercontent.com/39367117/50983868-b9a08980-1500-11e9-98b8-e82231f56212.png)

**Comment by andreluizpd** [comment]
> Hi,
> 
> You need to create a "Rules for import and link computers"
> Which check if the serial number is already present in GLPI.
> ![image](https://user-images.githubusercontent.com/39367117/50983852-ad1c3100-1500-11e9-975f-a1f804be2b62.png)
> And the action need to create the link with the existing computer in glpi
> ![image](https://user-images.githubusercontent.com/39367117/50983868-b9a08980-1500-11e9-98b8-e82231f56212.png)

That Worked, thank you @keha35
