### ISSUE TITLE
RAM is not accurate between OCS and GLPI

### ISSUE THREAD

**Issue by fabien4455** [pluginsGLPI/ocsinventoryng#198]
Hello,

- The version of the plugin : 1.5.6

- The version of GLPI : 9.3.1 & 9.3.2 & 9.3.3 ( I tried 3 versions ) 

- The steps to reproduce my issue : 

1- Have a OCS 2.5 server with GLPI 9.3.X. 
2- Install 1.5.6 plugin
3- Import a computer in GLPI from OCS. The RAM will not be accurate. 

My real exemple with screenshots. 

I have a computer imported on OCS with 2.4.2 UNIX AGENT,
here is RAM info from OCS : 

![image](https://user-images.githubusercontent.com/22091839/51972521-d8e56380-247b-11e9-8159-5b4a7e414083.png)

See, i have 2 * 8 Go RAM sticks in the computer so 16 Go of RAM. 

![image](https://user-images.githubusercontent.com/22091839/51972601-0df1b600-247c-11e9-83ec-b79c2ecf6585.png)

If I go to GLPI and import my computer.. I have problems with RAM import. 

![image](https://user-images.githubusercontent.com/22091839/51972650-38437380-247c-11e9-84a7-91a7be608fda.png)

GLPI only report : one stick of RAM : 8 Go.

![image](https://user-images.githubusercontent.com/22091839/51972834-a0925500-247c-11e9-9668-a2ec25e0801f.png)

Also I have a computer that got 32 Go of RAM ( 4 * 8 Go sticks ) correctly showed in OCS, but in GLPI only 1 of them ( 1 * 8 Go ) is showed.. 

I've tried to downgrade to Glpi 9.2.2 and OCS plugin 1.4.4 with the same OCS server ( 2.5 ) and it's working perfectly fine... 

The issue is, I think, from your plugin that's not fully working with GLPI 9.3.X

Thank's.

**Comment by fabien4455** [comment]
UP UP UP 👍

**Comment by fabien4455** [comment]
Hey this is still an issue on GLPI 9.4 and OCS 2.5 and plugin 1.6.0.... Can you respond to this ticket or not ? This bug is big. Also CPU is not correctly returned...

**Comment by EC2311** [comment]
Hello
same problem here : https://forum.glpi-project.org/viewtopic.php?id=167131 for me.

**Comment by ageri** [comment]
UP

**Comment by fabien4455** [comment]
They just don't care about us... It's a big bug but no one care ..... They will release 1.6 1.7 1.8 plugin without fixing it...

**Comment by fabien4455** [comment]
Bonjour, si vous voulez je peux l'écrire en Français pour que vous puissiez répondre au ticket ?

**Comment by EC2311** [comment]
A priori 
Il y a plusieurs sujets sur des dysfonctionnements du plugin OCS : 
https://forum.glpi-project.org/viewtopic.php?id=165913
https://forum.glpi-project.org/viewtopic.php?id=167131

Quand pouvons nous espérer une solution sur ces soucis qui empechent l'upgrade de GLPI (car plugin OCS possède toujours le bug dans les versions ulterieures à 1.5 :( 

D'avance merci

**Comment by fabien4455** [comment]
Je précise que j'ai essayé GLPI 9.4 et votre plugin en 1.6.. toujours le même problème, vous répondez à des tickets plus récents que le miens, pourquoi ? je pense pourtant que le problème est important ! qu'avez vous changé entre la version 1.5 et 1.5.1 ?? 

Svp répondez

**Comment by keha35** [comment]
Hi,

Can you try with this [FIX](https://github.com/pluginsGLPI/ocsinventoryng/pull/212/commits/3f71af04134640d8b7f8b4a357013ca59ade814c) ?

**Comment by EC2311** [comment]
Hello 

I upload 1.5.6 version (the last for 9.3x) i think.
But trying to watch computer I don't have the view of last synchronisation of OCS part : switching back to 1.5.0 it's seen.
So already at this part something is wrong. I don't know if somebody else may confirm that ?

**Comment by vgelot** [comment]
Hello,
I applied the same patch for the RAM that @keha35 proposed
Seems to work for a full import (and massive import I think), but in my case, I configured OCS in standard method, so sometimes, I get twice the RAM I should.
For instance, my computer has 8GB of RAM
Before the patch, I got 4GB of RAM
After the patch, with a force full import, I got 8GB, but after a cron (/opt/glpi/front/cron.php), I get 16GB of RAM

**Comment by vgelot** [comment]
In my case, I also have a problem with the full import, he gets stuck sometimes on a computer
After 1 minute on a computer, the process stops

**Comment by linuxmangr** [comment]
> Hi,
> 
> Can you try with this [FIX](https://github.com/pluginsGLPI/ocsinventoryng/pull/212/commits/3f71af04134640d8b7f8b4a357013ca59ade814c) ?

Hello!
I try this fix and is working.
Bad now need run full import for one by one to update RAM

**Comment by linuxmangr** [comment]
And some question why where found ram I see Gio and note GB ?
How I change it ?

**Comment by linuxmangr** [comment]
I found it in GLPI locale .po file.
Open with Poedit and change and save it and put the .po and .mo  file on server.
