### ISSUE TITLE
Problème de Synchronisation/Import des ordinateurs

### ISSUE THREAD

**Issue by rollandpf** [pluginsGLPI/ocsinventoryng#202]
Dear GLPi user.

For bug reports, you can open an issue here, provide us : 
- The version of the plugin : 1.6.0
- The version of your GLPI : 9.4.0

Bonjour,

depuis que j'ai fait la mise à jour de mon GLPI de la version 9.3.1 à la version 9.4.0 et du plugin de la version 1.5 à la version 1.6, je rencontre des soucis au niveau de l'import des nouveaux PC et de la synchronisation des anciens.

Mon serveur est configuré en mode expert au niveau de la méthode de synchronisation. J'ai une crontable, exécutée toutes les 5mn, qui exécute le script : glpi/plugins/ocsinventoryng/scripts/run.php

Actuellement, quand je vais voir le résultat de l'exécution de l'"Exécution des scripts de la synchronisation automatique" j'obtiens le résultat suivant : 
![synchro](https://user-images.githubusercontent.com/48216797/53746315-361c6c80-3ea1-11e9-9b4d-25620ef9c859.png)

![synchro2](https://user-images.githubusercontent.com/48216797/53747315-47ff0f00-3ea3-11e9-9ac9-778f3324e2f1.png)

On constate que le statut reste sur "En cours d'exécution", que l'on n'a plus la "Durée d'exécution du processus" et parfois même la "Date de fin d'exécution" est vide.

Toutes mes machines ne sont pas synchronisées. Avant la mise à jours de GLPI, en fin de journée, il y avait environ 4 ou 5 machines en attente de synchronisation dans la liste des "Ordinateurs mis à jour dans OCSNG", maintenant je monte à plus de 50. Les 2 derniers PC que j'ai ajouté à mon parc et enregistré dans OCSNG étaient bien présent dans la liste "Importation de nouveaux ordinateurs" mais n'ont pas été importé automatiquement par le script comme avant.

Pouvez-vous m'éclairer, il y a peut être une option qu'il faut que je modifie dans la configuration du plugin ou de mon GLPI. Ci-dessous une copie d'une partie de mes logs d'exécution du plugin

Sun, 03 Mar 2019 20:05:01 +0100 /var/www/glpi/plugins/ocsinventoryng/scripts/run.php started
	Manage delete items in OCS server #1: "Localhost"
22252 Started
22253 Started
=====================================================
	Thread #2: starting (2/2)
Toolbox::userErrorHandlerNormal() in /var/www/glpi/inc/toolbox.class.php line 659
  *** PHP Notice(8): Use of undefined constant PLUGIN_OCSINVENTORYNG_STATE_STARTED - assumed 'PLUGIN_OCSINVENTORYNG_STATE_STARTED'
  Backtrace :
  ...s/ocsinventoryng/scripts/ocsng_fullsync.php:147
 	Thread #2: import computers from server: 'Localhost'
	Thread #2: 5 computer(s)
.Toolbox::userErrorHandlerNormal() in /var/www/glpi/inc/toolbox.class.php line 659
  *** PHP Notice(8): Undefined index: import_teamviewer
  Backtrace :
  ...ns/ocsinventoryng/inc/ocsprocess.class.php:1089
  ...ins/ocsinventoryng/inc/ocsprocess.class.php:471 PluginOcsinventoryngOcsProcess::synchronizeComputer()
  ...s/ocsinventoryng/scripts/ocsng_fullsync.php:415 PluginOcsinventoryngOcsProcess::processComputer()
  ...s/ocsinventoryng/scripts/ocsng_fullsync.php:292 plugin_ocsinventoryng_importFromOcsServer()
  ...s/ocsinventoryng/scripts/ocsng_fullsync.php:164 SecondPass()

22253 ended, waiting for 1 running thread
=====================================================
	Thread #1: starting (1/2)
Toolbox::userErrorHandlerNormal() in /var/www/glpi/inc/toolbox.class.php line 659
  *** PHP Notice(8): Use of undefined constant PLUGIN_OCSINVENTORYNG_STATE_STARTED - assumed 'PLUGIN_OCSINVENTORYNG_STATE_STARTED'
  Backtrace :
  ...s/ocsinventoryng/scripts/ocsng_fullsync.php:147
 	Thread #1: import computers from server: 'Localhost'
	Thread #1: 6 computer(s)
.Toolbox::userErrorHandlerNormal() in /var/www/glpi/inc/toolbox.class.php line 659
  *** PHP Notice(8): Undefined index: import_teamviewer
  Backtrace :
  ...ns/ocsinventoryng/inc/ocsprocess.class.php:1089
  ...ins/ocsinventoryng/inc/ocsprocess.class.php:471 PluginOcsinventoryngOcsProcess::synchronizeComputer()
  ...s/ocsinventoryng/scripts/ocsng_fullsync.php:415 PluginOcsinventoryngOcsProcess::processComputer()
  ...s/ocsinventoryng/scripts/ocsng_fullsync.php:292 plugin_ocsinventoryng_importFromOcsServer()
  ...s/ocsinventoryng/scripts/ocsng_fullsync.php:164 SecondPass()
 .Toolbox::userErrorHandlerNormal() in /var/www/glpi/inc/toolbox.class.php line 659
  *** PHP Notice(8): Undefined index: import_teamviewer
  Backtrace :
  ...ns/ocsinventoryng/inc/ocsprocess.class.php:1089
  ...ins/ocsinventoryng/inc/ocsprocess.class.php:471 PluginOcsinventoryngOcsProcess::synchronizeComputer()
  ...s/ocsinventoryng/scripts/ocsng_fullsync.php:415 PluginOcsinventoryngOcsProcess::processComputer()
  ...s/ocsinventoryng/scripts/ocsng_fullsync.php:292 plugin_ocsinventoryng_importFromOcsServer()
  ...s/ocsinventoryng/scripts/ocsng_fullsync.php:164 SecondPass()
 Toolbox::userErrorHandlerNormal() in /var/www/glpi/inc/toolbox.class.php line 659
  *** PHP Notice(8): Use of undefined constant PLUGIN_OCSINVENTORYNG_STATE_RUNNING - assumed 'PLUGIN_OCSINVENTORYNG_STATE_RUNNING'
  Backtrace :
  ...s/ocsinventoryng/scripts/ocsng_fullsync.php:402
  ...s/ocsinventoryng/scripts/ocsng_fullsync.php:292 plugin_ocsinventoryng_importFromOcsServer()
  ...s/ocsinventoryng/scripts/ocsng_fullsync.php:164 SecondPass()
 .Toolbox::userErrorHandlerNormal() in /var/www/glpi/inc/toolbox.class.php line 659
  *** PHP Notice(8): Undefined index: import_teamviewer
  Backtrace :
  ...ns/ocsinventoryng/inc/ocsprocess.class.php:1089
  ...ins/ocsinventoryng/inc/ocsprocess.class.php:471 PluginOcsinventoryngOcsProcess::synchronizeComputer()
  ...s/ocsinventoryng/scripts/ocsng_fullsync.php:415 PluginOcsinventoryngOcsProcess::processComputer()
  ...s/ocsinventoryng/scripts/ocsng_fullsync.php:292 plugin_ocsinventoryng_importFromOcsServer()
  ...s/ocsinventoryng/scripts/ocsng_fullsync.php:164 SecondPass()

22252 ended, waiting for 0 running thread
Sun, 03 Mar 2019 20:05:03 +0100 /var/www/glpi/plugins/ocsinventoryng/scripts/run.php ended

Sun, 03 Mar 2019 20:10:01 +0100 /var/www/glpi/plugins/ocsinventoryng/scripts/run.php started
	Manage delete items in OCS server #1: "Localhost"

Cordialement.

**Comment by rollandpf** [comment]
En complément, 

depuis peu la commande "php /var/www/glpi/plugins/ocsinventoryng/scripts/run.php --thread_nbr=2 --server_id=1" me renvoie des erreurs. Par exemple :
Stack trace:
#0 /var/www/glpi/plugins/ocsinventoryng/inc/networkport.class.php(429): PluginOcsinventoryngNetworkPort::updateNetworkPort('6C:71:D9:01:AD:...', 'Realtek RTL8188...', '876', 'PluginOcsinvent...', Array, Array, false, Array, Array, '0.0.0.0', '0.0.0.0', '0.0.0.0', '8')
#1 /var/www/glpi/plugins/ocsinventoryng/inc/device.class.php(475): PluginOcsinventoryngNetworkPort::importNetwork(Array, Array, '876', '8')
#2 /var/www/glpi/plugins/ocsinventoryng/inc/ocsprocess.class.php(1234): PluginOcsinventoryngDevice::updateDevices('Item_DeviceNetw...', Array, Array)
#3 /var/www/glpi/plugins/ocsinventoryng/inc/ocsprocess.class.php(471): PluginOcsinventoryngOcsProcess::synchronizeComputer(Array)
#4 /var/www/glpi/plugins/ocsinventoryng/scripts/ocsng_fullsync.php(415): PluginOcsinventoryngOcsProcess::processComputer(Array)
#5 /var/www/glpi/plugins/ocsinventoryng/scripts/ocsng_fullsync. in /var/www/glpi/plugins/ocsinventoryng/inc/networkport.class.php on line 145
PHP Fatal error:  Uncaught Error: Call to a member function getID() on boolean in /var/www/glpi/plugins/ocsinventoryng/inc/networkport.class.php:145
Stack trace:
#0 /var/www/glpi/plugins/ocsinventoryng/inc/networkport.class.php(429): PluginOcsinventoryngNetworkPort::updateNetworkPort('7C:5C:F8:78:62:...', 'Intel(R) Wirele...', '698', 'PluginOcsinvent...', Array, Array, false, Array, Array, '0.0.0.0', '0.0.0.0', '0.0.0.0', '18')
#1 /var/www/glpi/plugins/ocsinventoryng/inc/device.class.php(475): PluginOcsinventoryngNetworkPort::importNetwork(Array, Array, '698', '18')
#2 /var/www/glpi/plugins/ocsinventoryng/inc/ocsprocess.class.php(1234): PluginOcsinventoryngDevice::updateDevices('Item_DeviceNetw...', Array, Array)
#3 /var/www/glpi/plugins/ocsinventoryng/inc/ocsprocess.class.php(471): PluginOcsinventoryngOcsProcess::synchronizeComputer(Array)
#4 /var/www/glpi/plugins/ocsinventoryng/scripts/ocsng_fullsync.php(415): PluginOcsinventoryngOcsProcess::processComputer(Array)
#5 /var/www/glpi/plugins/ocsinventoryng/scripts/ocsng_fullsyn in /var/www/glpi/plugins/ocsinventoryng/inc/networkport.class.php on line 145

**Comment by rollandpf** [comment]
J'ai réglé une partie de mes problèmes en ajoutant les lignes suivantes au début du ficher ocsng_fullsync.php

define("PLUGIN_OCSINVENTORYNG_STATE_STARTED", 1);
define("PLUGIN_OCSINVENTORYNG_STATE_RUNNING", 2);
define("PLUGIN_OCSINVENTORYNG_STATE_FINISHED", 3);

A nouveau les statuts, date de début, date de fin d’exécution et durée du script sont calculés normalement.
![Sans titre](https://user-images.githubusercontent.com/48216797/54293819-efb9c280-45b0-11e9-946a-9d335a27b182.jpg)

Je vais me pencher sur le second problème qui renvoie l'erreur suivante à l'exécution du script : PHP Fatal error: Uncaught Error: Call to a member function getID() on boolean in /var/www/glpi/plugins/ocsinventoryng/inc/networkport.class.php:145

Erreur qui disparaît après un import manuellement depuis l'interface à l'adresse http://.../glpi/plugins/ocsinventoryng/front/ocsng.sync.php

**Comment by bidis31** [comment]
Bonjour,
je rencontre les mêmes pb avez-vous une piste de résolution ?
merci

**Comment by rollandpf** [comment]
J'ai modifié le fichier glpi/plugins/ocsinventoryng/inc/networkport.class.php en apportant le changement suivant :

Le bloc suivant (ligne 143)
if ($network_port->fields['instantiation_type'] == $instantiation_type) {
   $instantiation = $network_port->getInstantiation();
   $inst_input['id'] = $instantiation->getID();
   $inst_input['networkports_id'] = $network_port->getID();
   $instantiation->update($inst_input, $install_network_history);
   unset($instantiation);
}

est devenu : 

if ($network_port->fields['instantiation_type'] == $instantiation_type) {
   $instantiation = $network_port->getInstantiation();
   if (is_object($instantiation)){
      $inst_input['id'] = $instantiation->getID();
      $inst_input['networkports_id'] = $network_port->getID();
      $instantiation->update($inst_input, $install_network_history);
   }
   unset($instantiation);
}

Les anciens PC se synchronisent bien. On a repris le fonctionnement normal.

Par contre les nouveaux PC ne sont plus importés automatiquement. Il faut pour l'instant le faire à la main. 

J'ai repéré des erreurs SQL dès qu'un nouveau PC est détecté Par exemple :
*** MySQL query error:
  SQL: SELECT DISTINCT `glpi_plugin_ocsinventoryng_details`.`id` AS id, 'pierre.francois.roll' AS currentuser,
                        `glpi_plugin_ocsinventoryng_details`.`ocsid` AS ocsid,
           `glpi_plugin_ocsinventoryng_details`.`ocsid` AS ocsid,
           `glpi_plugin_ocsinventoryng_details`.`plugin_ocsinventoryng_ocsservers_id` AS plugin_ocsinventoryng_ocsservers_id, `glpi_plugin_ocsinventoryng_details`.`plugin_ocsinventoryng_threads_id`,
                  `glpi_plugin_ocsinventoryng_details`.`threadid`, `glpi_entities`.`completename` AS completename,
           `glpi_entities`.`ocsid` AS ocsid,
           `glpi_entities`.`plugin_ocsinventoryng_ocsservers_id` AS plugin_ocsinventoryng_ocsservers_id, `glpi_entities`.`plugin_ocsinventoryng_threads_id`,
                  `glpi_entities`.`threadid`, `glpi_plugin_ocsinventoryng_threads`.`processid` AS processid,
           `glpi_plugin_ocsinventoryng_threads`.`ocsid` AS ocsid,
           `glpi_plugin_ocsinventoryng_threads`.`plugin_ocsinventoryng_ocsservers_id` AS plugin_ocsinventoryng_ocsservers_id, `glpi_plugin_ocsinventoryng_threads`.`plugin_ocsinventoryng_threads_id`,
                  `glpi_plugin_ocsinventoryng_threads`.`threadid`, `glpi_plugin_ocsinventoryng_ocsservers`.`name` AS name,
           `glpi_plugin_ocsinventoryng_ocsservers`.`ocsid` AS ocsid,
           `glpi_plugin_ocsinventoryng_ocsservers`.`plugin_ocsinventoryng_ocsservers_id` AS plugin_ocsinventoryng_ocsservers_id, `glpi_plugin_ocsinventoryng_ocsservers`.`plugin_ocsinventoryng_threads_id`,
                  `glpi_plugin_ocsinventoryng_ocsservers`.`threadid`, `glpi_plugin_ocsinventoryng_details`.`process_time` AS process_time,
           `glpi_plugin_ocsinventoryng_details`.`ocsid` AS ocsid,
           `glpi_plugin_ocsinventoryng_details`.`plugin_ocsinventoryng_ocsservers_id` AS plugin_ocsinventoryng_ocsservers_id, `glpi_plugin_ocsinventoryng_details`.`plugin_ocsinventoryng_threads_id`,
                  `glpi_plugin_ocsinventoryng_details`.`threadid`, `glpi_plugin_ocsinventoryng_details`.`action` AS action,
           `glpi_plugin_ocsinventoryng_details`.`ocsid` AS ocsid,
           `glpi_plugin_ocsinventoryng_details`.`plugin_ocsinventoryng_ocsservers_id` AS plugin_ocsinventoryng_ocsservers_id, `glpi_plugin_ocsinventoryng_details`.`plugin_ocsinventoryng_threads_id`,
                  `glpi_plugin_ocsinventoryng_details`.`threadid`, `glpi_plugin_ocsinventoryng_details`.`computers_id` AS computers_id,
           `glpi_plugin_ocsinventoryng_details`.`ocsid` AS ocsid,
           `glpi_plugin_ocsinventoryng_details`.`plugin_ocsinventoryng_ocsservers_id` AS plugin_ocsinventoryng_ocsservers_id, `glpi_plugin_ocsinventoryng_details`.`plugin_ocsinventoryng_threads_id`,
                  `glpi_plugin_ocsinventoryng_details`.`threadid` FROM `glpi_plugin_ocsinventoryng_details`LEFT JOIN `glpi_entities` 
                                          ON (`glpi_plugin_ocsinventoryng_details`.`entities_id` = `glpi_entities`.`id`
                                              )LEFT JOIN `glpi_plugin_ocsinventoryng_threads` 
                                          ON (`glpi_plugin_ocsinventoryng_details`.`plugin_ocsinventoryng_threads_id` = `glpi_plugin_ocsinventoryng_threads`.`id`
                                              )LEFT JOIN `glpi_plugin_ocsinventoryng_ocsservers` 
                                          ON (`glpi_plugin_ocsinventoryng_details`.`plugin_ocsinventoryng_ocsservers_id` = `glpi_plugin_ocsinventoryng_ocsservers`.`id`
                                              ) WHERE   (  1 )  AND (    (`glpi_plugin_ocsinventoryng_threads`.`processid`  LIKE '531540'  ) ) ORDER BY ITEM_PluginOcsinventoryngDetail_1 ASC 
  Error: Unknown column 'glpi_entities.ocsid' in 'field list'
  Backtrace :
  inc/search.class.php:1181                          
  inc/search.class.php:98                            Search::constructData()
  inc/search.class.php:80                            Search::showList()
  plugins/ocsinventoryng/front/detail.php:36         Search::show()
  {"user":"1022@SRVGLPI"}  

On a effectivement des champs qui n'existent pas :  `glpi_entities`.`ocsid` , TEM_PluginOcsinventoryngDetail_1 par exemple. 

En modifiant la requête en erreur on finit par obtenir une liste. Je n'ai pas encore trouvé dans le code comment corriger la génération des requêtes en erreur.

**Comment by bidis31** [comment]
Avez vous testez en GLPI 9.4.1.1 ? Cela semble résoudre quelques PB mais pas tout !!

**Comment by rollandpf** [comment]
Merci, je viens de tester la version 9.4.1.1. 

Tout fonctionne bien coté import. Les 2 PC que j'avais en attente depuis ce matin on été importé à la première exécution du script. La synchronisation des PC déjà présent dans la base est pour l'instant plus longue qu'avant. 

Ce matin je synchronisais par exemple 18 PC en 3s. Pour 15 PC il m'a pris 43s après la mise à jour. Pas très grave tant que ça fonctionne. En plus la latence vient peut être de mon Hyperviseur qui est assez surchargé en ce moment.

**Comment by rollandpf** [comment]
J'ai rebasculé en version 9.4, la nouvelle version me perd toutes les informations de gestion, ce qui est plus pénalisant pour mon utilisation de GLPI que d'importer manuellement les nouveaux PC.

**Comment by bidis31** [comment]
Je n'ai pas constaté ce pb chez nous ....la synchro fonctionne bien seule la première avec reimport de l'ensemble des postes dans OCS a été tres longue .

**Comment by rollandpf** [comment]
Sur mon PC de test tout fonctionne bien en 9.4.1.1. Et même en version 9.4 avec le plugin téléchargé et installé sans mes modifications. La seule différence avec mon serveur de production, c'est l'absence de l'extension OPcache sur ma machine de test. J'ai désactivé l'extension sur le serveur de production et refait la mise à jour. Tout semble OK maintenant. 

Je pense que c'est le cache qui me posait des problèmes lors de ma première tentative de mise à jour. Je ne l'avait pas vidé après l'installation de la version 9.4.1.1

Vu le peu de gain de performances que j'ai constaté sur GLPI depuis que j'ai activé OPcache, je vais laisser l'extension désactivée.

**Comment by rollandpf** [comment]
Au bout de 30mn, les informations de gestion ont à nouveau disparues. Pourquoi ? Je ne vois rien dans les logs. Je suis repassé en 9.4. Je vais signaler l'incident sur le forum de GLPI.

**Comment by rollandpf** [comment]
Problème réglé après mise à jour à la version 9.4.2.

J'ai juste du retirer les lignes suivantes au début du fichier ocsng_fullsync.php

define("PLUGIN_OCSINVENTORYNG_STATE_STARTED", 1);
define("PLUGIN_OCSINVENTORYNG_STATE_RUNNING", 2);
define("PLUGIN_OCSINVENTORYNG_STATE_FINISHED", 3);

Si elles étaient nécessaires avec la version 9.4, avec la 9.4.2 elles gênèrent un warning (constante déjà définie).
