### ISSUE TITLE
Automatic actions 

### ISSUE THREAD

**Issue by sewkol** [pluginsGLPI/ocsinventoryng#209]
Hello

I have a problem with the automatic synchronization of computers.
In the plugin settings, I have the synchronization method "Standard (allow manual actions)". In the Automatic actions setting, when I change the status to "Scheduled", "Next run" is always "Disabled".

![ocsng](https://user-images.githubusercontent.com/42667940/55471636-8571cc00-560a-11e9-9e1f-ff60eac47239.png)

I can execute "Execute" manually and synchronize nicely, but how to do automatic synchronization of already imported computers? 

OCS Inventory NG plugin: 1.6.0
GLPI: 9.4.1.1
OCS Server: 2.5

**Comment by keha35** [comment]
Hi, 

Is the plugin enabled in "Setup > Plugins"
I can't reproduce this behaviour.

**Comment by sewkol** [comment]
Yes. Plugin is enabled:

![plugins](https://user-images.githubusercontent.com/42667940/56287632-31440d00-611d-11e9-98f4-1cc567b503f9.png)

**Comment by keha35** [comment]
Hi,

It seems to be a probleme of the release of GLPI.
Can you try with the release 9.4.2 ?

**Comment by sewkol** [comment]
Actually it looks like a bug in version 9.4.1.1. I updated GLPI to 9.4.2 and it works. I only changed the run mode to CLI.

By the way in the debug mode I found the following error:
![ocs-bebug](https://user-images.githubusercontent.com/42667940/56342768-35256d00-61b9-11e9-9de3-476eb342d0dc.png)

Thanks for the hint. 

Greetings
Seweryn Kolano

**Comment by keha35** [comment]
Hi,

For this error, you need to update the DB.
you can check : [#201](https://github.com/pluginsGLPI/ocsinventoryng/issues/201#issuecomment-484093158)

This problem will be updated in the next release.

**Comment by sewkol** [comment]
It actually helped :)

Thanks
