### ISSUE TITLE
Automatic Synchronization not working

### ISSUE THREAD

**Issue by bigbroDOTpro** [pluginsGLPI/ocsinventoryng#210]
Dear GLPi user.

For bug reports, you can open an issue here, provide us : 
- plugin. 1.6
- The version of your GLPI. 9.4.
- Automatic Synchronization not working. (disabled plugin)

![ocsg](https://user-images.githubusercontent.com/49197831/55555630-62b8e380-56ee-11e9-9598-44731f7113b4.png)
![ocsng1](https://user-images.githubusercontent.com/49197831/55555639-664c6a80-56ee-11e9-9c63-cc7e1a1a720d.png)
![ocsng2](https://user-images.githubusercontent.com/49197831/55555642-68162e00-56ee-11e9-8e78-550004f8acfa.png)
![ocsng3](https://user-images.githubusercontent.com/49197831/55555644-69475b00-56ee-11e9-9243-2586802d73d2.png)

Synchronization work only manual push.
Inside: Automatic action->Ocsinventoryng - ocsng (OCSNG - Launch OCSNG synchronization script) Status: Disabled plugin

**Comment by keha35** [comment]
Hi,

It seems to be a probleme of the release of GLPI.
Can you try with the release 9.4.2 ?

**Comment by asemerdjian** [comment]
I am having the same exact issue of inventory not importing automatically, and able to manually.
GLPI 9.4.3 with OCS Inventory NG Plugin 1.6.0

**Comment by hgpit** [comment]
Same problem (I think). GLPI 9.4.3. OCS 1.6 plugin.

Can run `sudo -u apache /usr/share/glpi/plugins/ocsinventoryng/scripts/ocsng_fullsync.sh` from the command line **_manually_** and the OCS sync catches up.

Script looks okay:
`[root@svr-h003011 ~]# ls -lha /usr/share/glpi/plugins/ocsinventoryng/scripts/ocsng_fullsync.sh
-rwxr--r-- 1 apache apache 2.6K Feb 25 13:40 /usr/share/glpi/plugins/ocsinventoryng/scripts/ocsng_fullsync.sh`

GLPI claims to be executing frequently:
![image](https://user-images.githubusercontent.com/16598973/61638808-0e804200-ac92-11e9-8adc-1c0e30bdbd06.png)
But if I click 'Execute', it finishes without error, but nothing gets synchronized.

GLPI cron script is in the cron:
`
![image](https://user-images.githubusercontent.com/16598973/61638919-4f785680-ac92-11e9-9f9c-170582d560d4.png)`

**Comment by cristanxu** [comment]
no reply?
