### ISSUE TITLE
OCSinventory NG and GLPI api

### ISSUE THREAD

**Issue by Synedh** [pluginsGLPI/ocsinventoryng#213]
Hello,

In my use of GLPI, I need to access the details of the computers via the REST API. For instance, I need to retrieve the value of the OCSNG TAG.
As I don't find any information about this in the wiki and my research in the API does not succeed, I end up doubting the presence of this key in it.

![image](https://user-images.githubusercontent.com/16208735/58493975-6314ae80-8174-11e9-8c67-eb4a61deaddd.png)

If that key exists somewhere, could you tell me how to get it ?

Thanks.

**Comment by stravassac** [comment]
Hi @Synedh,
You can do it by:
  - search the number of searchOption "OCSNG TAG" by http://127.0.0.1/apirest.php/listSearchOptions/Computer
  - search your computer ID with this filter with 
     - number of the searchOption ID (NUMBER_ID  -> 2 in my case)
     - ID_COMPUTER -> ID of your computer
     - number from previous search (NUMBER_OCSNG_TAG -> 10005 in my case)
http://127.0.0.1/apirest.php/search/Computer?criteria[0][field]=NUMBER_ID&criteria[0][searchtype]=contains&criteria[0][value]=ID_COMPUTER&forcedisplay[0]=NUMBER_OCSNG_TAG
