### ISSUE TITLE
Automatic Synchronization not working (still)

### ISSUE THREAD

**Issue by hgpit** [pluginsGLPI/ocsinventoryng#218]
Same problem (I think) as #210 . GLPI 9.4.3. OCS 1.6 plugin.

Can run `sudo -u apache /usr/share/glpi/plugins/ocsinventoryng/scripts/ocsng_fullsync.sh` from the command line **_manually_** and the OCS sync catches up.

Script looks okay:
**[root@svr-h003011 ~]# ls -lha /usr/share/glpi/plugins/ocsinventoryng/scripts/ocsng_fullsync.sh
-rwxr--r-- 1 apache apache 2.6K Feb 25 13:40 /usr/share/glpi/plugins/ocsinventoryng/scripts/ocsng_fullsync.sh**

GLPI claims to be executing frequently:
![image](https://user-images.githubusercontent.com/16598973/61638808-0e804200-ac92-11e9-8adc-1c0e30bdbd06.png)
But if I click '**Execute**', it finishes without error, but nothing gets synchronized.

GLPI cron script is in the cron:
![image](https://user-images.githubusercontent.com/16598973/61638919-4f785680-ac92-11e9-9f9c-170582d560d4.png)

_Originally posted by @hgpit in https://github.com/pluginsGLPI/ocsinventoryng/issues/210#issuecomment-513806306_

**Comment by hgpit** [comment]
Trying to look into this myself, but not getting very far...

If I run **ocsng_fullsync.sh** with the **--nolog** option, I am seeing some PHP errors:

**Fri Jul 26 16:25:01 BST 2019 /usr/share/glpi/plugins/ocsinventoryng/scripts/ocsng_fullsync.sh started
        Manage delete items in all OCS server
=====================================================
=====================================================
        Manage delete items in OCS server #1: "ocsserver.hayley-group.local"
PHP Fatal error:  Uncaught ErrorException: fopen(/var/lib/glpi/files/_cache/cache_trans/glpi_cache_trans_9.4.381a87b8484bba7310f8109549c74b6c8-74/glpi_cache_trans_9.4.381a87b8484bba7310f8109549c74b6c8-Zend_I18n_
Translator_Messages_bf12c669ca5450dc3ebca380d47b0449.dat): failed to open stream: Permission denied in /usr/share/php/Zend/Cache/Storage/Adapter/Filesystem.php:1572
Stack trace:
#0 [internal function]: Zend\Stdlib\ErrorHandler::addError(2, 'fopen(/var/lib/...', '/usr/share/php/...', 1572, Array)
#1 /usr/share/php/Zend/Cache/Storage/Adapter/Filesystem.php(1572): fopen('/var/lib/glpi/f...', 'cb')
#2 /usr/share/php/Zend/Cache/Storage/Adapter/Filesystem.php(969): Zend\Cache\Storage\Adapter\Filesystem->putFileContent('/var/lib/glpi/f...', 'C:31:"Zend\\I18n...', true, NULL)
#3 /usr/share/php/Zend/Cache/Storage/Adapter/AbstractAdapter.php(688): Zend\Cache\Storage\Adapter\Filesystem->internalSetItem('Zend_I18n_Trans...', 'C:31:"Zend\\I18n...')
#4 /usr/share/php/Zend/Cache/Storage/Adapter/Filesystem.php(843): Zend\Cache\Storage\ in /usr/share/php/Zend/Cache/Storage/Adapter/Filesystem.php on line 1580
=====================================================
        Thread #1: starting (1/2)
        Thread #1: import computers from server: 'ocsserver.hayley-group.local'
        Thread #1: 8 computer(s)
.PHP Fatal error:  Uncaught ErrorException: fopen(/var/lib/glpi/files/_cache/cache_trans/glpi_cache_trans_9.4.381a87b8484bba7310f8109549c74b6c8-74/glpi_cache_trans_9.4.381a87b8484bba7310f8109549c74b6c8-Zend_I18n
_Translator_Messages_bf12c669ca5450dc3ebca380d47b0449.dat): failed to open stream: Permission denied in /usr/share/php/Zend/Cache/Storage/Adapter/Filesystem.php:1572
Stack trace:
#0 [internal function]: Zend\Stdlib\ErrorHandler::addError(2, 'fopen(/var/lib/...', '/usr/share/php/...', 1572, Array)
#1 /usr/share/php/Zend/Cache/Storage/Adapter/Filesystem.php(1572): fopen('/var/lib/glpi/f...', 'cb')
#2 /usr/share/php/Zend/Cache/Storage/Adapter/Filesystem.php(969): Zend\Cache\Storage\Adapter\Filesystem->putFileContent('/var/lib/glpi/f...', 'C:31:"Zend\\I18n...', true, NULL)
#3 /usr/share/php/Zend/Cache/Storage/Adapter/AbstractAdapter.php(688): Zend\Cache\Storage\Adapter\Filesystem->internalSetItem('Zend_I18n_Trans...', 'C:31:"Zend\\I18n...')
#4 /usr/share/php/Zend/Cache/Storage/Adapter/Filesystem.php(843): Zend\Cache\Storage\ in /usr/share/php/Zend/Cache/Storage/Adapter/Filesystem.php on line 1580
=====================================================
        Thread #2: starting (2/2)
        Thread #2: import computers from server: 'ocsserver.hayley-group.local'
        Thread #2: 4 computer(s)
.PHP Fatal error:  Uncaught ErrorException: fopen(/var/lib/glpi/files/_cache/cache_trans/glpi_cache_trans_9.4.381a87b8484bba7310f8109549c74b6c8-74/glpi_cache_trans_9.4.381a87b8484bba7310f8109549c74b6c8-Zend_I18n
_Translator_Messages_bf12c669ca5450dc3ebca380d47b0449.dat): failed to open stream: Permission denied in /usr/share/php/Zend/Cache/Storage/Adapter/Filesystem.php:1572
Stack trace:
#0 [internal function]: Zend\Stdlib\ErrorHandler::addError(2, 'fopen(/var/lib/...', '/usr/share/php/...', 1572, Array)
#1 /usr/share/php/Zend/Cache/Storage/Adapter/Filesystem.php(1572): fopen('/var/lib/glpi/f...', 'cb')
#2 /usr/share/php/Zend/Cache/Storage/Adapter/Filesystem.php(969): Zend\Cache\Storage\Adapter\Filesystem->putFileContent('/var/lib/glpi/f...', 'C:31:"Zend\\I18n...', true, NULL)
#3 /usr/share/php/Zend/Cache/Storage/Adapter/AbstractAdapter.php(688): Zend\Cache\Storage\Adapter\Filesystem->internalSetItem('Zend_I18n_Trans...', 'C:31:"Zend\\I18n...')
#4 /usr/share/php/Zend/Cache/Storage/Adapter/Filesystem.php(843): Zend\Cache\Storage\ in /usr/share/php/Zend/Cache/Storage/Adapter/Filesystem.php on line 1580
cleaning up.
Fri Jul 26 16:25:04 BST 2019**

Should I flush all the privileges under /var/lib/glpi/files/_cache, recursively, to be owned by 'apache' (I'm using CentOS)?

Thanks

**Comment by Eon9D** [comment]
As far as I know its ocsng_fullsync.sh OR the job in GLPI.
I've disabled the job in GLPI - set it to import "None" as in the wiki and added ocsng_fullsync.sh to the system cron every 30min. Works for me

**Comment by keha35** [comment]
Hi,

Like @Eon9D said, you need to configure it in the crontab.

For exemple if you want the sync every 30 min :
`*/30 * * * * apache sh /usr/share/glpi/plugins/ocsinventoryng/scripts/ocsng_fullsync.sh --thread_nbr=2 --server-id=1`
