### ISSUE TITLE
New imported computers from OCS-NG contains all computers

### ISSUE THREAD

**Issue by Eon9D** [pluginsGLPI/ocsinventoryng#220]
- The version of the plugin. 1.6.0
- The version of your GLPI. 9.4.2

- The steps to reproduce your issue:
OCS contains PC1,PC2,PC3.
Activated the notify function for new computers "New imported computers from OCS-NG".
I expect to not get a mail
I added PC4 to OCS
I expect to get a notification that a new computer was imported ("PC4")

--------
Problem: The mail always contains ALL computers - not only the new imported.
What can I do to analyze the problem?

**Comment by tsmr** [comment]
Fixed for 1.6.1
