### ISSUE TITLE
BUG ? Sous GLPI lors de la mise à jour d'un champ ordinateur, cette maj n'est pas appliquée aux éléments connectés

### ISSUE THREAD

**Issue by Muzo18** [pluginsGLPI/ocsinventoryng#224]
- Version ocsinventoryng : 1.6.0
- Version GLPI : 9.4.3

Bonjour,

J'espère ne pas dire une bêtise ou avoir loupé une info...

Dans GLPI, lorsque le plugin ocsinventoryng est activé, si je modifie le champ "utilisateur" ou "usager" d'un ordinateur, cette modification n'est pas appliquée aux éléments associés (moniteur, périphérique...).
Les options de "Mise à jour automatique des éléments connectés aux ordinateurs" sont corrects.
Ce problème n'est pas présent lorsque le plugin est désactivé.

Si je modifie le champ "lieu" ou "groupe technique", pas de soucis constaté.

Est-ce un bug, ou bien alors y a-t-il un paramétrage qui m'a échappé ?

Merci et à bientôt.

**Comment by tsmr** [comment]
Corrigé normalement.
