### ISSUE TITLE
BUG remontée des caractéristiques mémoire et CPU dans GLPI

### ISSUE THREAD

**Issue by ChristopheLacaze** [pluginsGLPI/ocsinventoryng#225]
- Version ocsinventoryng : 1.6.0
- Version GLPI : 9.4.3

Bonjour,

Suite à la montée de version de l'outil GLPI en version 9.4.3 avec la version 1.6.0 du plugin, nous avons constaté que tous les nouveaux équipements intégrés dans GLPI ne disposent que d'un seul processeur (même s'il y en a plusieurs) et que d'une seule barrette mémoire.

Après analyse du code du plugin, j'ai remarqué qu'à partir du moment où il existe un processeur (ou une mémoire) de même modèle pour un ordinateur importé, il n'y a pas ajout des composants supplémentaires) mais mise à jour de celui.

Pour résoudre ce problème, j'ai effectué des modifications dans le fichier ocsinventoryng/inc/device.class.php afin que tous les processeurs et mémoires d'un ordinateur importé soient insérés.
J'ai joint un fichier patch contenant les modifications que j'ai apportées dans le code source.
Si vous pensez que cela résout effectivement le problème, vous pouvez l'intégrer dans la version courante du plugin.

En espérant que cela vous aide.

[ocsinventoryng-device.patch.txt](https://github.com/pluginsGLPI/ocsinventoryng/files/3615809/ocsinventoryng-device.patch.txt)

**Comment by tsmr** [comment]
Merci pour ca. Ne pensez vous pas qu'il faudrait le faire pour tous les devices ?
