### ISSUE TITLE
Synchronize Computers -> OS Version does not change

### ISSUE THREAD

**Issue by hiscorebob** [pluginsGLPI/ocsinventoryng#227]
Plugin Version : 1.6.0
GLPI Version : 9.4.4

Steps to reproduce:

Computer A has Windows 7 installed. Imported into GLPI (from OCS) , Computer has OS Windows 7 in GLPI
Computer A is upgraded to Windows 10, after a synchronization in GLPI Computer still has OS Windows 7 in GLPI (instead of Windows 10). In OCS, Computer is shown with correct OS Windows 10
Tested with several Computers (incl. Windows PC's and Mac's)

For bug reports, you can open an issue here, provide us : 
- The version of the plugin.
- The version of your GLPI.
- The steps to reproduce your issue.

Delete this text to submit your issue.

The Plugin team.

**Comment by miampatate** [comment]
Hi,

I have the same issue on Plugin version 1.6.0 and GLPI version 9.4.3.

Computer migrated Windows 7 to 10 and appears twice in GLPI but not in OCS.
Same problem with CPU, appears twice too in GLPI and not in OCS. 
![image](https://user-images.githubusercontent.com/57104517/67692739-01e94500-f977-11e9-8511-bb65806916cd.png)
![image](https://user-images.githubusercontent.com/57104517/67692817-1b8a8c80-f977-11e9-9be8-712091c6e632.png)

Thanks

**Comment by keha35** [comment]
Hi,

And have you something in the locks in the computer?

Br.

**Comment by hiscorebob** [comment]
In my case, nothing in Locks:
![image](https://user-images.githubusercontent.com/31902080/67753583-3a4f5880-fa35-11e9-8574-8395690918df.png)

**Comment by miampatate** [comment]
Hi,

In my case, i have this : 
![image](https://user-images.githubusercontent.com/57104517/67766799-a88c1f00-fa25-11e9-93ea-ccfd54f232c6.png)

Thx

**Comment by Eon9D** [comment]
Can confirm that it is not updated in GLPI and there are no locks.
Push #207 / #208 made by @yllen was tring to fix this i think.
There is also a pending Pull #196 ...
