### ISSUE TITLE
GLPI location is not imported from OCSNG TAG 

### ISSUE THREAD

**Issue by julio1501** [pluginsGLPI/ocsinventoryng#233]
Hi location ist not filled in GLPI from the OCSNG TAG

OCSNG Plugin: 1.6.1
GLPI: 9.4.5

i can see all computer assets with the right OCSNG TAG but the Dropdown Field "location" is empty 

Thanks

**Comment by tsmr** [comment]
Hello I cannot reproduce

I have setup :

![image](https://user-images.githubusercontent.com/13178158/80472374-ee7a5f00-8944-11ea-9bc6-2db244e7b652.png)

And Location is set with TAG if i do an full import

**Comment by tsmr** [comment]
No answer i close
