### ISSUE TITLE
New imported computer state  after update 1.6.0

### ISSUE THREAD

**Issue by target74** [pluginsGLPI/ocsinventoryng#236]
Dear Team,

In 1.6.0 update column states_id_default in glpi_plugin_ocsinventoryng_ocsservers has been dropped.

In fact, all new computers imported have no state ( states_id=0 ).
What can we do to restore the old behaviour and set a default state in import runs?

Plugin version:  1.6.0
GLPI version: 9.4.5
Step to reproduce: install plugin1.6.0 / update to 1.6.0 and launch import.
Thank you.

Roberto.

**Comment by giudig** [comment]
+1

**Comment by dcec** [comment]
Hi Team,

I have encountered the same problem after upgrade, 
there is another method for setting the status?

**Comment by goltob** [comment]
Hello

I also have the same problem.
Maybe there will be a workaround in the meantime?

**Comment by tsmr** [comment]
You can use Rules for assets (/front/ruleasset.form.php)

Create a new rule : 
Criterias : Element - Computer / Automatic Inventory : Yes
Action : Assign status

**Comment by giudig** [comment]
Hi @tsmr,

thanks a lot for the tip.
It works for me.

Plugin version: 1.6.0
GLPI version: 9.4.5
