### ISSUE TITLE
Error when importing equipment by SNMP

### ISSUE THREAD

**Issue by renedimv** [pluginsGLPI/ocsinventoryng#240]
Dear GLPi user.

For bug reports, you can open an issue here, provide us : 
- The version of the plugin.
  1.6.1
- The version of your GLPI.
   9.4.6
- The steps to reproduce your issue.
I have network devices (switches) added through SNMP in OCS and I want to import them to GLPi with the plugin, but when I import the devices via SNMP, the name information, MAC, description, etc., are empty.

![error_import](https://user-images.githubusercontent.com/66768502/84352474-0881a100-ab83-11ea-809d-a9a953d4b282.png)

**Comment by tsmr** [comment]
Hello

Have you defined fileds to import form OCS Server Setup ?

![image](https://user-images.githubusercontent.com/13178158/84380622-ed954800-abe7-11ea-9474-f68e71ec6812.png)

**Comment by renedimv** [comment]
I have the GLPI version 9.4.6 and I only have these options when I want to import. With which version of GLPI those options appear to you.
![snmp_ocs](https://user-images.githubusercontent.com/66768502/84471901-ed2e9880-ac4b-11ea-86e1-47598e369223.png)

**Comment by tsmr** [comment]
You must activate SNMP into OCS Server

**Comment by renedimv** [comment]
I have SNMP activated in OCS and I also have SNMP communications equipment added.
![snmp1](https://user-images.githubusercontent.com/66768502/84559534-0e04f580-ad01-11ea-9db9-a0ea29003093.png)

In GLPI when I import the new equipment with SNMP, I can see all the information of the OCS equipment.
![snmp2](https://user-images.githubusercontent.com/66768502/84559686-7accbf80-ad02-11ea-9e35-2717a62d077c.png)

But when I confirm the import in GLPI it does not add that information.
![snmp3](https://user-images.githubusercontent.com/66768502/84559701-9df76f00-ad02-11ea-9e3c-bc129c9e9cc0.png)

**Comment by tsmr** [comment]
You don't have these tabs in your setup

![image](https://user-images.githubusercontent.com/13178158/84566535-36790800-ad72-11ea-9eb3-dd2b89293e99.png)

So i think there is a problem in connection with your OCS server
