### ISSUE TITLE
OCSNG 1.6.1 Plug in error in GLPI 9.4.6

### ISSUE THREAD

**Issue by RageshR007** [pluginsGLPI/ocsinventoryng#241]
Hi

After upgrading GLPI to version 9.4.6 ..i had installed the latest OCS plugin 1.6.1..instalation looks fine..but i get an error while taking OCS configuration details...is it have any issue on the functionality..?

PHP Notice: Undefined index: use_newocs_alert in /var/www/html/octait/plugins/ocsinventoryng/inc/config.class.php at line 475
PHP Notice: Undefined index: delay_ocs in /var/www/html/octait/plugins/ocsinventoryng/inc/config.class.php at line 479

- The version of the plugin.
GLPI 9.4 : Version 1.6.1 disponible / available

- The version of your GLPI.

GLPI 9.4.6 

- The steps to reproduce your issue.

Go to the configuration of OCS plugin

The Plugin team.
![OCS](https://user-images.githubusercontent.com/56621454/84479550-c6ef1400-acb0-11ea-9e49-19834680941e.jpg)

**Comment by tsmr** [comment]
Have you the table glpi_plugin_ocsinventoryng_ocsalerts ?

**Comment by RageshR007** [comment]
thanks, tsmr..I don't really understand what u mean..can u please explain little in detail..? So that i can follow the steps.

**Comment by tsmr** [comment]
Have you a table glpi_plugin_ocsinventoryng_ocsalerts in you glpi database ?

**Comment by RageshR007** [comment]
Yes ..its have glpi_plugin_ocsinventoryng_ocsalerts table..pls see the screenshot.

![OCSPlugin](https://user-images.githubusercontent.com/56621454/84616041-54687900-aee8-11ea-94b9-e116eb293489.jpg)

**Comment by tsmr** [comment]
Have you these 2 fields (use_newocs_alert & delay_ocs) into glpi_plugin_ocsinventoryng_configs table too ?

**Comment by RageshR007** [comment]
![image](https://user-images.githubusercontent.com/56621454/84627066-d9ad5700-af03-11ea-9e09-0a7532801599.png)

**Comment by tsmr** [comment]
**glpi_plugin_ocsinventoryng_configs** (not glpi_plugin_ocsinventoryng_ocsalerts)

**Comment by RageshR007** [comment]
![image](https://user-images.githubusercontent.com/56621454/84628429-3e69b100-af06-11ea-9549-2fb5ebad4cee.png)

**Comment by tsmr** [comment]
So you must launch this SQL command :

```
ALTER TABLE `glpi_plugin_ocsinventoryng_configs` 
            ADD `delay_ocs` int(11) NOT NULL default '-1',
            ADD `use_newocs_alert` TINYINT( 1 ) NOT NULL DEFAULT '-1';
```

**Comment by RageshR007** [comment]
Thanks tsmr...will try that .

**Comment by RageshR007** [comment]
its works tsmr...thanks for your guidance.

**Comment by tsmr** [comment]
👍
