### ISSUE TITLE
Softwares not associated with Computers

### ISSUE THREAD

**Issue by asm19** [pluginsGLPI/ocsinventoryng#242]
Hello,

I am testing the plugin with version 9.5rc2 and it is working but I have a problem. When I open a computer, it does not have any associated software. The software being imported into the software category but it is not associated with computers:

- The version of the plugin: 1.7.0
- The version of your GLPI: 9.5rc2

![image](https://user-images.githubusercontent.com/1648981/86137420-2ccb0080-bae5-11ea-9f33-5cb61fc6a551.png)

![image](https://user-images.githubusercontent.com/1648981/86137530-4a986580-bae5-11ea-9064-4b1e28fa6d8c.png)

In the plugin settings the software is active:

![image](https://user-images.githubusercontent.com/1648981/86138119-f04bd480-bae5-11ea-9c5b-7e7f5448c94d.png)

Is this a bug in the plugin or GLPI?

Thank you

**Comment by tsmr** [comment]
And here

![image](https://user-images.githubusercontent.com/13178158/86138943-686ac800-baef-11ea-860a-eba42421b86f.png)

**Comment by asm19** [comment]
It's ok, disable:

![image](https://user-images.githubusercontent.com/1648981/86139670-ee831080-bae7-11ea-84f4-148f02722ca8.png)

**Comment by asm19** [comment]
@tsmr , the problem not ok.
I say "It's ok" but for: The setting is disable.

**Comment by tsmr** [comment]
Have you glpi/files/_log/ php-errors & sql-errors files ?

**Comment by asm19** [comment]
Yes, the problem is in queries:

**_Error: Table 'glpidb.glpi_computers_softwareversions' doesn't exist_**

Check logs in attach.
In php-errors don't have any error.

[sql-errors.log](https://github.com/pluginsGLPI/ocsinventoryng/files/4852725/sql-errors.log)

**Comment by tsmr** [comment]
So this is not a problem with the plugin. Your glpi database is corrupted.

**Comment by asm19** [comment]
I created the database again with version 9.5rc2 and the glpi_computers_softwareversions table is not created. I think the table name has been changed in this latest version of glpi?

**Comment by tsmr** [comment]
ok i see : the tables are been renamed : glpi_items_softwareversions - i'll do a correction in the plugin

**Comment by asm19** [comment]
Ok, thank you.
When you make the correction I put it in my environment.

**Comment by asm19** [comment]
The query have errors:

First, check the spaces, example (but have more, in more than one place):

![image](https://user-images.githubusercontent.com/1648981/86153762-0794bd00-bafa-11ea-8bcf-41bd0c758ff9.png)

I try execute the query manually in sql but I have one more column that doesn't exist:

SELECT `glpi_items_softwareversions`.`id` as id, `glpi_softwares`.`name` as sname, `glpi_softwareversions`.`name` as vname FROM `glpi_items_softwareversions` INNER JOIN `glpi_softwareversions` ON `glpi_softwareversions`.`id`= `glpi_items_softwareversions`.`softwareversions_id` INNER JOIN `glpi_softwares` ON `glpi_softwares`.`id`= `glpi_softwareversions`.`softwares_id` WHERE `glpi_items_softwareversions`.`computers_id`= 51 AND `glpi_items_softwareversions`.`itemtype`= 'Computer' AND `is_dynamic` = 1;

_**ERROR 1054 (42S22): Unknown column 'glpi_items_softwareversions.computers_id' in 'where clause'**_

**Comment by asm19** [comment]
Hello Xavier,

I already tested your latest version, it still has errors. That's what I said above, you have a "space" at the end of the column name, example:

'glpi_items_softwareversions **'**

Log in attach.
[sql-errors.log](https://github.com/pluginsGLPI/ocsinventoryng/files/4863260/sql-errors.log)
