### ISSUE TITLE
[OCS Inventory] Changes in software database model

### ISSUE THREAD

**Issue by gillesdubois** [pluginsGLPI/ocsinventoryng#243]
Hi,

I'm from the OCS Inventory Team and I would like to inform you about a database change in our software inventory.

We recently changed how we manage software inventory in OCS.
You will find at the following link the SQL changes we performed : https://github.com/OCSInventory-NG/OCSInventory-ocsreports/blob/master/files/update/7030.sql

The next release that will have this change is the 2.8 and will be most likely released in September / October.
I'm creating this issue so you can get informed of the change.

We'll try to submit a PR during this summer :) 

Regards,
Gilles Dubois.

**Comment by tsmr** [comment]
Thanks for your report  👍 

We will try to check your changes for implement them into plugin

**Comment by tsmr** [comment]
https://github.com/pluginsGLPI/ocsinventoryng/commit/5c157b1c4c2192da3bd890be0798ed32533734ee

**Comment by jorgeag68** [comment]
Hello,

The fix here does not work for me with Plugin version 1.6.1 and OCSNG 2.8.0.

https://github.com/pluginsGLPI/ocsinventoryng/commit/90ef807511f5f2fb4be53ceb4c4a8ed6986909c7

getting this error:

"""
[2020-10-29 15:29:42] glpisqllog.ERROR: DBmysql::query() in /usr/share/glpi/inc/dbmysql.class.php line 188
  *** MySQL query error:
  SQL: SELECT
                                        IFNULL(`dico_soft`.`FORMATTED`, `softwares`.`NAME`) AS NAME,
                                        `softwares`.`VERSION`,
                                        `softwares`.`PUBLISHER`,
                                        `softwares`.`COMMENTS`,
                                        `softwares`.`FOLDER`,
                                        `softwares`.`FILENAME`,
                                        `softwares`.`FILESIZE`,
                                        `softwares`.`SOURCE`,
                                        `softwares`.`HARDWARE_ID`,`softwares`.`GUID`,
                                        `softwares`.`LANGUAGE`,
                                        `softwares`.`INSTALLDATE`,
                                        `softwares`.`BITSWIDTH`FROM `softwares`
                            INNER JOIN `dico_soft` ON (`softwares`.`NAME` = `dico_soft`.`EXTRACTED`)
                            WHERE `softwares`.`HARDWARE_ID` IN (22)ORDER BY `id` DESC
  Error: Table 'ocsweb.softwares' doesn't exist
  Backtrace :
  ...ns/ocsinventoryng/inc/ocsdbclient.class.php:340 
  ...s/ocsinventoryng/inc/ocsdbclient.class.php:1008 PluginOcsinventoryngOcsDbClient->getComputerSections()
  plugins/ocsinventoryng/inc/ocsclient.class.php:374 PluginOcsinventoryngOcsDbClient->getComputers()
  ...ns/ocsinventoryng/inc/ocsprocess.class.php:1159 PluginOcsinventoryngOcsClient->getComputer()
  plugins/ocsinventoryng/front/ocsng.sync.php:52     PluginOcsinventoryngOcsProcess::synchronizeComputer()

"""

Regards,
