### ISSUE TITLE
OCS Inventory Pulgin for GLPI9.5

### ISSUE THREAD

**Issue by ITSyners** [pluginsGLPI/ocsinventoryng#244]
Hi friends, 

The last week I Updated the GLPI program to the new version, 9.5.0
Before that I had install the OCS Inventory plugin, but with the new version the plugin is not compatible.

I need know when I can have the new version of the Ocs Inventory Plugin to run with GLPI 9.5.0

Thanks a lot.

**Comment by koffisani** [comment]
Needed here too.

**Comment by benoitsauveing** [comment]
I need too.

**Comment by projetoroot** [comment]
we have a large number of requests from our subscribers on our youtube channel for the plugin update, we are looking forward to the update.

**Comment by tsmr** [comment]
https://github.com/pluginsGLPI/ocsinventoryng/releases/tag/1.7.0

**Comment by koffisani** [comment]
Thank you, @tsmr.
