### ISSUE TITLE
Software import issue (Table 'ocs.softwares' doesn't exist) 

### ISSUE THREAD

**Issue by lble44** [pluginsGLPI/ocsinventoryng#245]
Hi,

I have an issue to import software. When I try to import new computers with software option enabled, it doesn't work.
Here is the sql-errors_log, it seems like the table ocs.softwares is missing :
---------------------------------------------------------------------------------------------------------------------------------
[2020-07-31 13:07:32] glpisqllog.ERROR: DBmysql::query() in /var/www/html/glpi/inc/dbmysql.class.php line 188
  *** MySQL query error:
  SQL: SELECT
                                        `softwares`.`NAME`,
                                        `softwares`.`VERSION`,
                                        `softwares`.`PUBLISHER`,
                                        `softwares`.`COMMENTS`,
                                        `softwares`.`FOLDER`,
                                        `softwares`.`FILENAME`,
                                        `softwares`.`FILESIZE`,
                                        `softwares`.`SOURCE`,
                                        `softwares`.`HARDWARE_ID`,`softwares`.`GUID`,
                                  `softwares`.`LANGUAGE`,
                                  `softwares`.`INSTALLDATE`,
                                  `softwares`.`BITSWIDTH`FROM `softwares`
                             WHERE `softwares`.`HARDWARE_ID` IN (1)ORDER BY `id` DESC
  Error: Table 'ocs.softwares' doesn't exist
  Backtrace :
  ...ns/ocsinventoryng/inc/ocsdbclient.class.php:340 
  ...s/ocsinventoryng/inc/ocsdbclient.class.php:1008 PluginOcsinventoryngOcsDbClient->getComputerSections()
  plugins/ocsinventoryng/inc/ocsclient.class.php:374 PluginOcsinventoryngOcsDbClient->getComputers()
  ...ns/ocsinventoryng/inc/ocsprocess.class.php:1159 PluginOcsinventoryngOcsClient->getComputer()
  plugins/ocsinventoryng/front/ocsng.sync.php:52     PluginOcsinventoryngOcsProcess::synchronizeComputer()
  {"user":"9@PAH-FUSION01"} 
-------------------------------------------------------------------------------------------------------------------------

Bug reports version :
- plugin : 1.6.1
- GLPI : 9.4.4

Thank's in advance for your answers.

**Comment by gillesdubois** [comment]
Hi @lble44 

I'm not an expert in the OCS / GLPI Connector but OCS software's datamodel has changed recently.
If you are running a nightly "softwares" table won't exist anymore since its been replaced by multiple tables.

See : https://github.com/pluginsGLPI/ocsinventoryng/issues/243

I think that the connector is not updated yet 

Regards,
Gilles Dubois.

**Comment by micter59** [comment]
Thanks tsmr ! Il had the same error, and I did use the 2 files that you modified. Now the plugin is fully functionnal.

**Comment by tsmr** [comment]
https://github.com/pluginsGLPI/ocsinventoryng/commit/5c157b1c4c2192da3bd890be0798ed32533734ee
