### ISSUE TITLE
 PHP Notice:  Undefined index: instantiation_type

### ISSUE THREAD

**Issue by cristianmenghi** [pluginsGLPI/ocsinventoryng#246]
I got this error when trie to synchronize already imported equipment 

HP Notice:  Undefined index: instantiation_type in /var/www/html/glpi/plugins/ocsinventoryng/inc/networkport.class.php on line 135, referer: http://server.uy/plugins/ocsinventoryng/front/ocsng.sync.php

But for some computers, not all.

GLPI 9.5.1
Plugin: 1.7.0
MySQL 5.7 
all on Ubuntu 18.04

**Comment by tsmr** [comment]
Can you verify in your GLPI database if you have into glpi_networkports table a instantiation_type field ?

**Comment by tsmr** [comment]
No answer i close
