### ISSUE TITLE
OS version import

### ISSUE THREAD

**Issue by hgpit** [pluginsGLPI/ocsinventoryng#248]
OCS Server v2.7
GLPI v9.5.1
OCS Plugin v1.7.0

Hello,

We have found that the Operating System version reported in OCS is different to that which is displayed in GLPI.
For instance, we have a PC (under Assets: Computers), which _is_ synced with OCS and in GLPI has an OS version of 10.0.14393. However, if we look at the same computer on our OCS Server, it has the correct OS version of 10.0.17134.

This seems to be the case with all computers. We are guessing that GLPI's 'OS Version' only gets populated on the first import from OCS.

Is there any chance this can be fixed/changed to sync every time the plugin syncs the asset?

Thank you.

**Comment by 88ee55** [comment]
Did so

Changed inc/os.class.php
```
         if ($force) {
            self::resetOS($options['computers_id'], $uninstall_history);
         }
```

```

         if ($force || $computerOS != $hardware["OSNAME"]) {
            self::resetOS($options['computers_id'], $uninstall_history);
         }
```

**Comment by hgpit** [comment]
Hi, I'm just picking this one up on behalf of my colleague. The code is there as per the last update

if ($force || $computerOS != $hardware["OSNAME"]) {
            self::resetOS($options['computers_id'], $uninstall_history);
         }

![image](https://user-images.githubusercontent.com/16598973/114902471-c6ae3080-9e0d-11eb-9ad2-bf0ac677a93e.png)
![image](https://user-images.githubusercontent.com/16598973/114902541-d4fc4c80-9e0d-11eb-84d7-c393a1678303.png)

**Comment by jpclerc** [comment]
> 
> 
> OCS Server v2.7 GLPI v9.5.1 OCS Plugin v1.7.0
> 
> Hello,
> 
> We have found that the Operating System version reported in OCS is different to that which is displayed in GLPI. For instance, we have a PC (under Assets: Computers), which _is_ synced with OCS and in GLPI has an OS version of 10.0.14393. However, if we look at the same computer on our OCS Server, it has the correct OS version of 10.0.17134.
> 
> This seems to be the case with all computers. We are guessing that GLPI's 'OS Version' only gets populated on the first import from OCS.
> 
> Is there any chance this can be fixed/changed to sync every time the plugin syncs the asset?
> 
> Thank you.

No solution ?
