### ISSUE TITLE
Linking new computers in OCSNG with existing ones in GLPI doesn't work

### ISSUE THREAD

**Issue by sessterling** [pluginsGLPI/ocsinventoryng#249]
Plugin Version : 1.7.0
GLPI Version : 9.5.1
OCSREPORTS : Ocs Inventory Server 2.7

I try to linking new computers in OCSNG with existing ones in GLPI , but the list is always empty.

**Comment by Muzo18** [comment]
Hello,

I'm French.
I got the same issue.

Plugin Version : 1.7.0
GLPI Version : 9.5.1
OCSREPORTS : Ocs Inventory Server 2.5

"Import new computers" list contains some computers, but "Link new OCSNG computers to existing GLPI computers" list is empty.

Thanks for your help.

Have a good day.

**Comment by tsmr** [comment]
Have you created a rule for link computers ? http://.../front/ruleimportcomputer.php

**Comment by Muzo18** [comment]
Thanks for your response.

I have the same rule between GLPI 9.4 and 9.5.
![image](https://user-images.githubusercontent.com/55094140/91052370-a7198c00-e621-11ea-81e1-409b4d416a3c.png)


There is something to change ?

**Comment by Muzo18** [comment]
Je pense avoir compris.

La règle qui était reprise de la version précédente nécessitait que le nom de machine **ET** le numéro de série soient communs pour proposer la liaison OCS-GLPI.
Dans mon cas, pour les ordinateurs concernés, le nom était OK, mais le numéro de série ne correspondait pas (pas bien pris en charge dans le BIOS et dans OCS).
Comme les 2 critères ne correspondaient pas, les ordinateurs n'apparaissent pas dans la liste des liaisons possible.

J'ai créé une nouvelle règle uniquement sur le nom, et la liste n'est plus vide.

Merci de m'avoir guidé.
Je pense que d'autres utilisateurs vont rencontrer ce soucis, mais ils pourront le régler.

Bonne journée.

**Comment by rollandpf** [comment]
Bonjour,

j'ai le même problème. Modifier les règles comme indiqué ne change rien pour moi. Par contre j'ai remarqué que dans mon cas la non présentation des anciens éléments à lier vient de la récursivité.

J'ai plusieurs entité et sous entités. Si je me place dans l'entité racine la liste des éléments à lier est vide. Si je me positionne dans l'entité où l’élément à lié est enregistré dans GLPI, il apparaît.

Bonne journée.

**Comment by tigerblue77** [comment]
Bonjour,

nous rencontrons le même problème en 9.5.1, nos nouveaux ordinateurs atterrissent dans "Importation de nouveaux ordinateurs" alors que précédemment ils étaient bien ajoutés à notre base GLPI. Nous avons une tâche CRON qui fonctionne toutes les demi-heures et appelle les deux commandes suivantes :

/var/www/glpi/plugins/ocsinventoryng/scripts/ocsng_fullsync.sh --thread_nbr=2 --server_id=1
/var/www/php /var/www/glpi/front/cron.php --force ocsng

Cela fonctionnait en 9.4.x

Merci d'avance pour votre aide

Plugin Version : 1.7.0
GLPI Version : 9.5.0
OCSREPORTS : Ocs Inventory Server 2.7
Ubuntu 18.04.5 LTS

**Comment by y0rune** [comment]
When you would like to solve that problem you only must create a new rule.

Administration -> Rules -> Rules for assigning an item to an entity 
![image](https://user-images.githubusercontent.com/10187235/94665887-03e92000-030d-11eb-9c22-098460b5324a.png)
![image](https://user-images.githubusercontent.com/10187235/94665929-0ea3b500-030d-11eb-8a4d-e9e9384bca8d.png)


After that you only **have to enable** that rule and it should work. 
![image](https://user-images.githubusercontent.com/10187235/94666026-32ff9180-030d-11eb-9459-7569c107e854.png)

**Comment by Muzo18** [comment]
Hello y0rune,

Thanks for your answer, but I can't choose the criteria "is already present in GLPI".
The only choices presented by GLPI in my case :

![2020-09-30 12_54_11-GLPI - Rules - 21](https://user-images.githubusercontent.com/55094140/94676786-2a628780-031c-11eb-8376-830f1539a86f.png)

**Comment by y0rune** [comment]
@Muzo18 You should go to Rules for assigning an item to an entity
![image](https://user-images.githubusercontent.com/10187235/94689117-c2696c80-032e-11eb-84c0-7a240c33193c.png)
![image](https://user-images.githubusercontent.com/10187235/94689182-d8772d00-032e-11eb-8bdc-fbdb22c75e6d.png)

**Comment by Muzo18** [comment]
Oh yes, I understand the error : 
I selected "Rules for Assigning an Item to an Entity" like you said, but in the screenshot, it's "Rules for import and link computers".
It works better now   ;o)
I also created a new rule with the same parameters, but using "serial numbers" instead of "computer's name".

All is ok now.

Thank you

**Comment by y0rune** [comment]
Sorry yeah that was my mistake. 

---
Y0rune

**Comment by Muzo18** [comment]
Don't worry.
Thank you.
