### ISSUE TITLE
Data Import - Plugin OCS Bitlocker

### ISSUE THREAD

**Issue by GuillaumeFabre69** [pluginsGLPI/ocsinventoryng#250]
Plugin Version : 1.7.0
GLPI Version : 9.5.1
OCSREPORTS : Ocs Inventory Server 2.7

Bonjour,
serait-il possible d'ajouter les données du plugin OCS Bitlocker dans l'import de GLPI.
GLPI ayant ajouté dans sa version 9.5 le chiffrement des volumes.
![1](https://user-images.githubusercontent.com/70584361/91855907-1fa5cb80-ec66-11ea-9168-2746744f05c4.png)
![2](https://user-images.githubusercontent.com/70584361/91856060-51b72d80-ec66-11ea-9326-4840aa4b688a.png)

Merci.

**Comment by keha35** [comment]
Hi, 

i've commit this upgrade : 
https://github.com/pluginsGLPI/ocsinventoryng/commit/2b4c068a9318f9d16219fb07585e1354da2e37a4

It will be in the next release.

**Comment by GuillaumeFabre69** [comment]
Thanks you !!!
