### ISSUE TITLE
Can't import new computers to GLPI from OCS Inventory using plugin 

### ISSUE THREAD

**Issue by AcidoSour** [pluginsGLPI/ocsinventoryng#251]
Hello

I installed GLPI and OCS in my Debian 10 server, then I configured it and installed OCS Plugin (1.7.0) on GLPI. The first time that i tried to search computers using OCS plugin on GLPI it worked, showed me all the computers that i had installed the OCS agent, but after that, I installed the agent on 3 new computers, OCS showed me that the new computers are ok, but when i try to import new computers on GLPI it says that there is no new computer to import. I can synchronize computers that i have already imported to GLPI but i cant import new computers.

Anyone know what is wrong? Thank you for your time.

- OCS  2.7
- GLPI 9.5.1
- Plugin 1.7.0

**Comment by Dealtis-mcado** [comment]
hi i have a same issue
the error at the import
![image](https://user-images.githubusercontent.com/69046138/92938101-6f497b80-f44c-11ea-8f21-dac26817d44f.png)

**Comment by tsmr** [comment]
> hi i have a same issue
> the error at the import
> ![image](https://user-images.githubusercontent.com/69046138/92938101-6f497b80-f44c-11ea-8f21-dac26817d44f.png)

Which version of plugin please ?

**Comment by Dealtis-mcado** [comment]
Centos 8 for glpi, centos 7 for ocs server
OCS 2.6
GLPI 9.5.1
Plugin 1.7.0

**Comment by Dealtis-mcado** [comment]
i have an error in my hook.php, i replace this wth the last file in the last release, its ok now

**Comment by tsmr** [comment]
https://github.com/pluginsGLPI/ocsinventoryng/releases/tag/1.7.3
