### ISSUE TITLE
plugin will not import/sync computers on OCS Server 2.8 

### ISSUE THREAD

**Issue by gitdevmod** [pluginsGLPI/ocsinventoryng#252]
plugin:1.7.0
glpi:9.5.1
ocs server 2.8
ocs agent 2.8

Since last update of ocs server to 2.8, glpi ocs plugin can not import computers because of change in software(s) table
I can see computers that need update or import but on excution it fails

`SQL Error "1146": Table 'ocsweb.softwares' doesn't exist in query "SELECT `softwares`.`NAME`, `softwares`.`VERSION`, `softwares`.`PUBLISHER`, `softwares`.`COMMENTS`, `softwares`.`FOLDER`, `softwares`.`FILENAME`, `softwares`.`FILESIZE`, `softwares`.`SOURCE`, `softwares`.`HARDWARE_ID`,`softwares`.`GUID`, `softwares`.`LANGUAGE`, `softwares`.`INSTALLDATE`, `softwares`.`BITSWIDTH`FROM `softwares` WHERE `softwares`.`HARDWARE_ID` IN (972)ORDER BY `id` DESC"
Uncaught Exception Error: Call to a member function fetch_assoc() on bool in /usr/share/glpi/inc/dbmysql.class.php at line 496`

Maybe it's this [change](https://github.com/OCSInventory-NG/OCSInventory-ocsreports/commit/1a8d19c4be713739d7043761aa70b383a3c83c36)

**Comment by maltyx** [comment]
The same problem on OSC NG server 2.8 / GLPI 9.4.6 / OCS Inventory plugin for GLPI 1.6.1

**Comment by tsmr** [comment]
https://github.com/pluginsGLPI/ocsinventoryng/commit/5c157b1c4c2192da3bd890be0798ed32533734ee
