### ISSUE TITLE
unable to import or synchronize : Uncaught Exception Error: Call to a member function fetch_assoc() on bool in /var/www/html/cmdb/inc/dbmysql.class.php at line 496

### ISSUE THREAD

**Issue by laTruffe79** [pluginsGLPI/ocsinventoryng#253]
Dear GLPi user.

For bug reports, you can open an issue here, provide us : 
- The version of the plugin : 1.7
- The version of your GLPI. 9.5
- The steps to reproduce your issue.
Just try to import or synchronize and we get a blank page and this in php log : 
glpiphplog.CRITICAL:   *** Uncaught Exception Error: Call to a member function fetch_assoc() on bool in /var/www/html/cmdb/inc/dbmysql.class.php at line 496
  Backtrace :
  ...ns/ocsinventoryng/inc/ocsdbclient.class.php:341 DBmysql->fetchAssoc()
  ...s/ocsinventoryng/inc/ocsdbclient.class.php:1008 PluginOcsinventoryngOcsDbClient->getComputerSections()
  plugins/ocsinventoryng/inc/ocsclient.class.php:377 PluginOcsinventoryngOcsDbClient->getComputers()
  ...ns/ocsinventoryng/inc/ocsprocess.class.php:1165 PluginOcsinventoryngOcsClient->getComputer()
  plugins/ocsinventoryng/front/ocsng.sync.php:52     PluginOcsinventoryngOcsProcess::synchronizeComputer()

thanks for your help

**Comment by laTruffe79** [comment]
It's related to the parameter "data to import" when I change the value in section software to unique import, when I disable it it works again and when I enable it, it fails.
![Capture d’écran de 2020-09-16 16-59-15](https://user-images.githubusercontent.com/7983536/93355329-39d2d280-f83e-11ea-82a7-19894b409b18.png)

**Comment by Dealtis-mcado** [comment]
Pas de changement chez moi en changeant ces options

**Comment by laTruffe79** [comment]
Remplacé par quoi ?

**Comment by Dealtis-mcado** [comment]
j'ai repris le fichier hook.php de la dernière release ocs, lors de la maj, ce fichier a du mal passé

**Comment by pbiggin23** [comment]
Hopefully Google Translates this well.

Hi I can confirm we have this issue aswell.

Setting the software to "No Import"allows the rest of OCS to Sync like normal as mentioned above.

I think GLPI has changed the software tables in 9.5.1 that now don't work with the OCS Plugin. 


======================================================


Espérons que Google traduit bien cela.

Salut, je peux confirmer que nous avons également ce problème.

Régler le logiciel sur "Aucune importation" permet au reste d'OCS de se synchroniser comme d'habitude, comme mentionné ci-dessus.

Je pense que GLPI a changé les tables de logiciels dans 9.5.1 qui ne fonctionnent plus avec le plugin OCS.

**Comment by laTruffe79** [comment]
Hello, I think that GLPI cannot import from ocs because there is a change in ocs's database and so there is an exception throwed (not very usefull in order to debug...) I got no time these days to investigate more but the issue is confirmed.

**Comment by Dealtis-mcado** [comment]
i have ocs 2.6, glpi 9.5.1 and plugin ocs 1.7 and all function are ok, the problem is in your configuration, try to reinstall the plugin and update glpi

**Comment by pbiggin23** [comment]
Yeah I have rolled back the OCS server to 2.6 from 2.8 this morning and everything is fine with GLPI on 9.5.1 and Plugin OCS at 1.7

So OCS 2.8 is the problem.

**Comment by laTruffe79** [comment]
It seems to be related with [that](https://github.com/pluginsGLPI/ocsinventoryng/issues/245) strange that there is not a PR to solve that.

**Comment by tsmr** [comment]
https://github.com/pluginsGLPI/ocsinventoryng/commit/5c157b1c4c2192da3bd890be0798ed32533734ee
