### ISSUE TITLE
Pas de remonté des nouveaux PC OCS ==>GLPI

### ISSUE THREAD

**Issue by Epoc2016** [pluginsGLPI/ocsinventoryng#254]
Bonjour,

J'utilise OCS et GLPI depuis quelques temps, et tout à toujours bien fonctionné, mais , depuis la mise à jour GLPI 95.1 et le plugin GLPI/OCS 1.7.0, (OS: Debian 10.5) je n'ai plus la remonté de nouveaux PC depuis le serveur OCS.
mon serveur GLPI n'est pas encore en production, je test avant...

Ma configuration OCS, est la même que celle de mon serveur de prod, le test est positif, il contacte bien le serveur OCS

_Mon serveur de prod (OS: Debian 9.0) est GLPI 9.4.6 et le plugin OCS en prod est 1.6.0_ 

Merci d'avance,
Cordialement,

_Epoc_

**Comment by laTruffe79** [comment]
As tu ce soucis ? => [https://github.com/pluginsGLPI/ocsinventoryng/issues/253](https://github.com/pluginsGLPI/ocsinventoryng/issues/253)

**Comment by Epoc2016** [comment]
Hummm.. bonne question...
Je controlerai d'ici lundi.. 
Mais je pense que c'est plus un soucis de droits...je ferai un test d'ici lundi..
Et je reviendrai donner le résultat...
La synchronisation est ok.. donc pas de raison que le rapatriement des nouveaux pc ne remonte pas...
Je tiens informé...
Merci du retour...

**Comment by Epoc2016** [comment]
Bonjour,
Ben pour les infos..:
     Tout est ok, la remontée des nouveau PC se fait correctement.
     Debian 10.5.0  ...  GLPI 9.5.1 ....  Plugin OCS 1.7.0
Voila, problème de droit sur le dossier...
Merci pour les infos..

Je clôture le post
