### ISSUE TITLE
Error using Clean OCSNG deleted computers

### ISSUE THREAD

**Issue by lucafwp** [pluginsGLPI/ocsinventoryng#255]
Using clean OCSNG deleted computers function the following error is displayed:

`glpiphplog.CRITICAL:   *** Uncaught Exception ErrorException: Undefined variable: sess_last_req in /usr/share/glpi/plugins/ocsinventoryng/front/deleted_equiv.php at line 71
  Backtrace :
  plugins/ocsinventoryng/front/deleted_equiv.php:71  Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}()`

To reproduce the bug:
- create a pc in OCS
- import it in GLPI
- delete the pc on OCS
- go to clean OCSNG deleted computers functionality

- Plugin version: 1.7.0
- GLPI version: 9.5.1
- OCS version: 2.7.0

A possibile workaround might be the following:

> --- /usr/share/glpi/plugins/ocsinventoryng/front/deleted_equiv.php 2020-10-09 12:03:51.702623020 +0200
+++ /usr/share/glpi/plugins/ocsinventoryng/front/deleted_equiv.php.new  2020-10-12 11:19:25.860627983 +0200
@@ -63,7 +63,7 @@
       PluginOcsinventoryngOcsProcess::manageDeleted($_SESSION["plugin_ocsinventoryng_ocsservers_id"]);
    }
>\-   if ($_SESSION["ocs_deleted_equiv"]["total"] != $_SESSION["ocs_deleted_equiv"]["deleted"] && $_SESSION["ocs_deleted_equiv"]["last_req"]) {
>\+   if ($_SESSION["ocs_deleted_equiv"]["total"] != $_SESSION["ocs_deleted_equiv"]["deleted"] && isset($_SESSION["ocs_deleted_equiv"]["last_req"])) {
>       echo $_SESSION["ocs_deleted_equiv"]["deleted"] . "/" . $_SESSION["ocs_deleted_equiv"]["total"];
       echo "<br><br>";

**Comment by lucafwp** [comment]
I think I've found the problem here.
A table is missing:

`CREATE TABLE `deleted_equiv` (
  `DATE` timestamp NOT NULL default CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
  `DELETED` varchar(255) NOT NULL,
  `EQUIVALENT` varchar(255) default NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;`

It is required by function _getDeletedComputers_ in file _ocsinventoryng/inc/ocsdbclient.class.php_ .
I can't find this table in GLPI source code nor in plugin OCSNG.
Where should this table be created?

**Comment by tsmr** [comment]
https://github.com/pluginsGLPI/ocsinventoryng/commit/fea07400dd624934ca14baa40d0ca5b1ef0c1d47
