### ISSUE TITLE
Import new computer or synchronize existing computer, the software cannot be imported

### ISSUE THREAD

**Issue by xupei30** [pluginsGLPI/ocsinventoryng#257]
Dear Plugin team

For bug reports, you can open an issue here, provide us : 
- plugin 1.7.0
- GLPI 9.5.2
-OCS-Server2.8
-CentOS7
-PHP7.4
-Mysql5.7
- Import new computer or synchronize existing computer, the software cannot be imported

debug:
PHP User deprecated function (16384): Use sodiumDecrypt in /var/www/html/glpi/inc/toolbox.class.php at line 632
PHP User deprecated function (16384): Use sodiumDecrypt in /var/www/html/glpi/inc/toolbox.class.php at line 632
PHP User deprecated function (16384): Use sodiumDecrypt in /var/www/html/glpi/inc/toolbox.class.php at line 632
PHP User deprecated function (16384): Use sodiumDecrypt in /var/www/html/glpi/inc/toolbox.class.php at line 632
PHP User deprecated function (16384): Use sodiumDecrypt in /var/www/html/glpi/inc/toolbox.class.php at line 632
PHP User deprecated function (16384): Use DBmysql::insertId() in /var/www/html/glpi/inc/toolbox.class.php at line 632
PHP User deprecated function (16384): Use sodiumDecrypt in /var/www/html/glpi/inc/toolbox.class.php at line 632
PHP User deprecated function (16384): Use sodiumDecrypt in /var/www/html/glpi/inc/toolbox.class.php at line 632
PHP User deprecated function (16384): Use sodiumDecrypt in /var/www/html/glpi/inc/toolbox.class.php at line 632
PHP User deprecated function (16384): Use sodiumDecrypt in /var/www/html/glpi/inc/toolbox.class.php at line 632
SQL Error "1146": Table 'ocs.softwares' doesn't exist in query "SELECT `softwares`.`NAME`, `softwares`.`VERSION`, `softwares`.`PUBLISHER`, `softwares`.`COMMENTS`, `softwares`.`FOLDER`, `softwares`.`FILENAME`, `softwares`.`FILESIZE`, `softwares`.`SOURCE`, `softwares`.`HARDWARE_ID`,`softwares`.`GUID`, `softwares`.`LANGUAGE`, `softwares`.`INSTALLDATE`, `softwares`.`BITSWIDTH`FROM `softwares` WHERE `softwares`.`HARDWARE_ID` IN (19)ORDER BY `id` DESC"
Uncaught Exception Error: Call to a member function fetch_assoc() on bool in /var/www/html/glpi/inc/dbmysql.class.php at line 496
![20201027100311](https://user-images.githubusercontent.com/59216351/97248007-c4462300-183b-11eb-9628-8273d987a929.png)

**Comment by tsmr** [comment]
https://github.com/pluginsGLPI/ocsinventoryng/commit/5c157b1c4c2192da3bd890be0798ed32533734ee
