### ISSUE TITLE
Can't import new computers to GLPI from OCS Inventory using plugin 1.7.0

### ISSUE THREAD

**Issue by snowliou** [pluginsGLPI/ocsinventoryng#258]
Hello 

I hope Google translates well...
I installed GLPI and OCS on the Centos 7 server, then configured them and installed the OCS plugin (1.7.1) on GLPI
After the first synchronization, the OCS computer cannot be synchronized to GLPI correctly, only the computer name is displayed on GLPI, and the detailed data is not synchronized.
And after manual synchronization, there are many waiting information points that cannot be synchronized normally, and then click debug mode to appear
PHP User deprecated function (16384): Use sodiumDecrypt in /var/www/html/glpi/inc/toolbox.class.php at line 632
PHP User deprecated function (16384): Use sodiumDecrypt in /var/www/html/glpi/inc/toolbox.class.php at line 632
PHP User deprecated function (16384): Use sodiumDecrypt in /var/www/html/glpi/inc/toolbox.class.php at line 632
PHP User deprecated function (16384): Use sodiumDecrypt in /var/www/html/glpi/inc/toolbox.class.php at line 632

PHP User deprecated function (16384): Use sodiumDecrypt in /var/www/html/glpi/inc/toolbox.class.php at line 632
PHP User deprecated function (16384): Use DBmysql::fetchRow() in /var/www/html/glpi/inc/toolbox.class.php at line 632

Does anyone know what's wrong? thank you for your time.

centos 7.5
OCS 2.8
GLPI 9.5.2
Plugin 1.7.0
![image](https://user-images.githubusercontent.com/73454496/97402600-c38db980-192d-11eb-8b9b-2d0ffa87c12e.png)

**Comment by snowliou** [comment]
View error log:
[Wed Oct 28 14:13:47.353580 2020] [php7:warn] [pid 211248:tid 140132837455616] [client 10.3.13.36:62637] PHP Warning: mysqli::real_connect(): (HY000/1045): Access denied for user'ocs'@'localhost' (using password: NO) in /var/www/html/glpi/inc/dbmysql.class.php on line 185, referer: http://10.3.6.51/glpi/plugins/ocsinventoryng /front/ocsng.php

**Comment by tsmr** [comment]
Hello Can you try to save the server configuration by resetting the password? (not change the password in mysql) - just add the password field & save the form glpi/plugins/ocsinventoryng/front/ocsserver.form.php?id=X

**Comment by tsmr** [comment]
& try this too : https://github.com/pluginsGLPI/ocsinventoryng/commit/a88a9f79581cf4bd0e7393d70bd554d80cfc6230

**Comment by snowliou** [comment]
> Hello Can you try to save the server configuration by resetting the password? (not change the password in mysql) - just add the password field & save the form glpi/plugins/ocsinventoryng/front/ocsserver.form.php?id=X


Do you use the web interface to reset the password?

**Comment by tsmr** [comment]
Do not change password in database !
Just go on form : glpi/plugins/ocsinventoryng/front/ocsserver.form.php?id=X & just add the password field & save the form

**Comment by snowliou** [comment]
> 並[嘗試](https://github.com/pluginsGLPI/ocsinventoryng/commit/a88a9f79581cf4bd0e7393d70bd554d80cfc6230)一下：[a88a9f7](https://github.com/pluginsGLPI/ocsinventoryng/commit/a88a9f79581cf4bd0e7393d70bd554d80cfc6230)

![image](https://user-images.githubusercontent.com/73454496/97419190-bc25da80-1944-11eb-94cb-6a91a2e263e9.png)
![image](https://user-images.githubusercontent.com/73454496/97419215-c3e57f00-1944-11eb-902e-62375ea02c28.png)

PHP User Warning (512): Unable to extract nonce from content. It may not have been crypted with sodium functions. in /var/www/html/glpi/inc/toolbox.class.php at line 293
PHP Warning (2): mysqli::real_connect(): (HY000/1045): Access denied for user 'ocs'@'localhost' (using password: NO) in /var/www/html/glpi/inc/dbmysql.class.php at line 185
PHP User Warning (512): Unable to extract nonce from content. It may not have been crypted with sodium functions. in /var/www/html/glpi/inc/toolbox.class.php at line 293
PHP Warning (2): mysqli::real_connect(): (HY000/1045): Access denied for user 'ocs'@'localhost' (using password: NO) in /var/www/html/glpi/inc/dbmysql.class.php at line 185

PHP User Warning (512): Unable to extract nonce from content. It may not have been crypted with sodium functions. in /var/www/html/glpi/inc/toolbox.class.php at line 293
PHP Warning (2): mysqli::real_connect(): (HY000/1045): Access denied for user 'ocs'@'localhost' (using password: NO) in /var/www/html/glpi/inc/dbmysql.class.php at line 185
PHP Warning (2): mysqli::query(): invalid object or resource mysqli in /var/www/html/glpi/inc/dbmysql.class.php at line 299
SQL Error "1045": Access denied for user 'ocs'@'localhost' (using password: NO) in query "SELECT COUNT(*) FROM `deleted_equiv`"
PHP User deprecated function (16384): Use DBmysql::fetchRow() in /var/www/html/glpi/inc/toolbox.class.php at line 632
Uncaught Exception Error: Call to a member function fetch_row() on bool in /var/www/html/glpi/inc/dbmysql.class.php at line 471

**Comment by tsmr** [comment]
Please test use the master version of the plugin

**Comment by snowliou** [comment]
> Please test use the master version of the plugin


I do not quite understand you...

**Comment by Blank-Vcf** [comment]
Use the green code button on the project code tab. You will get zip and extract everyting as you do it in the plugin folder.

**Comment by tsmr** [comment]
https://github.com/pluginsGLPI/ocsinventoryng/releases/tag/1.7.3
