### ISSUE TITLE
Sodium error 

### ISSUE THREAD

**Issue by Blank-Vcf** [pluginsGLPI/ocsinventoryng#259]
For bug reports, you can open an issue here, provide us : 
- The version of the plugin. 1.7.1
- The version of your GLPI. 9.5.2
- Ocs 2.8 version 7039

Have the same problem with other issues. I have deleted the whole plugin folder and install plugin 1.7.1.

After resseting the ocs password i get the error in glpi log:

] glpiphplog.CRITICAL:   *** Uncaught Exception SodiumException: secret key size should be SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_KEYBYTES bytes in /var/www/inc/toolbox.class.php at line 306
  Backtrace :
  inc/toolbox.class.php:306                          sodium_crypto_aead_xchacha20poly1305_ietf_decrypt()
  ...ins/ocsinventoryng/inc/ocsserver.class.php:1878 Toolbox::sodiumDecrypt()
  ...ins/ocsinventoryng/inc/ocsserver.class.php:1860 PluginOcsinventoryngOcsServer::getDBocs()
  plugins/ocsinventoryng/inc/ocsserver.class.php:80  PluginOcsinventoryngOcsServer::checkOCSconnection()
  inc/commonglpi.class.php:339                       PluginOcsinventoryngOcsServer->getTabNameForItem()
  plugins/ocsinventoryng/inc/ocsserver.class.php:143 CommonGLPI->addStandardTab()
  inc/commonglpi.class.php:294                       PluginOcsinventoryngOcsServer->defineTabs()
  inc/commonglpi.class.php:859                       CommonGLPI->defineAllTabs()
  inc/commonglpi.class.php:1230                      CommonGLPI->showTabsContent()
  plugins/ocsinventoryng/front/ocsserver.form.php:73 CommonGLPI->display()

And with debug in glpi
![image](https://user-images.githubusercontent.com/16317786/97403251-632e5600-18f4-11eb-984c-7e2962993b99.png)

Same error by launching scripts/ocsng_fullsync.sh

**Comment by tsmr** [comment]
Hello Can you try to save the server configuration by resetting the password? (not change the password in mysql) - just add the password field & save the form glpi/plugins/ocsinventoryng/front/ocsserver.form.php?id=X

**Comment by tsmr** [comment]
& try this too : https://github.com/pluginsGLPI/ocsinventoryng/commit/a88a9f79581cf4bd0e7393d70bd554d80cfc6230

**Comment by Blank-Vcf** [comment]
> 
> 
> & try this too : [a88a9f7](https://github.com/pluginsGLPI/ocsinventoryng/commit/a88a9f79581cf4bd0e7393d70bd554d80cfc6230)

It's ok with the fix
empty password in mysql en set them again in gui > ok
Script seem working just a notice:

.PHP Deprecated:  Use DBmysql::affectedRows() in /var/www/inc/toolbox.class.php on line 634

**Comment by tsmr** [comment]
Cool 👍 
https://github.com/pluginsGLPI/ocsinventoryng/commit/ae9477b9ca8c9c709f6973491cb0d04b3d5ad1c1
