### ISSUE TITLE
secret key size should be SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_KEYBYTES

### ISSUE THREAD

**Issue by MidnightRAT** [pluginsGLPI/ocsinventoryng#260]
Fedora 31 x86_64
httpd-2.4.46-1.fc31.x86_64
php-fpm-7.3.23-1.fc31.x86_64
php-sodium-7.3.23-1.fc31.x86_64
GLPI 9.5.2
ocsinventoryng 1.7.1

Test not comlete ater update from 1.7.0

After fully reinstall 1.7.1 I can't add new ocsinventory server

`[2020-10-28 11:35:25] glpiphplog.CRITICAL:   *** Uncaught Exception SodiumException: secret key size should be SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_KEYBYTES bytes in /usr/share/glpi/inc/toolbox.class.php at line 273
  Backtrace :
  inc/toolbox.class.php:273                          sodium_crypto_aead_xchacha20poly1305_ietf_encrypt()
  ...ins/ocsinventoryng/inc/ocsserver.class.php:1648 Toolbox::sodiumEncrypt()
  inc/commondbtm.class.php:1102                      PluginOcsinventoryngOcsServer->prepareInputForAdd()
  plugins/ocsinventoryng/front/ocsserver.form.php:59 CommonDBTM->add()`

Thank You

**Comment by tsmr** [comment]
Please test with master version

https://github.com/pluginsGLPI/ocsinventoryng/archive/master.zip

**Comment by jpdenss** [comment]
It works with this version!! Thanks!

**Comment by tsmr** [comment]
👍

**Comment by jcervantes-sipecom** [comment]
Hi, I'm still having the same problem, and I use the link before the masted.zip:

![image](https://user-images.githubusercontent.com/56606032/97762699-574eb980-1ad7-11eb-8d60-23df4884d6fc.png)

![image](https://user-images.githubusercontent.com/56606032/97762744-81a07700-1ad7-11eb-8f7b-49e3ccdc81fe.png)

**Comment by jackburton79** [comment]
Did you try re-typing the password for the ocs database connection? That
worked for me.

Il ven 30 ott 2020, 23:51 jcervantes-sipecom <notifications@github.com> ha
scritto:

**Comment by jcervantes-sipecom** [comment]
Yes, I haven't added the database connection yet:
![image](https://user-images.githubusercontent.com/56606032/98067602-f4875600-1e27-11eb-83c1-a4649c41d7dc.png)

And when I try to configured from the begining:

![image](https://user-images.githubusercontent.com/56606032/98067713-2bf60280-1e28-11eb-8c67-fbe0cc29533a.png)

I cannot complete adding the database connection:
![image](https://user-images.githubusercontent.com/56606032/98067741-3ca67880-1e28-11eb-850d-b7647cbfcc18.png)

**Comment by chatoros** [comment]
https://github.com/pluginsGLPI/ocsinventoryng/issues/260?_pjax=%23js-repo-pjax-container#issuecomment-721498896
Same problem for me, its continue

**Comment by alifro81** [comment]
Hi,

I have the same problem

![image](https://user-images.githubusercontent.com/71875810/99407324-42539200-28ef-11eb-99db-2050fd7bd78a.png)

For now, the only solution I found is to create the OCS server without typing the password and then modify it (putting the password)

The most reliable thing would be that the problem is solved,

someone found a solution?
