### ISSUE TITLE
erreur import bitlockerStatus

### ISSUE THREAD

**Issue by GuillaumeFabre69** [pluginsGLPI/ocsinventoryng#262]
Plugin Version : 1.7.1
GLPI Version : 9.5.2
OCSREPORTS : Ocs Inventory Server 2.8

Bonjour,
j'ai l'erreur suivante lorsque j'importe un ordinateur avec le plugin bitlocker activé :
Undefined index: id in /var/www/glpi/plugins/ocsinventoryng/inc/bitlockerstatus.class.php at line 78
Undefined index: DISABLED in /var/www/glpi/plugins/ocsinventoryng/inc/bitlockerstatus.class.php at line 91
Undefined index: id in /var/www/glpi/plugins/ocsinventoryng/inc/bitlockerstatus.class.php at line 99
Column 'item_disks_id' cannot be null in query "INSERT INTO `glpi_plugin_ocsinventoryng_bitlockerstatuses` (`computers_id`, `item_disks_id`, `volume_type`, `protection_status`, `init_project`) VALUES ('11, NULL, '0', 'DISABLED', 'Faux')"

Le statut du chiffrement du volume n'est donc pas mis à jour dans GLPI.
Cordialement.
Guillaume

**Comment by tsmr** [comment]
https://github.com/pluginsGLPI/ocsinventoryng/releases/tag/1.7.3

**Comment by tanguydd** [comment]
Bonjour
J'ai la même erreur que le monsieur avec glpi 9.5.3 et ocsinventoryng 1.7.3. Je précise n'avoir activé l'option pour remonter le statut bitlocker qu’après la synchro initiale ocs/glpi
merci

**Comment by GuillaumeFabre69** [comment]
Hello ! It's NTFS FileSystem, I have this error for all the computers using Bitlocker in NTFS Filesystem.
I opened another issue for this problem with others informations https://github.com/pluginsGLPI/ocsinventoryng/issues/270
