### ISSUE TITLE
Clean installation GLPI 9.5.2+OCS Server 2.8+glpi ocsinventory plugin 1.7.1 cannot connect to OCS DB

### ISSUE THREAD

**Issue by conassabarbaro** [pluginsGLPI/ocsinventoryng#263]
hello all,

after a clean installation with all latest version of GLPI. OCS and GLPI plugin for OCS, when I try to add the OCS server it does not add the server to GLPI.

points to take in consideration:
-my ocsadmin (database user) has access to database (tested mysql -u ocsadmin -p ocsdb ok).

**Comment by CireSacud26** [comment]
Hello !

Same problem after migrating OCS plugin from 1.7.0 to 1.7.1 on GLPI 9.5.2. Link to OCS DB was OK with ocs plugin 1.7.0 but with "PHP User deprecated function (16384): Use sodiumDecrypt" error message.

With OCS plugin V1.7.1, no more DB connexion and these errors are shown : 
PHP User Warning (512): Unable to extract nonce from content. It may not have been crypted with sodium functions. in G:\inc\toolbox.class.php at line 293
PHP Warning (2): mysqli::real_connect(): (HY000/1045): Access denied for user 'ocs'@'pref26-sweb02.at.int' (using password: NO) in G:\inc\dbmysql.class.php at line 185
PHP User Warning (512): Unable to extract nonce from content. It may not have been crypted with sodium functions. in G:\inc\toolbox.class.php at line 293
PHP Warning (2): mysqli::real_connect(): (HY000/1045): Access denied for user 'ocs'@'pref26-sweb02.at.int' (using password: NO) in G:\inc\dbmysql.class.php at line 185

**Comment by zakharov69** [comment]
I have a same ploblem!

**Comment by liugang926** [comment]
I have a same ploblem!

**Comment by pallut** [comment]
Idem pour moi, je n'arrive pas à ajouter un serveur ocs. Pourtant mysql -u ocsadmin -p ocsdb et ok

**Comment by pallut** [comment]
En attendant, j'ai réinstallé le plugin 1.7.0 et l'ajout de serveur ocs fonctionne bien

**Comment by liugang926** [comment]
> En attendant, j'ai réinstallé le plugin 1.7.0 et l'ajout de serveur ocs fonctionne bien
Yes, I do this too; but 1.7.0 will have a problem, the software information cannot be imported into GLPI.

**Comment by pallut** [comment]
Effectivement, je ne peux consulter toutes les informations  que dans ocsreports, et pas dans GLPI.

**Comment by CireSacud26** [comment]
Still the same problem with OCS plugin 1.7.2 : DB connection with OCS server doesn't work.

**Comment by M3ph1570** [comment]
GLPI 9.5.3 and OCS 2.8 over Ubuntu Server 18.04, when i take save de config of the ocs inventory server it just giveme a blank page, doesn't save the config, i try it with version 1.7.1 and 1.7.0,  it add the config of ocs inventory server but when i try to import have the same problem with a blank page

**Comment by Eon9D** [comment]
https://github.com/pluginsGLPI/ocsinventoryng/releases

See v1.7.2

**Comment by tsmr** [comment]
https://github.com/pluginsGLPI/ocsinventoryng/releases/tag/1.7.3
