### ISSUE TITLE
GLPI 9.5.2 + OCS 2.8 Uncaught Exception SodiumException

### ISSUE THREAD

**Issue by kero7in** [pluginsGLPI/ocsinventoryng#264]
A fatal error comes out, the described fix does not help.
Uncaught Exception SodiumException: secret key size should be SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_KEYBYTES bytes in /var/www/glpi/inc/toolbox.class.php at line 273

**Comment by dondarb** [comment]
The same thing happens to me, I get the following error:

Uncaught Exception SodiumException: secret key size should be SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_KEYBYTES bytes in /var/www/html/inc/toolbox.class.php at line 273

and version 1.7.2 does not solve.

**Comment by hgpit** [comment]
Same problem with sodium here.

**Comment by GuillaumeFabre69** [comment]
Bonjour,
même problème pour moi en 1.7.2

**Comment by Eon9D** [comment]
Same as in here: #263 
Not a coder but found a way to make it work.

The official code from GLPI looks like this:

  263    public static function sodiumEncrypt($content, $key = null) {
  264       if ($key === null) {
  265          $key = self::getGlpiSecKey();
  266       }
  267 
  268       $nonce = random_bytes(SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES); // NONCE = Number to be used ONCE, for each message
  269       $encrypted = sodium_crypto_aead_xchacha20poly1305_ietf_encrypt(
  270          $content,
  271          $nonce,
  272          $nonce,
  273          $key
  274       );
  275       return base64_encode($nonce . $encrypted);
  276    }
  277 
  278    public static function sodiumDecrypt($content, $key = null) {
  279       if (empty($content)) {
  280          // Avoid sodium exception for blank content. Just return the null/empty value.
  281          return $content;
  282       }
  283       if ($key === null) {
  284          $key = self::getGlpiSecKey();
  285       }


Note how both functions have an "if" case if no key is given to the function.
The request the key themselfs but in the plugin it tries to give a key to the function.
So wenn need to remove GLPIKEY form ocsserver.class.php..

EDIT seems they are working on it and are aware of the issue:
https://github.com/pluginsGLPI/ocsinventoryng/commit/a88a9f79581cf4bd0e7393d70bd554d80cfc6230

**Comment by zakharov69** [comment]
I have a same problem. OCS 2.8.0.0 + GLPI 9.5.0

**Comment by hgpit** [comment]
We just upgraded the OCS plugin from 1.7.1 to 1.7.2, but this did not fix the issue.

Then I had a brainwave... I just went into the OCS plugin config (in GLPI) and saved the same OCS MySQL password over itself, and it fixed it!

Give that a try, folks :)

**Comment by dondarb** [comment]
> We just upgraded the OCS plugin from 1.7.1 to 1.7.2, but this did not fix the issue.
> 
> Then I had a brainwave... I just went into the OCS plugin config (in GLPI) and saved the same OCS MySQL password over itself, and it fixed it!
> 
> Give that a try, folks :)

over itself? 
Can you be more specific?
I tried even with the root user and it always comes out the same error.

**Comment by CireSacud26** [comment]
Hi

> 
> 
> We just upgraded the OCS plugin from 1.7.1 to 1.7.2, but this did not fix the issue.
> 
> Then I had a brainwave... I just went into the OCS plugin config (in GLPI) and saved the same OCS MySQL password over itself, and it fixed it!
> 
> Give that a try, folks :)

Hi !
I updated OCS plugin to version 1.7.2 too (GLPI 9.5.2) but i'm still unable to add a new OCS server.

If I try to add one OCS server with his database password, i've this error : Uncaught Exception SodiumException: secret key size should be SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_KEYBYTES bytes in ..\inc\toolbox.class.php at line 273

And the OCS server is not added.

If I try to add it without typing in the database password, it works ! The OCS server is added but... I'm unable to set the database connexion by setting the password : PHP Warning (2): mysqli::real_connect(): (HY000/2002): Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée. in ..\inc\dbmysql.class.php at line 185

Hope it helps to solve this issue.

Regards,
Eric

**Comment by tsmr** [comment]
https://github.com/pluginsGLPI/ocsinventoryng/releases/tag/1.7.3
