### ISSUE TITLE
Linked objects // No import: the plugin will not import these elements

### ISSUE THREAD

**Issue by StefanSa** [pluginsGLPI/ocsinventoryng#265]
Hi there,
I get the following warning in red on "Linked objects"
```
-No import: the plugin will not import these elements
-Global import: everything is imported but the material is globally managed (without duplicate)
-Unit import: everything is imported as it is
```
What do i have to do to import software and other linked objects?

GLPI Versio = 9.5.2
Plugin Version = 1.7.0

**Comment by tsmr** [comment]
see https://github.com/pluginsGLPI/ocsinventoryng/wiki/Nouvelle-installation-du-plugin
