### ISSUE TITLE
Unknown column 'softwarelicenses_id' in 'where clause'

### ISSUE THREAD

**Issue by Eon9D** [pluginsGLPI/ocsinventoryng#266]
glpisqllog.ERROR: DBmysql::query() in /var/www/helpdesk/inc/dbmysql.class.php line 306
  *** MySQL query error:
  SQL: SELECT `id` FROM `glpi_items_softwareversions` WHERE `items_id` = '417' AND `itemtype` = 'Computer' AND `softwarelicenses_id` = '10'
  Error: Unknown column 'softwarelicenses_id' in 'where clause'
  Backtrace :
  inc/dbmysqliterator.class.php:95                   
  inc/dbmysql.class.php:857                          DBmysqlIterator->execute()
  inc/commondbtm.class.php:343                       DBmysql->request()
  ...ins/ocsinventoryng/inc/officepack.class.php:102 CommonDBTM->getFromDBByCrit()
  plugins/ocsinventoryng/inc/software.class.php:270  PluginOcsinventoryngOfficepack::updateOfficePack()
  ...ns/ocsinventoryng/inc/ocsprocess.class.php:1299 PluginOcsinventoryngSoftware::updateSoftware()
  ...ins/ocsinventoryng/inc/ocsprocess.class.php:474 PluginOcsinventoryngOcsProcess::synchronizeComputer()
  ...s/ocsinventoryng/scripts/ocsng_fullsync.php:417 PluginOcsinventoryngOcsProcess::processComputer()
  ...s/ocsinventoryng/scripts/ocsng_fullsync.php:293 plugin_ocsinventoryng_importFromOcsServer()
  ...s/ocsinventoryng/scripts/ocsng_fullsync.php:179 SecondPass()
  {"user":"@srv1"} 

GLPI 9.5.2
OCS 1.7.1 / 1.7.2

  SQL: SELECT `id` FROM `glpi_items_softwareversions` WHERE `items_id` = '417' AND `itemtype` = 'Computer' AND `softwarelicenses_id` = '10'

In table glpi_items_softwareversions there is no softwarelicenses_id

**Comment by tsmr** [comment]
https://github.com/pluginsGLPI/ocsinventoryng/releases/tag/1.7.3
