### ISSUE TITLE
Problem installing OCSInventory

### ISSUE THREAD

**Issue by AhmedZa0ui** [pluginsGLPI/ocsinventoryng#268]
Hello guys;

I have installed OCSInventory to my GLPI 9.5.2 that i just managed to upgrade, The plugin was successfully installed but i couldn't configure it, any idea how to fix it ? 
PS : i'm a windows user 
Plugin version : 1.7.2
GLPI version : 9.5.2

Thanx a lot;

**Comment by massinlaaouaj** [comment]
Same problem, but in my case I installed into Linux Server

**Comment by chatoros** [comment]
file:inc/ocsserver.class.php
funcion prepareInputForAdd($input) i removed GLPIKEY on encrypt and works
* check release: https://github.com/pluginsGLPI/ocsinventoryng/compare/1.7.0...master

**Comment by tsmr** [comment]
you're right
https://github.com/pluginsGLPI/ocsinventoryng/commit/f55d16b93fd54fdcd47301f1356c2c6f4334c062

**Comment by tsmr** [comment]
https://github.com/pluginsGLPI/ocsinventoryng/releases/tag/1.7.3
