### ISSUE TITLE
404 Not found error after installation

### ISSUE THREAD

**Issue by gattancha** [pluginsGLPI/ocsinventoryng#272]
Just done a clean installation of GPLI (v 9.5.3) and cloned the current code (v 1.7.3)
The plugin appears in GLPI and I can install it and enable it

![image](https://user-images.githubusercontent.com/19567119/102719957-01351000-42e9-11eb-8144-be50901c3db2.png)

But that is as far as I can get.. when I try to configure it, I get a 404 Not Found error at https://myglpliserver/plugins/ocsinventoryng/front/config.php

I'm running CentOS 8 with PHP 7.3,
I've even made sure Apache is the owner of the ocsinventoryng plugin folder and files , but to no effect

If anyone knows the solution to this I would be very grateful

**Comment by tsmr** [comment]
Hello
I think the problem is that you have OCS Server installation on same server than GLPI : 
https://github.com/pluginsGLPI/ocsinventoryng/wiki/Forbidden-problem-%28with-OCS-Server-2.2%29

**Comment by gattancha** [comment]
Thank for the reply, 
I tried changing my config file, but it had no effect, I will, however, try installing GLPI on a separate server to rule it out.
