### ISSUE TITLE
Default Status missing

### ISSUE THREAD

**Issue by lib-dbr** [pluginsGLPI/ocsinventoryng#277]
Dear GLPi user.

For bug reports, you can open an issue here, provide us : 
- The version of the plugin. 1.7.3
- The version of your GLPI. 9.5.1
- The steps to reproduce your issue. Tools --> OCSInventoryNG--> Import Options

Hello, I have setup a small instance of GLPI with OCSNG and have successfully configured automatic imports of 300 machines into GLPI. In the [Wiki](https://github.com/pluginsGLPI/ocsinventoryng/wiki/New-installation#import-options-), there lists the setting "Default Status". My instance does not show this setting. Has it been removed and the documentation is outdated?

If it has been removed, is there a way to set the glpi status on import?

thank you.

**Comment by tsmr** [comment]
Hello the wiki is outdated :
https://github.com/pluginsGLPI/ocsinventoryng/issues/236
