### ISSUE TITLE
Error to synchronize computers already imported 

### ISSUE THREAD

**Issue by allan-altair** [pluginsGLPI/ocsinventoryng#285]
- The version of the plugin. **1.7.3**
- The version of your GLPI. **9.5.4**
- The steps to reproduce your issue.

After upgrading the GPLI 9.5.2 to 9.5.4 and the OCS Inventory plugin 1.7.0 to 1.7.3, when synchronize computers already imported in the debug mode show the message below:

**PHP Notice (8): Undefined index: max_glpidate in glpi/plugins/ocsinventoryng/inc/ocsserver.class.php at line 2221**

**Comment by Nix-adm** [comment]
After upgrading from GPLI 9.4.6 to 9.5.3 and upgrade the OCS Inventory plugin to 1.7.3.
The synchronization   has ceased functioning.
Error logs : 

PHP Notice:  Undefined index: COMPUTERS in ocsng_fullsync.php on line 221
PHP Warning:  count(): Parameter must be an array or an object that implements Countable in ocsng_fullsync.php on line 221

Thanks for help

**Comment by abonanni** [comment]
Hello,
You can test my pull request : https://github.com/pluginsGLPI/ocsinventoryng/pull/294

**Comment by Flix886** [comment]
Hello,

done succesfully, but now i get no longer infomation like software, OS and components. It is only th asset with serialnumber.


![2021-06-04 13_54_01-GLPI - Computer - 1191](https://user-images.githubusercontent.com/85347568/120797483-63eb3280-c53c-11eb-869f-9edfd81e9127.png)


![2021-06-04 13_50_31-GLPI - Computer - 1191](https://user-images.githubusercontent.com/85347568/120797221-048d2280-c53c-11eb-810e-7b22600dfd81.png)

**Comment by Flix886** [comment]
Hi, problem is solved. It works now but don`t ask me why :D

**Comment by allan-altair** [comment]
Hello @abonanni,

I upgraded my plugin for the version that you mentioned, but I have the same problem.

**PHP Notice (8): Undefined index: max_glpidate in glpi/plugins/ocsinventoryng/inc/ocsserver.class.php at line 2221**

Thanks in advance

**Comment by allan-altair** [comment]
Hello @abonanni,

I upgraded my plugin for the version that you mentioned, but I have the same problem.

**PHP Notice (8): Undefined index: max_glpidate in glpi/plugins/ocsinventoryng/inc/ocsserver.class.php at line 2221**

Thanks in advance

**Comment by abonanni** [comment]
Hello @allan-altair 

My commit solve "PHP Notice: Undefined index: COMPUTERS in ocsng_fullsync.php on line 221" problem but not "Undefined index: max_glpidate".

Without copy of your database it will be hard to debug.

**Comment by allan-altair** [comment]
@abonanni,

Can I send to you a link to download my database using the email on your website?

**Comment by allan-altair** [comment]
@abonanni

How can I share my database with you?

**Comment by Nix-adm** [comment]
My workaround is change 'archive' fields from null to '0' in ocs database.
I started with a test from only four servers.
