### ISSUE TITLE
Exit code is 4 => Failed to talk with Communication Server

### ISSUE THREAD

**Issue by Giulio-N** [pluginsGLPI/ocsinventoryng#297]
Hi!

I installed OCS Inventory NG Agent 2.8.0.1

Service encounter error <OCS Inventory Agent encounter an error (exit code is 4 => Failed to talk with Communication Server)>.
And after:
Service encounter error <Failed to load/parse last inventory state>.

**Comment by tsmr** [comment]
Sorry
It's a OCS problem not from the plugin
