### ISSUE TITLE
Added some IPDISCOVER functionalities to ocsinventoryng

### ISSUE THREAD

**Issue by chrismako** [pluginsGLPI/ocsinventoryng#30]
GOAL : 

imported some functionalities from OCSServer ocsreports  :
- display information about subnets (name, hardware on those subnets)
- modify or identify subnets
- import and identify one or multiple hardware of the subnets in GLPI

Done : 
- displaying the information about the subnet
- import and identify hardware in glpi
- edit subnet information

menu : 
![ipdisc](https://cloud.githubusercontent.com/assets/20395852/18009693/aef357aa-6bad-11e6-8421-382f7286ca53.PNG)

display subnet informations:
![ipdisc1](https://cloud.githubusercontent.com/assets/20395852/18009747/e9d574f2-6bad-11e6-8ee6-9ecfa3d9a3ab.PNG)

**Comment by tsmr** [comment]
TODO : 
Add link for existing objects
hook - redirect
hook - simpleform SNMP
CHMA Comments
Add list subnet + form from Subnet list
