### ISSUE TITLE
Plugin Ocs Inventory not acquiring memory from OCS server from machines manualy imported

### ISSUE THREAD

**Issue by fgendorf** [pluginsGLPI/ocsinventoryng#31]
Hi, I had imported 5 machines manually in OCS server, when I went do sync with GLPI almost data is ok, but the memory.
It appear in computer details from OCS reports, however in GLPI the memories is not present.

How can I DEBUG plugin to see what it consulting from OCS Server database?

Thanks from advanced

**Comment by tsmr** [comment]
Can you give your versions of glpi, OCS, and plugin OCS ?

**Comment by fgendorf** [comment]
Hi,
GLPI 0.9.5
OCS 2.1
OCS Plugin 1.2.3

Just 5 machines, that was manually imported have this problem.



_________________________
Frederico Gendorf

**Comment by tsmr** [comment]
You don't use the release version ?

Have you select memory into OCS Server setup import into the plugin ?
