### ISSUE TITLE
No database connection between OCS & GLPI

### ISSUE THREAD

**Issue by Demonheart** [pluginsGLPI/ocsinventoryng#312]
- Debian 10.2.1-6
- Plugin version 2.0.0-rc1
- GLPI version 10.0.0-rc1

I got "Database connection failure" when I try to configure the server.

![ocsng](https://user-images.githubusercontent.com/1001730/154701623-60010a7b-1160-4166-9460-f0acdc78ea4e.jpg)

**Comment by Demonheart** [comment]
Debug say:
`PHP Warning (2): mysqli::real_connect(): (HY000/1045): Access denied for user 'adminocs'@'localhost' (using password: NO) in /var/www/glpi/src/DBmysql.php at line 240`

Have you a solution ?

**Comment by ajavor** [comment]
Have you set TRACE_DELETED = ON on the OCS server side? 

![obraz](https://user-images.githubusercontent.com/32665748/155484419-c073fae4-e937-4716-a65d-4b66c068718b.png)

**Comment by mitol007** [comment]
I confirm the problem on GLPI 10.0.0-rc1, OCS 2.9.2 and plugin ocsinventoryng-2.0.0-rc2.

**Comment by kinfra-vaultwarden** [comment]
Hello, 

Debian 11.2
php 7.4
glpi 10.0.0-rc2
ocsinventory NG 2.0.0-rc2

Same problem here. The is no value for ocs_db_passwd in the glpi_plugin_ocsinventoryng_ocsservers glpi table. 
![image](https://user-images.githubusercontent.com/93642011/157328197-7a6e7ae3-5f7d-4dd7-9ceb-9085fcce9290.png)

Probably link to this PHP warning : 
![image](https://user-images.githubusercontent.com/93642011/157328415-8de0aa39-92dd-48a8-be2e-81ad55f164da.png)

**Comment by rgonzalezmas** [comment]
Hello,

See  inc/ocsserver.class.php file, at **prepareInputForUpdate($input)**
I've changed encrypt instead decrypt, and the connection is done... 
Anybody can't explain this missmatch? A code error...?

```
 function prepareInputForUpdate($input){

      $adm = new PluginOcsinventoryngOcsAdminInfosLink();
      $adm->updateAdminInfo($input);
      if (isset($input["ocs_db_passwd"]) && !empty($input["ocs_db_passwd"])) {
         $input["ocs_db_passwd"] = rawurlencode(stripslashes($input["ocs_db_passwd"]));
        //$input["ocs_db_passwd"] = (new GLPIKey())->decrypt(stripslashes($input["ocs_db_passwd"]));
        $input["ocs_db_passwd"] = (new GLPIKey())->encrypt(stripslashes($input["ocs_db_passwd"]));
      } else {
         unset($input["ocs_db_passwd"]);
      }

      if (isset($input["_blank_passwd"]) && $input["_blank_passwd"]) {
              $input['ocs_db_passwd'] = '';
      }

      return $input;
   }
```

After this change , I am able to run the plugin on glpi 10 version and import the OCS computers into glpi asset manager

regards.

**Comment by tsmr** [comment]
Thanks [rgonzalezmas](https://github.com/rgonzalezmas) - good game 👍
