### ISSUE TITLE
Automatic import doesn't import anything

### ISSUE THREAD

**Issue by thenamelessthing** [pluginsGLPI/ocsinventoryng#316]
For bug reports, you can open an issue here, provide us : 
- Plugin 1.7.3
- GLPI 9.5.5
- OCS 2.9.0

After initial import of all computer I setup the automatic action to run every 5 min. In the task log I see the task run successfully.
But newly added computer in OCS are not imported into GLPI.

![image](https://user-images.githubusercontent.com/10235448/159005707-e5bef647-c992-45bc-b286-2fd1a14c9c20.png)

![image](https://user-images.githubusercontent.com/10235448/159005758-06bc01aa-7097-4ec9-86a1-e45ee826b434.png)

If I do an import manually, I can see the newly added computer from OCS.

![image](https://user-images.githubusercontent.com/10235448/159006028-ff56425f-5c00-4b30-8a2c-d813eee822c3.png)

**Comment by tsmr** [comment]
The automatic task ocsng is launched only if server is not in expert mode
The automatic task ocsng only synchronize existant computers, it doesn't import new computers
If you want to import new computers, disable this parameter, change to expert mode and use script from system

https://github.com/pluginsGLPI/ocsinventoryng/wiki/Massive-import---Expert-Mode

**Comment by thenamelessthing** [comment]
In expert mode same problem.  I have enabled the debug and now I see these error:

![image](https://user-images.githubusercontent.com/10235448/159016678-2ace4e38-74ee-4d98-8735-bbd325f59987.png)

**Comment by tsmr** [comment]
Try with last https://github.com/pluginsGLPI/ocsinventoryng/archive/refs/heads/9.5/bugfixes.zip

Verify your user / password to access ocs database

**Comment by thenamelessthing** [comment]
Thank you, we are progressing!

![image](https://user-images.githubusercontent.com/10235448/159023390-6748b703-52c0-474d-a827-b02d87b6b6e4.png)

Now I notice that this task doesn't seem to sync existing computers. I don't see the changes going up in GLPI, for example software that is no longer inventoried on a workstation is still visible in GLPI.

**Comment by thenamelessthing** [comment]
The  --thread_nbr=  option mean the number of process for the sync task or the number of computer synced for the task?

**Comment by tsmr** [comment]
The --thread_nbr= option mean the number of process for the sync task

**Comment by thenamelessthing** [comment]
@tsmr do you have any idea where I could check, to understand why the sync is not working even though I no longer have an error when running the script?

Je parle français aussi si c'est plus simple pour toi.

**Comment by tsmr** [comment]
Cela est censé synchroniser aussi les pcs.
Mais cela dépends du checksum coté OCS. Si tu forces l'import complet, il devrait mettre à jour les logiciels normalement

**Comment by thenamelessthing** [comment]
Si je vais dans la fiche de l'ordinateur et que je clique sur "Launch synchroniszation" tout ce met à jour.

Cependant, si je lance le script ocsng_fullsync.sh il ne se passe rien. La tâche roule quelques secondes sans plus et aucune erreur visible..

**Comment by thenamelessthing** [comment]
Si je lance la synchro manuellement par l'interface web de GLPI tout fonctionne. Si j'utilise le script sa roule quelques secondes et il n'y a aucune erreur. C'est comme si le script ne sélectionnait pas aucun ordinateur à synchroniser...

**Comment by thenamelessthing** [comment]
Autre élément que je ne comprend pas, dans la documentation du mode expert. C'est indiqué qu'on pouvait suivre en temps réel l'exécution.

![image](https://user-images.githubusercontent.com/10235448/159054604-33570be8-1209-433c-b389-6f241575154c.png)


Mais je n'ai pas de lien vers ce plugin..
![image](https://user-images.githubusercontent.com/10235448/159054985-fc046042-cba7-4c42-9c7f-7d85b9ef8453.png)

**Comment by tsmr** [comment]
Outils > OCS Inventory NG
![image](https://user-images.githubusercontent.com/13178158/159058127-e3214296-60c6-4473-bac3-602461e04725.png)

**Comment by thenamelessthing** [comment]
Je n'ai pas cette option et j'ai fait le tour de pas mal tout les menus de l'interface... Je ne retrouve pas cette option.

![msedge_2022-03-18_14-05-14](https://user-images.githubusercontent.com/10235448/159059048-e67f6af0-8001-4ddb-bc4e-58c3f9610db2.gif)

**Comment by tsmr** [comment]
Dans la configuration du serveur : 
![image](https://user-images.githubusercontent.com/13178158/159114961-5e2a6b71-d4b3-41ed-9ab5-a8ad46e6fb91.png)

**Comment by thenamelessthing** [comment]
Oulà! Je me sens vraiment Noob d'être passer à côté de ça!  Un énorme merci pour ton aide. J'espère que ce ticket pourra être utile à d'autres.

**Comment by thenamelessthing** [comment]
Je me répond à moi-même, il faut que la tâche cron soit fait à partir du compte root.

**Comment by tsmr** [comment]
![image](https://user-images.githubusercontent.com/13178158/159297156-0a793d7d-f411-4e09-a67e-f839f5714554.png)

**Comment by thenamelessthing** [comment]
ok, j'imagine que si j'active ce paramètre. Je dois indiquer d'une quelconque façon une "règle ou une action" qui indique que lorsque l'état "décomissionner" est choisi alors exécute "utiliser l'action automatique de nettoyage des agents & suppression depuis OCSNG"..???
