### ISSUE TITLE
Network Interfaces IP not imports from OCS server

### ISSUE THREAD

**Issue by ZakhariyaV** [pluginsGLPI/ocsinventoryng#321]
- The version of the plugin: 2.0.0
- The version of your GLPI: [GLPI 10.0.0]
- The steps to reproduce your issue:
1. Impoort or update (full sync) the PC to OCS server 
in OCS IP address presist for the network interface  of the PC
in GLPI IP address is not presist for the network interface of the PC

**Comment by ZakhariyaV** [comment]
![scr1](https://user-images.githubusercontent.com/104997977/167011204-461e855a-c0c9-4d32-9acb-c632671f1d89.png)
![scr2](https://user-images.githubusercontent.com/104997977/167011075-5a3859e4-ba96-4bc1-b515-c600b2a7c59e.png)

**Comment by ZakhariyaV** [comment]
Hi gues.
Can any one reply about this problem?
Before glpi and OCS inventory plugin upgrading, all workd fine.
At this time after full sync IP not syncyng and i recive blank feild instead of IP addres the computer from OCS server.
Please help to fix this problem.

**Comment by Muzo18** [comment]
Hello,

I've got the same Issue.

Plugin version : 2.0.4
GLPI Version : 10.0.5

Since the upgrade from GLPI 9.5.7 to 10.0.5, and OCS plugin from 2.0.3 to 2.0.4, all the links between GLPI computer and OCS were broken.
Now, when I link a computer, the "network port" is deleted and not recreated.

Anyone can help me ?

Thanks

**Comment by ZakhariyaV** [comment]
Are any bodey is faced this problem? How did you solved it?

**Comment by ZakhariyaV** [comment]
Without waiting for an answer, I have solved the issue.
The problem was in use 32 bit OS. When I migrated GLPI to Ubuntu x64 the problem has been solved.

**Comment by Muzo18** [comment]
ZakhariyaV,

My GLPI is running on Ubuntu x64 and I have the problem.
You solve it with the migration process, but the problem still exist when you update the system.
You close the issue, but you shouldn't have.

Bye

**Comment by ZakhariyaV** [comment]
Hi Muzo18!
When I  tried to upgrade my GLPI and php on x32 OS (Debian), i was got a notification that 32 bit php restrictions. And I supposed it with my problem
I installed Ubuntu 22.04 with LAMP server, then migrate glpi directory and SQL dump from x32 instance. 
After that steps IP addresses sync from OCS works fine.
