### ISSUE TITLE
Pas d'option "statut par defaut"  dans la conf du plugin 

### ISSUE THREAD

**Issue by jlb5980** [pluginsGLPI/ocsinventoryng#323]
Bonjour
Dans la configuration du plugin 1.7.3  il n'y a pas de trace de l'option "statut par defaut "  .
Contrairement au version plus ancienne .
Cette option était bien pratique pour donner un statut par exemple "actif"  aux nouvelles machines remontées. 

Version glpi : glpi 956
Cordialement

**Comment by tsmr** [comment]
https://github.com/pluginsGLPI/ocsinventoryng/issues/236
