### ISSUE TITLE
Rule to assign entity is not working

### ISSUE THREAD

**Issue by Dionizioaf** [pluginsGLPI/ocsinventoryng#333]
- The version of the plugin: 2.0.2
- The version of your GLPI: 10.0.3
- The version of OCS Reports: 2.9.2
- The steps to reproduce your issue.

Its a new install, we connect about 150 computers in ocsreports and configure GLPI with OCS integration, its working just fine, but the Rule for entities don't work.
I configure the Rule and run the import and it always mark the computer as root, i'm already placing the new Rule above Root Rule.
If the new rule I use the criteria that the source is OCS it works, but when i place some additional criteria like IP Address and domain is doesn't work.

I tried with PHP command in the shell and in the web interface, and its the same

**Comment by tsmr** [comment]
Please try with master version ? https://github.com/pluginsGLPI/ocsinventoryng/archive/refs/heads/master.zip

**Comment by tsmr** [comment]
fixed in 2.0.4
