### ISSUE TITLE
Plugin Errors : Problème d'importation du parc informatique 

### ISSUE THREAD

**Issue by Chaniac** [pluginsGLPI/ocsinventoryng#335]
- The version of the plugin : 2.0.2
- The version of your GLPI : GLPI 10.0.3
- The steps to reproduce your issue : Mise à jour du plugin OCS Inventory de la version 2.0.1 à 2.0.2 puis resynchronisation du parc...

Voici l'erreur que j'obtiens :

![image](https://user-images.githubusercontent.com/57410982/198576570-ef34906d-f345-4d2e-a4bc-cae1eba03853.png)

**Comment by Chaniac** [comment]
![image](https://user-images.githubusercontent.com/57410982/199933228-3770d0a7-4b44-47b2-bdfb-16c194832163.png)
de nouveau une erreur

**Comment by Chaniac** [comment]
cette fois :

The version of the plugin : 2.0.3
The version of your GLPI : GLPI 10.0.3
The steps to reproduce your issue : Mise à jour du plugin OCS Inventory de la version 2.0.1 à 2.0.2 puis resynchronisation du parc...

**Comment by MrYsson** [comment]
Bonjour,
Nous avons le même problème (en 2.0.2) et j'ai donc regardé comment corriger ce comportement.
J'ai commenté sur l'issue #325 (en anglais) ce qui doit être changé en version 2.0.1 et 2.0.2. Pour la version 2.0.3, ce sont les lignes 1342 et 1344.
Si besoin, je peux traduire mes explications vers le français.
