### ISSUE TITLE
Php warning after GLPI upgrade from 9.5.7 to 9.5.11

### ISSUE THREAD

**Issue by CireSacud26** [pluginsGLPI/ocsinventoryng#339]
Hello,

- The version of the plugin : 1.7.3
- The version of your GLPI : 9.5.11
- The steps to reproduce your issue : After upgrade of GLPI from 9.5.7 to 9.5.11 the following red warning is diplayed on all GLPI pages only for super-admin accounts.

`PHP Warning (2): Declaration of PluginOcsinventoryngTeamviewer::generateLinkContents($link, CommonDBTM $item) should be compatible with CommonDBTM::generateLinkContents($link, CommonDBTM $item, bool $safe_url = true) in .\plugins\ocsinventoryng\inc\teamviewer.class.php at line 326`

Thanks for helping to remove this.

Regards,
Eric

**Comment by tsmr** [comment]
Replace into inc\teamviewer.class.php by

```
/**
    * @param string     $link
    * @param CommonDBTM $item
    *
    * @return array
    */
   public static function generateLinkContents($link, CommonDBTM $item, bool $safe_url = true) {

      if (strstr($link, "[TWID]")) {
         $link = str_replace("[TWID]", $item->fields['twid'], $link);
         return [$link];
      }

      return parent::generateLinkContents($link, $item);
   }
```

**Comment by CireSacud26** [comment]
Hi tsmr !

Quick and nice fix. It works now like a charm !

Thanks !
