### ISSUE TITLE
SNMP Import

### ISSUE THREAD

**Issue by dwtz** [pluginsGLPI/ocsinventoryng#35]
Do i need a new rule for snmp import? I can browse all snmp devices but could not import it.
Message: SNMP objects not imported. Inventory and ipdiscover import is working fine.

**Comment by tsmr** [comment]
Thanks. No rule are necessary for SNMP Import at this time. Have you glpi/files/_log/php-errors or sql-errors ?

**Comment by dwtz** [comment]
Attached both log files.
Errors are shown during install (but only in log file).
No errors are logged during snmp import.

[Archiv.zip](https://github.com/pluginsGLPI/ocsinventoryng/files/454606/Archiv.zip)

**Comment by tsmr** [comment]
There are only errors of connection to an OCS Server. Have you setup server fo choice which fields are imported ? Import or link SNMP ? Versions of GLPI / OCS ?

**Comment by dwtz** [comment]
GLPI 0.90.5 (new test Install, empty data)
OCS version 2.2 but don´t no where to find  exact version. Last entry in Changelog 2.2RC
Attached some screenshots.

![database connection](https://cloud.githubusercontent.com/assets/21999928/18242954/09141320-7359-11e6-9fd2-56ad8c7f33c9.png)
![example device](https://cloud.githubusercontent.com/assets/21999928/18242955/0927f96c-7359-11e6-9757-fda0ea78ea36.png)
![not imported](https://cloud.githubusercontent.com/assets/21999928/18242957/094574b0-7359-11e6-83ce-724016890270.png)
![snmp import options](https://cloud.githubusercontent.com/assets/21999928/18242956/09388e62-7359-11e6-8898-cd3ebc7a9a42.png)

**Comment by tsmr** [comment]
What do you test to import ? Computer ? Network Equipment ?

**Comment by dwtz** [comment]
maybe I do something wrong.
If i create an new object for example network object AKCP sensorProbe4 and link it using "Link SNMP devices to existing GLPI objects" snmp data is imported.

If i press button "Import new SNMP devices" all my snmp devices are shown.
Now i choose for example Oki Printer.

![snmp import options](https://cloud.githubusercontent.com/assets/21999928/18243964/f13662f8-735d-11e6-95ef-dd2002317f47.png)

and start import. But import of device failed.
I had expected to see the new device in printer list.
Is it possible to map the object to asset using "Import new SNMP devices"?

**Comment by dwtz** [comment]
Item type to create is a table. but i can´t choose a type there. is it ok?

**Comment by tsmr** [comment]
I've do some fixes. Can you try by download master again & test ?

**Comment by tsmr** [comment]
I've do some fixes. Can you try by download master again & test ?

**Comment by dwtz** [comment]
yeah it is working now :-)
thanks for great support.

**Comment by tsmr** [comment]
ok cool ;)
