### ISSUE TITLE
glpi see the computers of ocs but fail the import

### ISSUE THREAD

**Issue by pperera611** [pluginsGLPI/ocsinventoryng#38]
When i push import new computers the system show me the computers, but when i selected import the system fail. 
Log glpi in apache2:

 PHP Fatal error:  Uncaught Error: Class 'UNKNOWN' not found in /var/www/glpi/plugins/ocsinventoryng/inc/ocsserver.class.php:2018\nStack trace:\n

#0 /var/www/glpi/plugins/ocsinventoryng/inc/ocsserver.class.php(2180): PluginOcsinventoryngOcsServer::getComputerInformations(Array, Array, '0', '0')\n

#1 /var/www/glpi/plugins/ocsinventoryng/inc/ocsserver.class.php(1788): PluginOcsinventoryngOcsServer::importComputer(2, '1', 0, '0', '0')\

n#2 /var/www/glpi/plugins/ocsinventoryng/front/ocsng.import.php(73): PluginOcsinventoryngOcsServer::processComputer(2, '1', 0, '0', $0, '0', '0')\n

#3 {main}\n  thrown in /var/www/glpi/plugins/ocsinventoryng/inc/ocsserver.class.php on line 2018, referer: http://glpi.anp.com.uy/plugins/ocsinventoryng/front/ocsng.import.php

![1](https://cloud.githubusercontent.com/assets/8573652/18281719/5527a78c-7434-11e6-90b5-67c85de3965b.png)

when push import....nothing...
![2](https://cloud.githubusercontent.com/assets/8573652/18281724/588c5008-7434-11e6-9f14-bd77a20523d3.png)

i m speak spanish, sorry for my english

Regards

**Comment by pperera611** [comment]
I forget:
glpi version: 0.90.5
plugin version: 1.2.3
ocs server : 2.2.1

**Comment by tsmr** [comment]
Can you give me full trace log into glpi/files/_log/php-errors or sql-erros please ?

**Comment by pperera611** [comment]
Hi!
Attach file with both logs
[log_php_and_sql.txt](https://github.com/pluginsGLPI/ocsinventoryng/files/457430/log_php_and_sql.txt)

Thanks for your help

**Comment by tsmr** [comment]
First thing : you have SQL errors because you have only_full_group_by on sql_mode into your mysql config file. Please remove it. 
For your problem with OCS, you don't have setup import informations, so you have errors.

I will also fix errors

**Comment by pperera611** [comment]
Ok, i update the my.cnf. 
I dont understand what do you mean about ocs.
I will wait the fix errors.
Regards

**Comment by tsmr** [comment]
I have fix errors but you must setup your OCS server into plugin with select informations to import : 

![image](https://cloud.githubusercontent.com/assets/13178158/18288036/03c72660-747a-11e6-9b73-2b0fd88c64ec.png)

**Comment by pperera611** [comment]
Hi. I already had set it

![image](https://cloud.githubusercontent.com/assets/8573652/18288187/b70ecd6a-7450-11e6-8793-9b6948d44766.png)

**Comment by tsmr** [comment]
Can you test with last master ?

**Comment by pperera611** [comment]
Yes. Today download the latest version of the master

**Comment by tsmr** [comment]
But download now (with my fixes) & test :+1:

**Comment by pperera611** [comment]
Previously i downloaded the version 1.2.2 and 1.2.1 and dont works for me. With the 1.2.3 at least recognizes computers from ocs.

Ok, Test and tell you

**Comment by pperera611** [comment]
it work!!! thanks for your help!!!

**Comment by tsmr** [comment]
;)
Warning, the 1.2.3 version is not released
I close thread
