### ISSUE TITLE
Failed to install plugin

### ISSUE THREAD

**Issue by Gabo8611** [pluginsGLPI/ocsinventoryng#40]
OCS Inventory NG	v1.2.2
glpi v9.1
Messages:
Error during the database query: INSERT INTO `glpi_notificationtemplates`...
and 
Error during the database query: INSERT INTO `glpi_notifications`...
no match column count.
Correct line 970 and 993 of hook.php file
Suggestion
Add value NULL
Regards

**Comment by tsmr** [comment]
Fixed this this commit : https://github.com/pluginsGLPI/ocsinventoryng/commit/d4c3c71fabb618dbf545f2b48a23a5c3d4861b5a
