### ISSUE TITLE
Not imported network ports

### ISSUE THREAD

**Issue by Krakozaber** [pluginsGLPI/ocsinventoryng#43]
When you import new devices are not imported network ports

**Comment by tsmr** [comment]
Can you give more informations please ?
Version of GLPI & OCS & Plugin
Setup of the plugin..

**Comment by Krakozaber** [comment]
GLPI 9.1, Plugin 1.2.3, OCS 2.2.1

**Comment by tsmr** [comment]
It's a bug of GLPI : 
https://github.com/glpi-project/glpi/pull/1069/files

Corrected for next version of GLPI

**Comment by Krakozaber** [comment]
Thx, this fix help.
