### ISSUE TITLE
Invalid OCSNG configuration (TRACE_DELETED must be active)

### ISSUE THREAD

**Issue by Lud3rik** [pluginsGLPI/ocsinventoryng#44]
Hello,

I have some issues with the plugin ocsinventory for GLPI.
When I want to connect to the database, I see a message like "Invalid OCSNG configuration (TRACE_DELETED must be active)".

So after searching on the internet, I read that I need to turn it on by using OCS.
But I don't see any manner to turn it on by the plugin.

GLPI Version : 0.90.5
GLPI Ocsinventory version : 1.2.1

Thank you for helping

**Comment by tsmr** [comment]
Le 06.10.2016 17:41, Lud3rik a écrit : 

> Hello, 
> 
> I have some
issues with the plugin ocsinventory for GLPI.
> When I want to connect
to the database, I see a message like "Invalid OCSNG configuration
(TRACE_DELETED must be active)". 
> 
> So after searching on the
internet, I read that I need to turn it on by using OCS.
> But I don't
see any manner to turn it on by the plugin. 
> 
> GLPI Version :
0.90.5
> GLPI Ocsinventory version : 1.2.1 
> 
> Thank you for helping

> 
> --
> You are receiving this because you are subscribed to this
thread.
> Reply to this email directly, view it on GitHub [1], or mute
the thread [2].

You must turn on into OCS web interface 

See attached

-- 

Tsmr
Xavier CAILLAUD
 

Links:
------
[1]
https://github.com/pluginsGLPI/ocsinventoryng/issues/44
[2]

**Comment by heartttz** [comment]
I have same problem. I can't find TRACE_DELETED.

**Comment by tsmr** [comment]
see .png 
https://cloud.githubusercontent.com/assets/13178158/19161239/4d734f2e-8bf3-11e6-841a-772524d04552.png

**Comment by Lud3rik** [comment]
Hello,

In fact, my real problem is that I don't know how to reach the website which displays this image.
Can you explain me where I need to click?

Thank you

**Comment by tsmr** [comment]
On your OCS server : example : http://localhost/ocsreports

**Comment by Lud3rik** [comment]
Ok thank you. I will install the server and configure it.

**Comment by heartttz** [comment]
Thank you very much. I'm done. lol
