### ISSUE TITLE
Cant import inventory

### ISSUE THREAD

**Issue by riassuncao** [pluginsGLPI/ocsinventoryng#45]
Hi guys.
I'm facing this problem: we have GLPI 9.1 and OCS plugin 1.2.3 on our test server.
The OCS Server isn’t in the same server of GLPI but I have configured the conexion, and when I test the conexion is ok.
But I cant import inventory.
When I checked the plugin code, step by step, I realized that the problem is in this line:

if (isset($_SESSION["ocs_import"]["id"])) {

$_Session["ocs_import"]["id"] is always evaluated to null and I cant find out where this session variable is seted.
Any ideas?
Sorry about english.﻿

**Comment by tsmr** [comment]
What have you setup into plugin ? Datas to imported, Importation options, Rules ?

**Comment by riassuncao** [comment]
![image](https://cloud.githubusercontent.com/assets/22745213/19243521/543bdf12-8eee-11e6-9153-753a4f64b217.png)

**Comment by riassuncao** [comment]
![image](https://cloud.githubusercontent.com/assets/22745213/19243549/65970854-8eee-11e6-8027-547296036bbf.png)

**Comment by riassuncao** [comment]
![image](https://cloud.githubusercontent.com/assets/22745213/19243563/7177cec4-8eee-11e6-9347-a33b4b3b5ba4.png)

**Comment by riassuncao** [comment]
"Sim" means "yes" and "não" means "no"
