### ISSUE TITLE
Drive volume not sync 

### ISSUE THREAD

**Issue by jgosse** [pluginsGLPI/ocsinventoryng#46]
hi ,
i have a problem when sync computer , The synchronization of volumes (free space and used) are not syncing . Volumes ( spaced and use) first import is ok but is not synchronize other times .
an idea ?
GLPI 9.1 / plugin OCSinventory NG 1.2.3

**Comment by tsmr** [comment]
The plugin change volumes if total size change or variation of 5% of space

**Comment by tsmr** [comment]
any news ?
