### ISSUE TITLE
GLPI 9.1 + OCS Inventory NG 1.2.3: no data after import computers

### ISSUE THREAD

**Issue by Darkentik** [pluginsGLPI/ocsinventoryng#54]
Hi there!
I´m using GLPI 9.1 with the plugin OCS Inventory NG 1.2.3
I can import computers from OCS and see them in the GLPI at "Inventory->Computers" but they have no data like software or any hardware devices.
I looked at the OCS there is all as it should be. The computers have information about all hardware devices and installed software.
Look:
URL: http://srv-intranet/ocsreports/index.php
Computers:
![ocs_computers](https://cloud.githubusercontent.com/assets/9421857/20213635/e66b3566-a809-11e6-8fb4-c4505486eae8.png)
Hard Disks from my notebook:
![ocs_computer_disks](https://cloud.githubusercontent.com/assets/9421857/20213641/f0ca3ec6-a809-11e6-8068-2e6c29e95ec4.png)

Here are my settings in GLPI 9.1:
Activated OCS Plugin in GLPI 9.1
![ocs plugin](https://cloud.githubusercontent.com/assets/9421857/20213401/d1eac58a-a808-11e6-9f5e-5e29a4a8ad12.png)

GLPI: 
OCS Plugin-Server configuration:
OCSNG Server:
![0_ocs server](https://cloud.githubusercontent.com/assets/9421857/20213404/d1ec5a08-a808-11e6-914b-2ab721739391.png)
Test:
![1_ocs db test](https://cloud.githubusercontent.com/assets/9421857/20213403/d1ec00da-a808-11e6-98f9-05ddf3dd5b36.png)
Import options:
![2_ocs import options](https://cloud.githubusercontent.com/assets/9421857/20213402/d1eb27be-a808-11e6-92ba-aef5954062c8.png)
Datas to import:
![3_ocs datas to import](https://cloud.githubusercontent.com/assets/9421857/20213405/d1ece522-a808-11e6-9fee-da77a0c46526.png)

When importing computers from OCS to GLPI with the Plugin i got the Computername but nothing else.
See:
![ocs_glpi_computers](https://cloud.githubusercontent.com/assets/9421857/20213756/804b9086-a80a-11e6-9663-07a4f6ab7514.png)

The drives, Software and all other stuff is empty:
![ocs_glpi_nb-df](https://cloud.githubusercontent.com/assets/9421857/20213781/98cb9250-a80a-11e6-927b-41fa5a460e16.png)

I don´t have any idea.
Thanks for help!

regards,
Darkentik

**Comment by tsmr** [comment]
For sotwares : https://github.com/pluginsGLPI/ocsinventoryng/wiki/Software-Import

For others informations, can you try this fix ? 
https://github.com/pluginsGLPI/ocsinventoryng/issues/52

**Comment by Darkentik** [comment]
> For others informations, can you try this fix ?
#52

So when i understand it right i have to install my ocsinventoryng software new to my server or?
If i´m right then i would download the version from the "Code" section from here ok?
Thanks.
