### ISSUE TITLE
Error on import computers on GLPI

### ISSUE THREAD

**Issue by grillosoft** [pluginsGLPI/ocsinventoryng#56]
Hi, my name is Juan, my english is no very good, sorry by that.

The problem is this.

When i import a computer, the system show a screen in blank.

The versions from my system are:
OCS Server 2.0.5
GLPI: 0.9.1.1
OcsInventoryNG: 1.2.3
Linux: Debian 7 (Wheezy)
PHP 5.4.45-0+deb7u5
Server version: Apache/2.2.22 (Debian)
MySQL:  Ver 14.14 Distrib 5.5.44, for debian-linux-gnu (x86_64) using readline 6.2

I show the Print Screen in order

![1](https://cloud.githubusercontent.com/assets/23530853/20403512/73884cb4-acd7-11e6-940f-c5bf63c6cce2.png)

![2](https://cloud.githubusercontent.com/assets/23530853/20403511/738317bc-acd7-11e6-9b80-9f2b9863ae3f.png)

![3](https://cloud.githubusercontent.com/assets/23530853/20403510/73825192-acd7-11e6-9352-2703e8586cc0.png)

![4](https://cloud.githubusercontent.com/assets/23530853/20403509/7380ad56-acd7-11e6-9929-c1151255e6c3.png)

The computer not show the hardware, the software and the TAG to the information.

The screen from my OCS Inventory Server from the PC

![5](https://cloud.githubusercontent.com/assets/23530853/20404147/0255bc54-acda-11e6-881b-0766e4c4b901.png)

**Comment by tsmr** [comment]
Try this fix : https://github.com/pluginsGLPI/ocsinventoryng/issues/52

**Comment by grillosoft** [comment]
Thanks tsmr, the problem was that. I just upgrade the OCS Inventory Server and fix the problem.
