### ISSUE TITLE
Pb display ocsinventoryng 1.9.1 on GLPI 9.1.1

### ISSUE THREAD

**Issue by denisit29** [pluginsGLPI/ocsinventoryng#61]
Hi,
Today I updated Glpi to 9.1.1 and the plugin ocs to 1.9.1. Now I cannot display inventories of computers and the parameters of the server Ocs. 
I've got this error in apache logs : "**_PHP Fatal error:  Arrays are not allowed in class constants in /var/www/html/glpi/plugins/ocsinventoryng/inc/snmpocslink.class.php on line 43_".
The line 43 is : " _const CARTRIDGE_COLOR_CYAN = array('cyan');_ "

Thanks for help.

**Comment by tsmr** [comment]
Already corrected : https://github.com/pluginsGLPI/ocsinventoryng/issues/59

**Comment by denisit29** [comment]
Ok thanks.
