### ISSUE TITLE
PHP < 5.6 Fatal error in the configuration

### ISSUE THREAD

**Issue by alias59** [pluginsGLPI/ocsinventoryng#66]
Hello,

Currently on the glpi 9.1.1 so the version ocsinventoryng 1.3.1

Fatal error: Arrays are not allowed in class constants in /home/colaert/glpi/plugins/ocsinventoryng/inc/snmpocslink.class.php on line 43

`const CARTRIDGE_COLOR_CYAN = array('cyan');
  const CARTRIDGE_COLOR_MAGENTA = array('magenta');
  const CARTRIDGE_COLOR_YELLOW = array('yellow', 'jaune');
  const CARTRIDGE_COLOR_BLACK = array('black', 'noir');`

**Comment by tsmr** [comment]
Already corrected : https://github.com/pluginsGLPI/ocsinventoryng/issues/59

**Comment by alias59** [comment]
Thank you

**Comment by tsmr** [comment]
Yes it's already fixed : https://github.com/pluginsGLPI/ocsinventoryng/issues/59
