### ISSUE TITLE
I can't see inventory

### ISSUE THREAD

**Issue by kikelin** [pluginsGLPI/ocsinventoryng#68]
Hi guys,

I'm using glpi v9.1 and ocs complement v1.2.3. 

I sincronized ocs with glpi and all my computers are there when i use glpi user. When i use other user, 

When I use another user, even though I have administrator permissions, this user can not see the inventory park.

In the user profiles tab, I have configured this so that the 'technical' user has all the permissions on the add-on, but still, a 'technical' user can not query the assets.
What is my problem?

Thanks so much!

**Comment by tsmr** [comment]
Can you give us your PHP version ?

**Comment by kikelin** [comment]
v 5.6

**Comment by kikelin** [comment]
but with user 'glpi' (Administrator), i can see all.

**Comment by tsmr** [comment]
Have you errors in debug mode & into glpi\files\_log files ?

**Comment by kikelin** [comment]
i don't see nothing with references it.

**Comment by tsmr** [comment]
Can you give us a screenshot which see problem for your user ?

**Comment by kikelin** [comment]
[With GLPI USER.docx](https://github.com/pluginsGLPI/ocsinventoryng/files/660743/With.GLPI.USER.docx)

**Comment by tsmr** [comment]
Have you create entities ? because you have entity column

**Comment by kikelin** [comment]
i have a unique entity with a son. But i can't see my assets over any entity.

**Comment by amma35** [comment]
Please open a new exit if the problem persists.
