### ISSUE TITLE
SNMP Import history

### ISSUE THREAD

**Issue by Krakozaber** [pluginsGLPI/ocsinventoryng#69]
GLPI - 9.1.1
OCS Inventory NG - 2.2.1
Plugin OCS Inventory NG - 1.3.2

ocsng_snmpfullsync.sh does not write history

**Comment by tsmr** [comment]
Have you checked SNMP History into plugin server setup ?

**Comment by Krakozaber** [comment]
Yes

**Comment by tsmr** [comment]
In next version, we have fixed some things for history. If you can, you can try master version (for TEST ONLY)

**Comment by Krakozaber** [comment]
I try it. No result.
If you click Force Sync SNMP history has recorded, the problem is only when running synchronization by cron job using the script */glpi/plugins/ocsinventoryng/scriptsocsng_snmpfullsync.sh

**Comment by tsmr** [comment]
For test : Can you try to modify scripts/ocsng_snmpfullsync.php file

l52

```
$_SESSION["glpicronuserrunning"] = $_SESSION["glpiname"] = 'ocsinventoryng';
```

by

```
$_SESSION["glpicronuserrunning"] = $_SESSION["glpiname"] = 'yourlogin';
```

?

**Comment by Krakozaber** [comment]
Tried, recording appeared.

**Comment by tsmr** [comment]
It's ok for you ?

**Comment by Krakozaber** [comment]
Sorry, lost in translation, the record does not appear.

**Comment by tsmr** [comment]
I found the problem : 
Into GLPI, the method Update refuse to log data from script : 
https://github.com/glpi-project/glpi/blob/master/inc/commondbtm.class.php#L380

If you remove ```isset($_SESSION['glpiactiveentities_string'])``` i think all is logued

**Comment by tsmr** [comment]
Issue opened : 
https://github.com/glpi-project/glpi/issues/1460

**Comment by Krakozaber** [comment]
glpi-project/glpi#1460 - it`s work
