### ISSUE TITLE
PHP 5.5 issue

### ISSUE THREAD

**Issue by AnaelMobilia** [pluginsGLPI/ocsinventoryng#71]
Dear GLPi user.

For bug reports, you can open an issue here, provide us : 
- The version of the plugin.
1.3.1

- The version of your GLPI.
9.1.1

- The steps to reproduce your issue.
Use PHP 5.5.38
Enable plugin, add an OCS server, save => crash

[Fri Dec 30 18:51:57.155164 2016] [:error] [pid 6816:tid 1872] [client ::1:56805] PHP Fatal error:  Arrays are not allowed in class constants in C:\\xampp\\htdocs\\glpi\\plugins\\ocsinventoryng\\inc\\snmpocslink.class.php on line 43, referer: http://localhost/glpi/plugins/ocsinventoryng/front/ocsserver.php

**Comment by tsmr** [comment]
Yes it's already fixed : https://github.com/pluginsGLPI/ocsinventoryng/issues/59

**Comment by AnaelMobilia** [comment]
Thanks !
