### ISSUE TITLE
Trace_Delete

### ISSUE THREAD

**Issue by dimavelichko** [pluginsGLPI/ocsinventoryng#72]
Centos7
GLPI 9.1.1 + Latest version OCS plugin, where is setting Trace_Delete?

**Comment by tsmr** [comment]
https://github.com/pluginsGLPI/ocsinventoryng/wiki/TRACE_DELETED-parameter

**Comment by dimavelichko** [comment]
I have "in requested URL /ocsreports was not found on this server"

Get Outlook for iOS




On Wed, Jan 11, 2017 at 12:46 PM +0300, "Xavier CAILLAUD" <notifications@github.com> wrote:












https://github.com/pluginsGLPI/ocsinventoryng/wiki/TRACE_DELETED-parameter
