### ISSUE TITLE
Sql error - import new computer from Ocs

### ISSUE THREAD

**Issue by pkolan** [pluginsGLPI/ocsinventoryng#75]
Hello,
when I want to import new computer, nothing happens. I have a connection to the Ocs server.
Ocs 2.3 on Ubuntu 16.04
GLPI 9.1.1 on the same server
Ocs Inventory NG 1.3.2

Sql-errors.log

2017-01-27 08:35:54 [2@ocs]
  *** MySQL query error:
  SQL: SELECT * FROM `glpi_plugin_ocsinventoryng_ocsservers` WHERE `HARDWARE_ID` = 21
  Error: Unknown column 'HARDWARE_ID' in 'where clause'
  Backtrace :
  ...ns/ocsinventoryng/inc/ocsdbclient.class.php:133 
  plugins/ocsinventoryng/inc/ocsclient.class.php:279 PluginOcsinventoryngOcsDbClient->getComputerRule()
  plugins/ocsinventoryng/hook.php:1641               PluginOcsinventoryngOcsClient->getOcsComputer()
  inc/plugin.class.php:1196                          plugin_ocsinventoryng_ruleCollectionPrepareInputDataForProcess()
  inc/rulecollection.class.php:1622                  Plugin::doOneHook()
  inc/rulecollection.class.php:1448                  RuleCollection->prepareInputDataForProcessWithPlugins()
  ...ins/ocsinventoryng/inc/ocsserver.class.php:2526 RuleCollection->processAllRules()
  ...ins/ocsinventoryng/inc/ocsserver.class.php:2047 PluginOcsinventoryngOcsServer::importComputer()
  plugins/ocsinventoryng/front/ocsng.import.php:73   PluginOcsinventoryngOcsServer::processComputer()

**Comment by tsmr** [comment]
Can you give me the criteria used into the two rules engines for OCSNG ?

**Comment by pkolan** [comment]
[www.sedal.pl/Pawel/images/glpi_rule1.jpg](url)
[www.sedal.pl/Pawel/images/glpi_rule2.jpg](url)
Can I export rule to the file?

**Comment by pkolan** [comment]
![glpi_test](https://cloud.githubusercontent.com/assets/25383809/22368910/4b7bb082-e489-11e6-97d6-0ca35a535e0f.jpg)
![glpi_rule2](https://cloud.githubusercontent.com/assets/25383809/22368916/5416ea5e-e489-11e6-82af-1103f42e774a.jpg)
![glpi_rule1](https://cloud.githubusercontent.com/assets/25383809/22368915/5415494c-e489-11e6-92bf-cee80ba254a5.jpg)

**Comment by pkolan** [comment]
Any ideas?

**Comment by tsmr** [comment]
I still can not replicate your problem

**Comment by pkolan** [comment]
Ok, I will be waiting

**Comment by tsmr** [comment]
Can you try with last version ?

**Comment by ndlpaix56** [comment]
OCS 2.3
GLPI 9.1.2
PLUGIN OCS INVENTORY NG 1.3.2

Hello,
I reproduced the bug when GLPI and OCS are installed on the same database.

The PHP code is searching glpi_plugin_ocsinventoryng_ocsservers table in OCS database.
>>>> ocsdbclient.class.php:134 :  if (self::OcsTableExists($table))
As is the same database, it returns true of course

If you change by if (self::OcsTableExists($table) && $table != "glpi_plugin_ocsinventoryng_ocsservers") {
the synchronization is success.

The question is why we can't installed this softwares in the same database ?

Sorry for my bad English ... I am French and I never have the opportunity to speak English.

**Comment by pkolan** [comment]
It works, now i can import computers.
Thanks ndlpaix56
