### ISSUE TITLE
PHP error when opening computer in GLPI

### ISSUE THREAD

**Issue by Edzilla2000** [pluginsGLPI/ocsinventoryng#76]
- The version of the plugin: 1.3.2
- The version of your GLPI: 9.1.2

I have just upgraded to GLPI 9.1.2 and upgraded your plugin as web.
Now if I open a computer in GLPI when the plugin is enabled, I get a PHP error when opening a computer: 

[Sun Jan 29 19:04:02.566135 2017] [:error] [pid 28553] [client 192.168.195.1:7030] PHP Fatal error:  Call to a member function fetch_assoc() on boolean in /var/www/glpi/inc/dbmysql.class.php on line 308

**Comment by tsmr** [comment]
Can you tell me what you have into glpi/files/_log/sql_errors.log ?

And your PHP version ?

**Comment by Edzilla2000** [comment]
This is what I have in the logs: 
2017-01-30 09:22:10 [2@astarte]
  *** MySQL query error:
  SQL: SELECT COUNT(*) AS cpt
             FROM `glpi_plugin_ocsinventoryng_winupdates` WHERE `computers_id`=\'2310\'
                                                AND entities_id NOT IN (\'0\')
  Error: Unknown column 'entities_id' in 'where clause'
  Backtrace :
  inc/db.function.php:319
  inc/commondbtm.class.php:1876                      countElementsInTable()
  inc/commondbtm.class.php:2372                      CommonDBTM->canUnrecurs()
  inc/computer.class.php:524                         CommonDBTM->showFormHeader()
  inc/commonglpi.class.php:632                       Computer->showForm()
  inc/commonglpi.class.php:1149                      CommonGLPI->showPrimaryForm()
  front/computer.form.php:107                        CommonGLPI->display()


PHP version is PHP Version 5.6.29-0+deb8u1

**Comment by tsmr** [comment]
OK, now a computer can be a recursive object. So we must to change SQL tables

Can you do this query into your mysql Server ? 
```
ALTER TABLE `glpi_plugin_ocsinventoryng_winupdates` 
               ADD `entities_id` int(11) NOT NULL DEFAULT '0';
```

**Comment by Edzilla2000** [comment]
Ok, thix fixed it.
