### ISSUE TITLE
Upgrade issues

### ISSUE THREAD

**Issue by klamu** [pluginsGLPI/ocsinventoryng#82]
Hey all

I'm trying to upgrade my GLPI/OCS installation to the latest versions

current (production) setup:  GLPI: 0.72.4,  OCS Import  1.3.0
upgrade to:                          GLPI 9.1.1, OCS Inventory NG 1.3.2

my upgrade path is:
1.  upgrade GLPI 0.72.4 -> GLPI 0.90.1
 2.  remove OCS massimport files, instal pluginl glpi-ocsinventoryng-1.2.1
3.  upgrade GLPI 0.90.1 to GLPI 9.1.1
 4.  upgrade plugin glpi-ocsinventoryng-1.3.2

the GLPI-upgrade works without issues,

but when I install glpi-ocsinventoryng (step 2)  
the web-browser (to run the install) stops   - when I click install again - a message is displayed (fast - can not see it) - and then it allows me to enable the plugin
``` output during ocsinventoryng installation:
Change of the database layout - ocs_glpi_ocslinks (17 minutes 49 seconds)
Task completed. (2 minutes 56 seconds)
Task completed. (1 minutes 52 seconds)

-> as far as i can see everything is there, ocs-servers, rules,....
-> changed the ocs-servers-mode to Expert and tried to run script ocsng_fullsync:

# ./ocsng_fullsync.sh --thread_nbr=1 --server_id=4 --nolog --debug
Mi 8. Feb 12:29:49 CET 2017 ./ocsng_fullsync.sh started
    Manage delete items in OCS server #4: "hsvocs1"
PHP Notice:  Undefined offset: 1 in /var/www/html/glpi/plugins/ocsinventoryng/scripts/ocsng_fullsync.php on line 41
=====================================================
    Thread #1: starting (1/1)
  *** MySQL query error:
  SQL: SELECT *
                FROM `glpi_plugin_ocsinventoryng_servers`
                WHERE `plugin_ocsinventoryng_ocsservers_id` = \'4\'
  Error: Table 'glpi.glpi_plugin_ocsinventoryng_servers' doesn't exist
  Backtrace :
  plugins/ocsinventoryng/inc/server.class.php:40     
  ...s/ocsinventoryng/scripts/ocsng_fullsync.php:276 PluginOcsinventoryngServer->getFromDBbyOcsServer()
  ...s/ocsinventoryng/scripts/ocsng_fullsync.php:159 SecondPass()
    Thread #1: cannot get server information
    Thread #1: done!!
=====================================================
```
cleaning up.

-> no issues in migration-log files

after some investigation; I found the following is missing / wrong:

tables not exist in DB:  (needed to recreate them based on the ./install/mysql/"empty.sql files
glpi_plugin_ocsinventoryng_notimportedcomputers and glpi_plugin_ocsinventoryng_servers

some issues with wrongly named col., needed to alter them:
```
ALTER TABLE `glpi`.`glpi_plugin_ocsinventoryng_threads` 
CHANGE COLUMN `ocsservers_id` `plugin_ocsinventoryng_ocsservers_id` INT(11) NOT NULL DEFAULT '1' ;

ALTER TABLE `glpi`.`glpi_plugin_ocsinventoryng_details` 
CHANGE COLUMN `ocsservers_id` `plugin_ocsinventoryng_ocsservers_id` INT(11) NOT NULL DEFAULT '1' ;

ALTER TABLE `glpi`.`glpi_plugin_ocsinventoryng_details` 
CHANGE COLUMN `plugin_massocsimport_threads_id` `plugin_ocsinventoryng_threads_id` INT(11) NOT NULL DEFAULT '0' ;
```
after all this changes, my ocsng_fullsync.sh works, and I can see the tasks in the frontend. 

I doubt this process is how it should be, and I'm not confident to put this into production,
can you guide me where I went wrong ?

thanks
Klaus

**Comment by amma35** [comment]
It will be difficult to correct, it is a very old version.
It should be with a developer or a partner for a development.
