### ISSUE TITLE
Unable to import new computers

### ISSUE THREAD

**Issue by grcmec** [pluginsGLPI/ocsinventoryng#89]
Hello all.

We are unable to import new computers, in debug mode we receibe the following message:

PHP Notice: Undefined index: plugin_fields_containers_id in C:\xampp\htdocs\glpi\plugins\fields\inc\container.class.php at line 900
PHP Notice: Undefined index: plugin_fields_containers_id in C:\xampp\htdocs\glpi\plugins\fields\inc\container.class.php at line 904
PHP Notice: Undefined index: plugin_fields_containers_id in C:\xampp\htdocs\glpi\plugins\fields\inc\container.class.php at line 751
PHP Notice: Undefined index: name in C:\xampp\htdocs\glpi\plugins\fields\inc\container.class.php at line 756

Fatal error: Class 'PluginFieldsComputer' not found in C:\xampp\htdocs\glpi\plugins\fields\inc\container.class.php on line 757

- The version of the plugin 1.3.3
- The version of your GLPI. 9.1.2

Please help.

**Comment by amma35** [comment]
This bug is related to the fields plugin. 

Please open an issue on the fields plugin. 

Thanks.
