### ISSUE TITLE
Import new computers returns no result

### ISSUE THREAD

**Issue by KyleChou** [pluginsGLPI/ocsinventoryng#93]
Dear GLPi user.

there is no result when i click Import new computers

**Comment by tsmr** [comment]
Please add more informations

Plugin setup / rules / erros in /glpi/files/logs/ logs errors

**Comment by amma35** [comment]
@KyleChou no additional information?

**Comment by amma35** [comment]
I'm closing for now without answer, feel free to reopen if issue persists.
