### ISSUE TITLE
Import computers from differents OCS databases

### ISSUE THREAD

**Issue by ClaudioNinin** [pluginsGLPI/ocsinventoryng#95]
Hello,

OCS Inventory NG 1.3.3
GLPI 9.1.2
I have two differents OCS databases and they are configureted in OCS Inventory NG.
When I try to import some computer the plugin every connect the same database. 
I test the connection in the both database and the status is OK. Can you help me?

Best regards,

Cláudio Ninin

**Comment by amma35** [comment]
Hi,
The selection of the server works well?
![setup](https://user-images.githubusercontent.com/15138371/34246740-1f867af8-e630-11e7-97ae-6d7e416a2e50.png)

**Comment by amma35** [comment]
I'm closing for now without answer, feel free to reopen if issue persists.
