### ISSUE TITLE
GLPI to OCS (Windows)

### ISSUE THREAD

**Issue by airnike** [pluginsGLPI/ocsinventoryng#97]
Hi all,

Not sure if this is the correct place to ask but pls redirect me to the proper place if this is not the place. Previously my GLPI is working nicely with OCS(Ubuntu) but I swap to OCS (Windows) and now synchronization doesn't work. DB connection failed. 

GLPI - version 9.1.2
Plugin - OCS Inventory NG version 1.3.3
i keyed in the information at TOOLS ? OCS INVENTORY NG

everything is exactly the same with the previous Linux server but the DB connection failed. 

I have ensured that from the GLPI server, I can telnet to the OCS Inventory Server
From the GLPI Server, the MySQL can also remote access OCS DB. 

Is there something missing or?

**Comment by amma35** [comment]
Still the connection problem?

**Comment by amma35** [comment]
I'm closing for now, feel free to reopen if issue persists.
