### ISSUE TITLE
Problem choosing a server from list when importing

### ISSUE THREAD

**Issue by PeeqPL** [pluginsGLPI/ocsinventoryng#98]
Hello!
I'm using:
- GLPI 9.1.6
- OCS Inventory NG  1.3.3
- Two OCSInventory Server 2.3.1

I have a problem choosing a server from the list. Always like I select another server than the default I'm redirected back to default. Sometimes it is written that I chose another server but after selecting sync I see data from the default server.
If I deactivate the default server then I can sync all the data from the second server.
In the first tab: server setup all works fine. The problem is with all the other tabs.
I have tried on many browsers: Opera, Firefox, Internet Explorer ;), Chrome
P.S sorry for my english :)

**Comment by Luiginoo** [comment]
Same problem on my GLPI server 
GLPI 9.1.6
OCS inventory NG 1.3.3
Any suggestions ?

**Comment by amma35** [comment]
Have you errors in debug mode & into glpi\files_log files ?

**Comment by amma35** [comment]
I'm closing for now without answer, feel free to reopen if issue persists.
